### PR TITLE
DTypes for Concat, UpSampling, Reshape, BlockGrad, SwapAxis and ElementWiseSum

### PR DESCRIPTION
**Pull request by vchuravy**
This extends concat and upsampling to work with all dtypes.

cc: @piiswrong 

### Todo:
- [x] Tests

### CODE REVIEW

**Comment by piiswrong** [comment]
These extensions are fairly similar. Just add consistency tests and it should be good to merge

**Comment by vchuravy** [comment]
All these operators are fairly easily extended to multiple DTypes.

**Comment by piiswrong** [comment]
LGTM

**Comment by vchuravy** [comment]
@tqchen Should I rebase or can you merge?

**Comment by sxjscience** [comment]
@vchuravy Could you rebase and I'll merge?

**Comment by vchuravy** [comment]
rebased.

**Comment by sxjscience** [comment]
@vchuravy How about to squash them to a single commit and I'll merge it after the Travis test.

**Comment by vchuravy** [comment]
Each of the commits is independent for each operator, so I prefer keeping them atomic

**Comment by sxjscience** [comment]
@vchuravy Fine.

**Pull request merged**
