### PR TITLE
[Scala] Nnvm sym op

### PR DESCRIPTION
**Pull request by javelinjs**
https://github.com/dmlc/mxnet/issues/3312

Symbol ops done, will modify NDArray today

### CODE REVIEW

**Comment by piiswrong** [comment]
please rebase on dmlc:nnvm

**Comment by tqchen** [comment]
Because there is a force push to nnvm, it is recommended to copy your changes out, do a clean reset to nnvm branch's head, and then copy your changes in to commit

**Comment by javelinjs** [comment]
OK, I'll copy these changes to the latest code base. Still working on the `NDArray` part

**Comment by javelinjs** [comment]
nnvm & code-generation support for `NDArray` finished, while there still exists some minor issues which I'll fix soon.
Also ping @Ldpe2G to review the changes of the NDArray function interfaces.

**Comment by piiswrong** [comment]
great. Could you do a rebase?

**Comment by javelinjs** [comment]
@piiswrong Sure, I pull the request just to preview the changes. My current branch is kind of mess, I'll rebase and open a new PR.
What does 'backward compatibility' mean?

**Comment by piiswrong** [comment]
@javelinjs Is the scala user facing api changed?
Can users run their old scripts on the new version without modification?

**Comment by javelinjs** [comment]
@piiswrong a little, pls refer to the changes in examples/ and core/src/test

**Comment by piiswrong** [comment]
So only argmaxChannel was changed? I think that's fine

**Comment by javelinjs** [comment]
@piiswrong previously, I hand-write function names in Scala and change those underscore-case functions (in C) to camel-case. Now code-generation doesn't do this, so several pieces of the function names may change, but not many.

**Comment by javelinjs** [comment]
move to #3361

**Pull request closed without merging**
