### PR TITLE
API docs formatting/review changes and scala tutorial added

### PR DESCRIPTION
**Pull request by Roshrini**
Made code formatting and spelling correction changes to Python and Scala API docs. Added one scala tutorial.

### CODE REVIEW

**Comment by piiswrong** [comment]
why remove all the >>>? It seems to be the standard way of displaying mixed python code and output

**Comment by Roshrini** [comment]
We had some discussions around this and turned out that due to >>>, it becomes difficult to copy paste the code for users while trying those examples. So, removes those.

**Comment by piiswrong** [comment]
Has there been complaints about this?
This is standard used every where for mixed data and code.
for example: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

**Comment by Roshrini** [comment]
If you see this new changed link https://github.com/Roshrini/mxnet/blob/b1cd636be561b5443b47046bc1614177a4eb62e6/docs/api/python/kvstore.md

You can see if there is separate function without >>>, it becomes easy to just see input code block and then output code block just below that.

**Comment by Roshrini** [comment]
new pull request opened

**Pull request closed without merging**
