### PR TITLE
add mean-file to argument

### PR DESCRIPTION
**Pull request by qiaohaijun**
different dataset will have different mean file.

### CODE REVIEW

**Comment by winstywang** [comment]
We don't need that actually. Computing mean file on imagenet is quite slow. Do you observe obvious performance difference between mean value and mean file?

**Comment by qiaohaijun** [comment]
I am training the 22k imagenet, I think the default value maybe not suitable

**Comment by winstywang** [comment]
@qiaohaijun Do you have any evidence for that? We have trained 22k imagenet, it works well.

**Comment by qiaohaijun** [comment]
ok, I close this pr first, when I find the evidence,then reopen

**Pull request closed without merging**
