### PR TITLE
expose ndarray in c++ dll, and add ndarray c++ example

### PR DESCRIPTION
**Pull request by hjk41**

### CODE REVIEW

**Comment by piiswrong** [comment]
Probably should add a makefile?

**Comment by hjk41** [comment]
@piiswrong right. Let me add a makefile. Travis checking is complaining about some format errors in Python files, which I didn't touch at all. Do you know what is going on?

**Comment by piiswrong** [comment]
It's happening to all PR. somehow the rules for python got more strict.

**Comment by antinucleon** [comment]
Fixed in https://github.com/antinucleon/mxnet/commit/30e742b7a427ab0392d9713bc62478470607fc5d

After I merge it, lint job will be normal

**Pull request merged**
