### PR TITLE
MXNet on Spark

### PR DESCRIPTION
**Pull request by javelinjs**
Just suffered several tough weeks, sorry for the late PR.

I have tested the mxnet-spark on EC2 g2 & c4 instances, which works well. As I mentioned in README.md, there still exists some pitfalls which we need to solve in the future. I'll also open another issue to list all these problems and make a roadmap.

@liyuance Tech manager of Qihoo 360's infrastructure team, is willing to deploy MXNet on Spark on their  Yarn clusters. He gave quite a lot of suggestion during my development.

### CODE REVIEW

**Comment by piiswrong** [comment]
This is great work. Cheers!

BTW, did you solve the multi instance problem?

**Comment by javelinjs** [comment]
Not yet. Currently workers have to run in different executors (processes).

**Comment by piiswrong** [comment]
Is there anything that prevent this from being merged now?

**Comment by javelinjs** [comment]
I'll update and merge.

**Pull request merged**
