### PR TITLE
training accuracy (cumulative -> real time)

### PR DESCRIPTION
**Pull request by mavenlin**
reset the eval_metric so that the training accuracy is real time. The cumulative accuracy is quite a problem when plotting, especially for the initial epochs.

### CODE REVIEW

**Comment by piiswrong** [comment]
I prefer realtime too. My solution is to set auto_reset=True in metric

**Comment by Piyush3dB** [comment]
Hello,

This change is breaking the parser script in `tools/parse_log.py`.  When I make the following change to `model.py` then the parser script runs fine:

```
--- a/python/mxnet/model.py
+++ b/python/mxnet/model.py
@@ -270,6 +270,10 @@ def _train_multi_device(symbol, ctx, arg_names, param_names, aux_names,
             if epoch_size is None or nbatch >= epoch_size:
                 break
 
+        name_value = eval_metric.get_name_value()
+        for name, value in name_value:
+            logger.info('Epoch[%d] Train-%s=%f', epoch, name, value)
+
         toc = time.time()
         logger.info('Epoch[%d] Time cost=%.3f', epoch, (toc - tic))
 
```

This is because the parser script looks for the regular expression `.*Epoch\[(\d+)\] Train.*=([.\d]+)` to retrieve the training accuracy.

Is this an acceptable fix for this issue?  If so I'm happy to prepare a PR for it...

Best Regards,
@Piyush3dB

**Comment by mli** [comment]
@mavenlin i don't understand why `logger.info` was deleted. is it because the real time accuracy is quite noisy?

**Comment by mavenlin** [comment]
@mli We can put this back, I delete this because the information is redundant, it is already printed in the real time training accuracy.

**Pull request merged**
