### PR TITLE
[RFC/WIP] RTC without NVRTC

### PR DESCRIPTION
**Pull request by vchuravy**
I am working on using the experimental GPU codegen for Julia (https://github.com/JuliaGPU/julia & https://github.com/JuliaGPU/CUDAnative) to create kernels for MXNet.
For that purpose I need to insert the CuModule directly and thus bypass NVRTC.

### CODE REVIEW

**Comment by tqchen** [comment]
The naming convention of C API, should be CreateFromPTX?

**Comment by vchuravy** [comment]
@tqchen Good idea. I have one problem before I can make this fully useful. For the Julia GPU codegen we have a NDArray-like type that exists on the GPU so you can just write normal Julia code and use all the convenience methods of Julia arrays on the GPU. Currently `decorate` inserts the shape of the array into the code we compile qith nvrtc, but on the Julia side I can't do that. Instead I would need to setup the array object in GPU memory and then set the data pointer to the NDArray. 

Any idea how to non-disruptively do this with the current code path?

**Comment by piiswrong** [comment]
I guess since you are directly inserting PTX you can use your own convention.

**Comment by vchuravy** [comment]
Yes, I just then also need to launch the kernel with that convention.

**Comment by piiswrong** [comment]
I see. I can think of two ways:
1. Add a void * params at the end that contains frontend specific parameter to kernel
2. Make a Julia specific rtc module and put it in julia

**Comment by vchuravy** [comment]
Would it be acceptable to have code like https://gist.github.com/vchuravy/ec05e427e99e4ef32d64934f3959a17b in the main repository or should I develop this as a plugin?

**Comment by piiswrong** [comment]
I think it's better to put it in jl repo, or as a plugin

**Comment by vchuravy** [comment]
Ok closing for now

**Comment by vchuravy** [comment]
So after looking into this a bit more in detail, here are my thoughts and maybe we can find a way to make this easier during the way to 1.0

To compile a julia function as a kernel, I need type information for that function. In most cases we will want to pass in DeviceArrays that use data from NDArrays. These DeviceArrays are parameterized, by DType and NDims. For each signature combination of DType and NDims I need to compile a new kernel. 

This means that `InferShape` and `InferType` need to have run already before I can initialise the PTX, that then get's translated into a `CUmodule` and `CUfunction` optimized per device and then run. 

I then need to communicate that information from a safe point (preferably a synchronous call, async might work but requires a lot more work and is fragile). The current outline of how this might look like can be seen at https://github.com/vchuravy/JLNDArrayOp .
Tomorrow I am going to write the Julia side of this and making it more safe (there are some unsafe hacks in there right now.)

Any feedback would be welcome.

**Pull request closed without merging**
