### PR TITLE
fix resnet-v2 segmenet fault problem

### PR DESCRIPTION
**Pull request by glingyan**
Signed-off-by: lingyan <lingyan.guo@intel.com>

### CODE REVIEW

**Comment by mli** [comment]
i tried to test this patch, but failed to run `prepare_mkl.sh`:

```bash
cp: target ‘./mklml_lnx_2017.0.2.20161122/license.txt’ is not a directory
basename: missing operand
```

**Comment by piiswrong** [comment]
This part of code is heavily modified in the nnvm branch. Consider moving to nnvm or all this will be lost once 0.9 is released

**Comment by glingyan** [comment]
@mli , could you just run  ./prepare_mkl.sh  0 ~/mklml to test
0 means gnu gcc
~/mklml is  dest folder

lingyan@aocl-server:~/intel_mxnet/mxnet$ ./prepare_mkl.sh  0 ~/mklml
--2016-12-13 19:41:28--  https://github.com/dmlc/web-data/raw/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20161122.tgz
Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.80
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.80|:913... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20161122.tgz [following]
--2016-12-13 19:41:29--  https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/mklml-release/mklml_lnx_2017.0.2.20161122.tgz
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.80|:913... connected.
Proxy request sent, awaiting response... 200 OK
Length: 58423364 (56M) [application/octet-stream]
Saving to: ‘./mklml_lnx_2017.0.2.20161122.tgz’

mklml_lnx_2017.0.2. 100%[===================>]  55.72M  3.16MB/s    in 17s     

2016-12-13 19:41:50 (3.21 MB/s) - ‘./mklml_lnx_2017.0.2.20161122.tgz’ saved [58423364/58423364]

/home/lingyan/mklml/ mklml_gnu 1

**Comment by glingyan** [comment]
@piiswrong  I tested in latest master
But will move to nnvm immediately

**Comment by piiswrong** [comment]
please fix lint. also please directly submit this to nnvm. We are not accepting PR on master for this part of code

**Comment by mli** [comment]
@glingyan if i remember correctly, previous make will automatically run `prepare_mkl.sh` is MKL flag is set. now we need to do it manually?

**Comment by mli** [comment]
well, i think we need to specify `MKLML_ROOT` for make. can you please update Makefile, if it is not specified, use `MXNET_ROOT/mklml` as the default location?

**Comment by mli** [comment]
confirmed #4085 is fixed. 

but one more problem is resnet is 10x slower on cpu than single k40. can you please double check if there is something not correctly set?

**Comment by glingyan** [comment]
@mli:

1.      Make will execute prepare_mkl.sh as before , By default, USE_BLAS=atlas, MKLML_ROOT=/usr/local

a.      Makefile will use prepare_mkl.sh 0 $MKLML_ROOT to download mkl

2.      I have tested in multi-machine, but have no problem

a.      My college get the same problem as you when run  prepare_mkl.sh directly, so I guest your cause is the same

**Comment by glingyan** [comment]
Will check , should be something not support very well

**Comment by zhenlinluo** [comment]
@mli  when you check the perf. on CPU, do you set below var? 
a.	KMP_AFFINITY=granularity=fine,compact,1,0
b.	OMP_NUM_THREADS=vCPUs / 2

Also do you run "numactl -i 0-1 python xxx" when you have two socket CPU?

**Comment by mli** [comment]
can you please only generate "[21:46:30] src/operator/pooling.cc:34: MKLPoolingOp Skip MKL optimization" once?

you can have a `static bool warn_generated = false `

**Comment by glingyan** [comment]
Will do that after my vocation

**Pull request merged**
