### PR TITLE
[OP] Move elemwise sum op to tensor fcompute

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
@piiswrong 

Other changes(fixes) in this PR

- Fix ROIPooling and Correlation's CPU backward because they assume out_grad buffer is zeroed @winstywang 
- Fix the broadcast_to's gradient(previous one won't have correct shape inference because axis parameter is not available in broadcast_to) @piiswrong 
- Fix the matrix op's gpu registration
- Fix warnings in C API ndarray

**Comment by tqchen** [comment]
please wait until checks finish before merge

**Comment by piiswrong** [comment]
I merged in master and test_operator.test_scalar_pow hangs in check_numeric_gradient.
Could you look into it?

**Comment by tqchen** [comment]
ok.. please test locall next time before we really do a force push.

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/pull/3482

**Pull request merged**
