### PR TITLE
Fix broadcast when both lhs and rhs needs broadcasting.

### PR DESCRIPTION
**Pull request by jermainewang**
@mli Fix the broadcasting problem in your notebook example. Added unittest.

### CODE REVIEW

**Comment by tqchen** [comment]
@jermainewang This is already handled via broadcast_add etc. any idea on directly redirect to these functions?

**Comment by jermainewang** [comment]
Does it also handle other stuffs like sub/div/mul/maximum/minimum ?

**Comment by mli** [comment]
yeah, check https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h#L429

**Comment by tqchen** [comment]
I guess actually they should be here https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_broadcast_op-inl.h

**Comment by jermainewang** [comment]
Ok, does that means we now have two `broadcast_to` in the code? One is defined in python another in c++. I will switch to the c++ version. Please correct me if i'm wrong. I will use the c++ `broadcast_to` combined with the `ufunc_helper` for all the `ufunc` function in python. Am I correct?

**Comment by jermainewang** [comment]
@tqchen I see. This code seems to have many redundant parts... It does not support maximum/minimum. The current way of adding this in python is here: https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L608
It seems cleaner.

**Comment by tqchen** [comment]
The c++ code enjoys being one step without resorting to broadcast_to, which I think should be preferred if available. Otherwise, the current way of resolving things is fine.

In either case, we should use the newer broadcast_to in c++ side.

**Comment by jermainewang** [comment]
I mean I agree use the `broadcast_to`. But the broadcast_plus and broadcast_mul just looks like monsters. It is much cleaner and easier to use the ufunc_helper in python to add new ufunc ops. I will keep it in the python right now until we have a easier way of defining ufunc with broadcast in c++.

**Comment by piiswrong** [comment]
I think backwardmul/div/pow etc can now be merged with function template with auto return type since we support c++11 with nvcc now.

**Comment by sxjscience** [comment]
@jermainewang The python `broadcast_to` is implemented by calling the C++ version https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L309-L331

We can simplify the code in the C++ side and add `max/min` and `broadcast_max/broadcast_min`.

**Comment by jermainewang** [comment]
Ok, I think the correct way to do this is still using the [`ufunc_helper`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L554) in python side. It accepts an argument `fn_array` which is a function to be called when both operands are of type `ndarray`. In current `mx.nd.add` implementation, it uses [`_internal._plus`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L625) for this argument. We could directly use `broadcast_plus` here for this function and remove the call to `broadcast_to`. This seems to be the minimal way of changing. What do you think @tqchen ?

And another problem for the c++ version broadcasting. It does not support:
```
a = mx.nd.ones((3,))
b = mx.nd.ones((4, 3))
c = a + b
```
This is a valid broadcasting with left padding. It fails here: https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_broadcast_op-inl.h#L57

The point is if we want the behavior to the same as `numpy`. We'd better allow this.

**Comment by sxjscience** [comment]
Changes like this shold be good.

**Comment by tqchen** [comment]
closing due to long time inactive

**Pull request closed without merging**
