### PR TITLE
[scala-package] fix the "too-wide" accessibilities of scala classes (mxnet-core)

### PR DESCRIPTION
**Pull request by CodingCat**
When going through the code of mxnet-core, I found that the accessibility of some classes are too wide, i.e. these classes shall not be exposed to the external usage

I cleaned these in this PR 

the other changes include

1. remove some author tags (as they are not allowed in ASF projects)

2. change the package name of examples from mxnet.examples to mxnetexamples: this change will make the development of examples in a full perspective of an external user, and it also helps to ensure that we are not mistakenly narrow the accessibilities 

@javelinjs @Ldpe2G would you mind helping to review?

### CODE REVIEW

**Comment by Ldpe2G** [comment]
LGTM and pls fix the package name of all the example run scripts under
https://github.com/dmlc/mxnet/tree/master/scala-package/examples/scripts

for example:
https://github.com/dmlc/mxnet/blob/master/scala-package/examples/scripts/run_visualization.sh#L16

Thanks.

**Comment by CodingCat** [comment]
@Ldpe2G thanks for reminding this, just committed the changes

**Comment by piiswrong** [comment]
is this good for merge?

**Comment by Ldpe2G** [comment]
@javelinjs

**Comment by CodingCat** [comment]
thanks

**Pull request merged**
