### PR TITLE
fix MKL warning in ubuntu

### PR DESCRIPTION
**Pull request by zhenlinluo**
@piiswrong  Eric, pls review, this fix compile warning of MKL files

### CODE REVIEW

**Comment by piiswrong** [comment]
there is a `type qualifier is meaning less on return type` warning that's not covered by this

**Comment by glingyan** [comment]
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
I do not get such error in gcc
could you share your build log?

**Comment by piiswrong** [comment]
include/mxnet/./././mkl_memory.h(83): warning: type qualifier on return type is meaningless

**Comment by piiswrong** [comment]
also please move mkl_memory into src/operator/mkl

**Pull request merged**
