### PR TITLE
[DOC] Refine note_engine.md

### PR DESCRIPTION
**Pull request by bryandeng**
Correct typos and improve wording.

### CODE REVIEW

**Comment by tqchen** [comment]
some changes related to #280

**Comment by bryandeng** [comment]
@tqchen A merge conflict will happen because of #280, please cherry-pick my second commit and let me open new PRs later.

**Comment by tqchen** [comment]
Can you do a rebase to merge the conflict, as shown by http://mxnet.readthedocs.org/en/latest/contribute.html#submit-a-pull-request

**Comment by bryandeng** [comment]
@tqchen Done!

**Comment by tqchen** [comment]
Thanks!

**Comment by bryandeng** [comment]
BTW, which tools do you use to make the figures? I also find some typos in figures.

**Comment by tqchen** [comment]
All the figures are made with google slide https://docs.google.com/presentation/d/1_u_0EybBWZObCDBAv4fmG6CsRzIzscRaY_xoZAtDA5o/edit?usp=sharing

**Comment by tqchen** [comment]
You can comment, or copy the slide to modify locally. The figures are on  https://github.com/dmlc/dmlc.github.io/tree/master/img/mxnet

**Comment by bryandeng** [comment]
Thanks!

**Pull request merged**
