### PR TITLE
Restruct get started

### PR DESCRIPTION
**Pull request by kevinthesun**
Restructure get started page to 'why mxnet' and 'installation'.
getstarted3

Move images to web-data: https://github.com/dmlc/web-data/pull/19
Resize images to 60%.
Make installation as index page.

@zackchase @sandeep-krishnamurthy

### CODE REVIEW

**Comment by piiswrong** [comment]
The why mxnet part doesn't look very convincing. Also its making installation harder to access. Let's remove it for now.

**Comment by zackchase** [comment]
@piiswrong disagree with you. We need to have solid high-level introduction to what MXNet is and what purpose it serves. Right now MXNet assumes the readers already knows what a deep learning acceleration library is, which is unacceptable. I agree that Installation needs to be as easy to reach as possible. One solution for is we can flip the order of the documents.

**Comment by zackchase** [comment]
@piiswrong We will have a new home page that will point to each document, however they both need to live within the Getting Started section. Let's change the order and approve this quickly so we can get to work on the improved home page.

**Comment by zackchase** [comment]
@kevinthesun Could you resize the images so that they are appropriate for the document?

**Comment by piiswrong** [comment]
In general yes. But this particular section is more like "why deep learning" than "why mxnet". It's probably better to call it "What's MXNet"

**Comment by zackchase** [comment]
@piiswrong No it's not. I imagine you're mistaken because you're only reading the first paragraph (perhaps because the picture is too big). It's a full-page document.

**Comment by piiswrong** [comment]
Also this image is too long. A thinner banner like image would be better as it won't hide the content below.

**Comment by piiswrong** [comment]
BTW we don't put images in main repo. They should go in web-data.

**Comment by zackchase** [comment]
@piiswrong Getting started is a *section*, not a page. It is not in the same page. They share a nav item. Nav item should point to categories, not pages (it should be somewhat balanced tree). 

Yes the images need to be sized, we've already discussed this above. 

Regarding the image repo, this seems like a horrible design decision. We shouldn't have dependencies among (as many as 3!) repos to make a single change to the site. It's fine to play by that for now. In the long run I think it's unacceptable.

**Comment by piiswrong** [comment]
Putting binaries in code repo will lead to extremely large repo size and clone can take a very long time.

**Comment by zackchase** [comment]
@piiswrong still that doesn't mean we need to dump all the static files in another repo does it? what are the alternatives? S3?

**Comment by piiswrong** [comment]
Hosting it on another server is more or less the same thing. Doing it ourselves means we need to handle DNS/CDN  and all that madness.

An alternative would be to put the docs folder itself in another folder.

**Comment by zackchase** [comment]
@piiswrong let's work out the long-term solution offline. In the short run - @kevinthesun can you please:
* resize the images
* commit them to the crazy image repo 
* flip the order of the documents so the Installation page appears first

Thanks!

**Comment by sandeep-krishnamurthy** [comment]
Long term solution - We will have quick installation commands (similar to pytorch) on home page and a link from there to the installation page. This will cover use-case brought up @piiswrong 

Also, I think in getting started page readers will see easily see Installation tab on the left which should serve the purpose.

**Pull request merged**
