### PR TITLE
Fixed without GPU using cpu

### PR DESCRIPTION
**Pull request by linkerlin**

### CODE REVIEW

**Comment by mli** [comment]
i was intentionally set default gpu='0' since cpu could be extremely slow on these networks

**Comment by tqchen** [comment]
close this PR as per @mli 's comment

**Comment by christallire** [comment]
@mli I have to say that that's not user friendly :( even simple warning could prevent users from hassle figuring out what's wrong with them.. I think that's why @linkerlin made PR at first place..

**Comment by mli** [comment]
@christallire i think you are right. we can use cpu as default but generate a warning such as "you'd better to use gpu"

**Pull request closed without merging**
