### PR TITLE
Add backward for sum_mid_internal

### PR DESCRIPTION
**Pull request by sxjscience**

### CODE REVIEW

**Comment by tqchen** [comment]
@jermainewang can you review this?

**Comment by piiswrong** [comment]
we should change these to using keyword argument

**Comment by sxjscience** [comment]
@piiswrong Do you mean to make it similar to numpy like `sum(axis=..)`?

**Comment by tqchen** [comment]
It would be great if we can refactor sum with the axis support. But since this PR is an improvement of existing API. We can merge it in for now after verifying its correctness.

**Comment by tqchen** [comment]
merge this in for now, @sxjscience you are more than welcomed to contribute a better version like sum(axis=..)

**Pull request merged**
