### PR TITLE
[Scala] add Profiler support

### PR DESCRIPTION
**Pull request by Ldpe2G**
follows: #3163

### CODE REVIEW

**Comment by piiswrong** [comment]
any updates/review?
@javelinjs

**Comment by javelinjs** [comment]
I'll review

**Comment by javelinjs** [comment]
LGTM, please update the branch.

**Comment by Ldpe2G** [comment]
I will update this pr before this weekend.

**Comment by javelinjs** [comment]
@piiswrong Any idea why test failed?

**Comment by Ldpe2G** [comment]
@javelinjs @piiswrong  finally pass the test

**Comment by piiswrong** [comment]
Jenkins server is offline. Tests are skipped...
Please make sure this is really working

Yizhi Liu <notifications@github.com>于2017年2月16日 周四上午7:21写道：

**Comment by javelinjs** [comment]
@Ldpe2G Could you make sure it works?

**Comment by javelinjs** [comment]
It builds on my mac.

**Comment by Ldpe2G** [comment]
I can successfully run the profiler examples on my ubuntu.

**Pull request merged**
