### PR TITLE
Jens Piontkowski patch 1

### PR DESCRIPTION
**Pull request by JensPiontkowski**
Hello, I had problems installing mxnet for R under Ubuntu, due to missing dependancy in the devtools packages of R. Here is a fix.

Best regards, Jens

### CODE REVIEW

**Comment by piiswrong** [comment]
@thirdwing

**Comment by thirdwing** [comment]
Hi, @JensPiontkowski 

This is something I assume everyone already knows. But it's better to add them into docs.

Can you combine them into one commit by following https://github.com/dmlc/mxnet/blob/master/doc/contribute.md#how-to-combine-multiple-commits-into-one ?

**Comment by JensPiontkowski** [comment]
I think, it is a lot easier if you just copy the lines into the document.

**Comment by antinucleon** [comment]
Close for long time idle.

**Pull request closed without merging**
