### PR TITLE
MKL specific CNN symbol and benchmark for better perf.

### PR DESCRIPTION
**Pull request by zhenlinluo**
@mli  @piiswrong , due to MKL does not support default INCLUDE_PADDING in pooling layer, existing CNN symbol and benchmark will call default mshadow pooling layer for CPU scoring. To get best MKL performance for benchmark, temporarily add symbol to add "pooling_convention=full" to utilize MKL pooling.

### CODE REVIEW

**Comment by piiswrong** [comment]
This isn't a sustainable solution. Too complicated. When do you think the support would come out?

**Comment by piiswrong** [comment]
BTW, could you move the mklbuffers to graph_executor?

**Comment by glingyan** [comment]
@piiswrong what I am trying to implement of mkl-dnn
what I am try to do is that
1. if input data is image data, mkl will allocate a operator buffer inside operator , transfrom image data to operator buffer, but write a private buffer to the output buffer inside NDArray , save some memory description in NDarray.
2. if the input data is NDArray , mkl will operator will try to use it
3. so the objective is that mkl will not store extra buffer in NDarray, only some memory description, and allocate buffer is use mxnet allocator

**Comment by piiswrong** [comment]
Why not use the previous graph executor solution?

**Comment by glingyan** [comment]
Could you help me to find someone on this case
This is the case that could not cover, it is only for "fwd_filter_data   @ MKLConvolutionOp"
  MXImperativeInvoke is call directly from c_api
int MXImperativeInvoke(AtomicSymbolCreator creator,
                       int num_inputs,
                       NDArrayHandle *inputs,
                       int *num_outputs,
                       NDArrayHandle **outputs,
                       int num_params,
                       const char **param_keys,
                       const char **param_vals)

libmxnet.dll!mxnet::MKLMemoryDescriptorBase<float>::convert_from_prv(void * cpu_ptr) Line 110        C++
              libmxnet.dll!mxnet::MKLMemHolder::check_and_prv_to_cpu(void * dptr_) Line 102               C++
    libmxnet.dll!mxnet::TBlob::FlatTo2D<mshadow::cpu,float>(mshadow::Stream<mshadow::cpu> * stream) Line 159            C++
              libmxnet.dll!mxnet::op::SGDMomUpdate<mshadow::cpu>(const nnvm::NodeAttrs & attrs, const mxnet::OpContext & ctx, const std::vector<mxnet::TBlob,std::allocator<mxnet::TBlob> > & inputs, const std::vector<enum mxnet::OpReqType,std::allocator<enum mxnet::OpReqType> > & req, const std::vector<mxnet::TBlob,std::allocator<mxnet::TBlob> > & outputs) Line 89           C++
              [External Code]
>             libmxnet.dll!MXImperativeInvoke::__l135::<lambda>(mxnet::RunContext rctx, mxnet::engine::CallbackOnComplete on_complete) Line 216          C++
              [External Code]
              libmxnet.dll!mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext run_ctx, mxnet::engine::OprBlock * opr_block) Line 327    C++
libmxnet.dll!mxnet::engine::ThreadedEnginePerDevice::CPUWorker<0>(mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<0> * block) Line 181               C++
libmxnet.dll!mxnet::engine::ThreadedEnginePerDevice::PushToExecute::__l18::mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<0> * <lambda>(void)::__l2::<lambda>() Line 77           C++
              [External Code]
              libmxnet.dll!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92 C++
              libmxnet.dll!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115        C++

**Comment by piiswrong** [comment]
mkl doesn't need to cover this as Convolution and other nn symbols are very rarely called imperatively.

**Comment by glingyan** [comment]
But it will affect the result of test/python/train/test_conv.py, lower the accuracy
That is very strange

**Comment by piiswrong** [comment]
could you insert a logging line in mximperativeinvoke and run test con to
see if it's called with convolution op?
glingyan <notifications@github.com>于2017年1月10日 周二下午11:42写道：

**Comment by glingyan** [comment]
Will do , found previous patch on nnvm have problem now ,need to be fixed

**Comment by glingyan** [comment]
image
MXImperativeInvoke call stack from python

**Comment by piiswrong** [comment]
This is calling _zeros. Not mkl ops.

**Comment by glingyan** [comment]
image
MXImperativeInvoke will call SGDMomUpdate to get grad update

**Comment by piiswrong** [comment]
Yes. But I won't call the MKL ops. So no need to put mkl buffers there

**Comment by glingyan** [comment]
image
SGDMomUpdate  need to get weight from operator , but since MXImperativeInvoke  is call from python, I need to find some place to put private MKL to TBLOB , otherwise , it will get 0 data
convert priv => usr   @fwd_filter_data   @ MKLConvolutionOp_1
convert priv => usr   @fwd_top_data      @ MKLPoolingOp_2
**convert priv => usr   @bwdf_filter_diff  @ MKLConvolutionOp_2
convert priv => usr   @bwdf_filter_diff  @ MKLConvolutionOp_1**
convert priv => usr   @fwd_filter_data   @ MKLConvolutionOp_2
convert priv => usr   @fwd_top_data      @ MKLPoolingOp_2
convert priv => usr   @bwd_top_diff      @ MKLPoolingOp_2

**Comment by piiswrong** [comment]
you can always convert to mxnet buffer if the blob is an output

**Comment by glingyan** [comment]
yes, this is 2nd choice, I will understand the whole flow and do it these days

**Comment by glingyan** [comment]
Option 1 , move to Executor could not be done because arg_param is create from python

a.	For weight & aux parameters
1.	FeedForward _init_params, model.py:513
Init ndarray for arg_params
=> arg_params = {k : nd.zeros(s) for k, s in param_name_shapes}
=>  <type 'list'>: ['conv1_weight', 'conv1_bias', 'bn1_gamma', 'bn1_beta', 'conv2_weight', 'conv2_bias', 'bn2_gamma', 'bn2_beta', 'fc2_weight', 'fc2_bias']
Init ndarray for aux_params
=> aux_params = {k : nd.zeros(s) for k, s in zip(aux_names, aux_shapes)}
=> <type 'list'>: ['bn1_moving_mean', 'bn1_moving_var', 'bn2_moving_mean', 'bn2_moving_var']
2.	_bind_exec, executor_manager.py:154 （duplicate allocate）
arg_arrays: arg_arr = nd.zeros(arg_shape[i], ctx, dtype=arg_types[i])
aux_arrays: aux_arrays = [nd.zeros(s, ctx, dtype=t) for s, t in zip(aux_shape, aux_types)]
3.	sym.bind(python) MXExecutorBindEX(C++)
assign to data_entry_
data_entry_[idx.entry_id(nid, 0)] = in_args[arg_top];
 
4.	assign to ForwardOpExecutor’s in_array
    for (const auto& e : inode.inputs) {
      exec->in_array.push_back(data_entry_[idx.entry_id(e)]);
    }
 
5.	ForwardOpExecutor=> setup
Assign in_data_ according to in_array
 
6.	ForwardOpExecutor=> run
op_->Forward(op_ctx, in_data_, req, out_data_, aux_data_)
 
b.	For output
1.	GraphExecutor::InitDataEntryMemory
Get NDarray from pool
    	    const NDArray& src = data_pool_.at(storage_id);
    data_entry_[i] = src.AsArray(vshape[i], vdtype[i]);

**Comment by glingyan** [comment]
[TBlob create stack for operator.docx](https://github.com/dmlc/mxnet/files/729636/TBlob.create.stack.for.operator.docx)

**Comment by piiswrong** [comment]
You don't have to attach mklblob to ndarray to only copy when .asnumpy() is called. You can keep mklblobs internal to executor and always copy to ndarray buffer for outputs and gradients

**Comment by piiswrong** [comment]
Here is a solution:
Register IsMKLMem attribute to mkl dnn ops. then insert an op to copy data from mkl buffer to tblob whenever passing data from mkl dnn ops to non-mkldnn ops

**Pull request closed without merging**
