### PR TITLE
[RFC] Exactly calculate nstep from workspace. Take 2

### PR DESCRIPTION
**Pull request by vchuravy**
Also applies the changes in #852 to deconvolution.

@antinucleon

### CODE REVIEW

**Comment by antinucleon** [comment]
There is a potential issue with CuDNN: https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_convolution-inl.h#L209

I suggest to remove auto select.

**Comment by piiswrong** [comment]
@antinucleon Which issue? I changed the algorithm preference from PREFER_FASTED to WORKSPACE_LIMIT and I think I works fine now.

**Comment by antinucleon** [comment]
@piiswrong I mean in this PR, it enable the workspace to be 0, and this will cause some problem when running with CuDNN, so I suggest to remove the auto select code in this PR.

**Comment by piiswrong** [comment]
I see.

**Comment by vchuravy** [comment]
removed workspace=0

**Pull request merged**
