### PR TITLE
[doc] add visual studio build instruction

### PR DESCRIPTION
**Pull request by happynear**

### CODE REVIEW

**Comment by happynear** [comment]
I have did my best to make the mxnet compatible with original VS2013, but I failed. Too many unsupported features I came across. VS2015 may provide a better support, but it can't work together with CUDA.
 
As far as I know, the only solution is to patch the VS2013 using Nov 2013 CTP and let CUDA mistake it as official VS2013 compiler.

**Comment by antinucleon** [comment]
Several comment: 
1. Could you remove Baidu Yun stuff? It is bad to point to 3rd binary(such as XcodeGhost)
2, Maybe we can consider to use VS Community instead of 2013

**Comment by tqchen** [comment]
@happynear  I think we should host thirdparty libraries. But let us fully consider the license issues. It would be really nice if we can enable user to compile these(or give user instruction to doing so) as well. 

On hosting the compiled binaries, maybe we can consider using github's release service, which allows attachment of binaries files.

**Comment by happynear** [comment]
@antinucleon ,
1. In the mainland of China, OneDrive and Dropbox are unstable and slow. Actually, this archive is also a compiler. Someone has reported the Nov 2013 CTP patch cannot be installed successfully, so I packed the files on my computer and uploaded. I will learn how to use github's release service and upload it. Maybe I should also provide the MD5 of the zip file.

2. VS Community do not support any version of CUDA at present.

@tqchen ,
I think the three third-party libraries (binary version) are not difficult to install. The links are all their official sites. The only works for users to do are downloading and installing / extacting them.

**Comment by antinucleon** [comment]
@happynear 

1. Frome NVIDIA page, VS 2013 community is able to support CUDA:
http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-microsoft-windows/#axzz3oDd9ZhPG

2. I know wtf network situation in mainland China, but I think it is something ppl inside of GFW are able to handle and we can avoid risk of potential virus or copyright by not providing any binary file links,

**Comment by tqchen** [comment]
@happynear Let us doing the following thing

- Can you update the instruction to use the official download links to these binary libraries. So this is the "official" solution for most users.
- We can include a convenient version (mark it non-official) to avoid copyright issues, on github release. 

Thanks!

**Comment by tqchen** [comment]
I think we are fine with not using community version for now

**Comment by tqchen** [comment]
I know it is extreme important to be able to easy installing on all platforms. In the future, I think we are also happy to release binary build of mxnet itself so user don't have to install the build tool-chain on github release.
 @happynear please let me know if you are interested in this

**Comment by happynear** [comment]
Yes, I am glad to contribute my effort to mxnet. I am making standalone third-party package now.

**Comment by tqchen** [comment]
Thanks! Your contribution is very valuable!

**Comment by tqchen** [comment]
@happynear Please let us know when you have any updates

**Comment by pluskid** [comment]
+1 for "official" instructions that avoid any possible licensing and other potential issues, especially since recent news about lots of Chinese developers suffering from a hacked xcode downloaded from some 3rd party file sharing services (e.g. [this news report](http://www.wired.com/2015/09/hack-brief-malware-sneaks-chinese-ios-app-store/)).

**Comment by happynear** [comment]
@pluskid 
I have heard about the news. The zip archive I uploaded to BaiduYun is precisely a compiler. 

But how can I provide the VS 2013 patch from an "official" way? The official installation package cannot be installed successfully on someone's PC.

**Comment by tqchen** [comment]
@happynear Let us simply provide the official link first. We can also suggest higher version of compiler, which might work or someone

**Comment by happynear** [comment]
@tqchen , to avoid lisence issues. I removed the zip archive links from build.md. Maybe a personal guidance in an issue is a better solution.

I will provide links to the vs2013 compiler patch and third-party libraries in https://github.com/dmlc/mxnet/issues/250 , individually.

**Comment by pluskid** [comment]
@happynear I apologize if my comments offend you. I did not mean anything against you. I just want to point out potential issues. This kind of licensing related issues could, for example, result in a [dmca takedown](https://github.com/github/dmca) of the whole repo in a worst case. But I do think what you do is very useful in practice for all windows users.

**Comment by happynear** [comment]
@pluskid , your warning is very instructive. I have removed the links that may cause lisence problems, and provided some "personal" suggestions in https://github.com/dmlc/mxnet/issues/250 . 

I indeedly always ignore the lisence and pirate problems. I just want to bring convience to the users, because many of them would give up when they were facing even a small error.

**Comment by antinucleon** [comment]
For Windows, I do think provide prebuilt official setup.exe is feasible.

**Comment by happynear** [comment]
@antinucleon , I agree. I can provide the compiled `mxnet.dll` and all third-party libraries.

I haven't learned how to make a setup.exe. I will learn to do so.

**Comment by tqchen** [comment]
I guess a precompiled dll is enough for us to make the pip pkgs and r pkgs.
we don't need a setup exe . But precompiled dll is indeed helpful:) I guess
user can download the opencv and openblas dll easily. There might be some
concern on shipping CUDNN as far as I know. We may have to ask user to
install it by them selfs

**Comment by tqchen** [comment]
Thanks @happynear For the contribution! I merged this in now. It would be great if you can help to provide a pre-compiled ```mxnet.dll```, which I think we can ship as long as do not include thirdparty libs officially

**Comment by happynear** [comment]
The pre-compiled `mxnet.dll` and `im2rec.exe` have been uploaded to http://1drv.ms/1G9ktuz . 
I will keep update this file, perhaps per week.

**Comment by pluskid** [comment]
Great! Thanks!

With the pre-compiled dll, maybe we could also easily setup a Windows CI testing hook with [Appveyor](http://www.appveyor.com).

**Pull request merged**
