### PR TITLE
add contrib package

### PR DESCRIPTION
**Pull request by piiswrong**
@precedenceguo @zhreshold 
Moved extra operators to contrib. Had to fix lint, please check if I made any error.
BTW do you have unittests for these ops?

### CODE REVIEW

**Comment by mli** [comment]
if i understand correctly, we put ops in contrib if they are new and not well tested. once they are mature, we will consider to move them into core. 

then do we really want to have `contrib` in `mx.sym.contrib.xxx`? if we move the ops, 
then users need to update their codes.

**Comment by piiswrong** [comment]
contrib is for things that we don't give backward compatibility promise. When ops move to core interface/behavior may change

**Comment by zhreshold** [comment]
Does it mean all contrib ops are enabled by default? 
I agree that some ops that are specific to certain tasks should be put somewhere else, but do you have a rule that what should be in and what should not? @piiswrong 
BTW, I don't think backward compatibility is a big issue for those Ops metioned.

**Comment by piiswrong** [comment]
It's basically a namespace that indicates limited guarantees. volatile interface/behavior, untested, etc

**Comment by precedenceguo** [comment]
I think it is better not to include them by default. Perhaps we can have a ENABLE_CONTRIB Makefile config to skip them and their docs to prevent other people seeing these operators without examples. It could be confusing.

**Comment by piiswrong** [comment]
We can probably add an option to disable it in the future when compile time is too long. For now keeping them in contrib is fine.

**Comment by fullfanta** [comment]
@piiswrong 

please fix the bug on faster-rcnn example.

At setup.py in python, packages contain 'mxnet.contrib'.

But at faster-rcnn example(https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/symbol/symbol_vgg.py), it uses **mx.symbol.contrib.Proposal** rather than **mx.contrib.symbol.Proposal**.

**Pull request merged**
