### PR TITLE
[Doc]Add MXNET_BACKWARD_DO_MIRROR in MXNet environment description

### PR DESCRIPTION
**Pull request by tornadomeet**

### CODE REVIEW

**Comment by piiswrong** [comment]
MXNET_BACKWARD_DO_MIRROR is different from memmonger. memmonger needs to be called separately with dmlc/memmongar

**Comment by tornadomeet** [comment]
@piiswrong  so there is no relation between `MXNET_BACKWARD_DO_MIRROR` and `memonger`? in my understand, `MXNET_BACKWARD_DO_MIRROR` will do mirror  on backward for most common op, but `memonger` is more heuristic, and we should set mirror by hand. right? if it is, i will change the doc on this view.

**Comment by piiswrong** [comment]
memonger is like an extension of mirror. 
mirror saves 30%-50% of memory at 95% speed
memmonger saves O(sqrt(N)) memory at 75% speed

**Comment by tornadomeet** [comment]
@piiswrong thanks, had fixed it.

**Comment by mcxkarakoc** [comment]
.

**Pull request merged**
