### PR TITLE
executor and optimizer bug fix.

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by piiswrong** [comment]
@tqchen @antinucleon

**Comment by tqchen** [comment]
@piiswrong any update on this PR? consider squash and merge, or abandon this

**Comment by piiswrong** [comment]
@tqchen Could you have a quick look? I'll merge afterwards.

**Comment by mli** [comment]
Can one of the admins verify this patch?

**Comment by tqchen** [comment]
Some comments, this PR seems contains three different component
- What does eval_iter mean? seems this is an additional args introduced.
- The pickable for ccsgd looks good, however, would be great we can have a general solution for pickle all possible implementation of optimizer, maybe can be done through the way we store node parameters as dict
-  imdecode function, I am not quite sure why this need to be in here, instead of using imdecode from opencv python then convert to ndarray, in worst case, let us make this a part of plugin.

**Comment by piiswrong** [comment]
eval_iter limit the number of evaluation batches to run. I'll add doc.

opencv doesn't release GIL so no multi threaded decoding. And even with single thread, this is 2-5x faster than cv2.imdecode.

**Comment by tqchen** [comment]
I see, I feel eval_iter should not be in the API, as it opens a deep wound. Another simpler way is simply wrap a data iter to only return first k items. Something like

eval_data=mx.io.LimitFirstKItems(mydata, k=10),


@piiswrong Can we add the imdecode as a plugin?

**Comment by piiswrong** [comment]
I think ndarray.imdecode should be the default way of decoding images. I'm planning to add it to recordio.unpack

**Comment by tqchen** [comment]
Let us at least put imencode in a separate file, and try to minimumly add in python side. While this can be an offical part of the package, it is great if this can be isolated as a plugin module(that will be included by default) to make the code less coupled

**Comment by piiswrong** [comment]
Python side wrapper is necessary because ndarray function interface only support float arguments and doesn't have default arguments.
Plus putting the code somewhere else is going to make it even harder to find where things are defined.

**Pull request merged**
