### PR TITLE
Added comments for getting data and set default data/model path

### PR DESCRIPTION
**Pull request by jamesliu**
Added additional comments for getting data and set the default data path and model path in order to avoid assertion error when running the example without a clue.

Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at ml.dmlc.mxnetexamples.rnn.TrainCharRnn$.main(TrainCharRnn.scala:40)
	at ml.dmlc.mxnetexamples.rnn.TrainCharRnn.main(TrainCharRnn.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

### CODE REVIEW

**Comment by jamesliu** [comment]
@Ldpe2G, may you take a look?

**Comment by Ldpe2G** [comment]
@jamesliu did you run this example with examples/scripts/rnn/run_train_charrnn.sh ?

**Comment by jamesliu** [comment]
@Ldpe2G 
Thanks for replying and let me know there is a script in another directory. 

I run it through IDE directly in examples/src/main/scala/ml/dmlc/mxnetexamples/rnn/TrainCharRnn.scala so I got the error.

After reading https://github.com/dmlc/mxnet/blob/master/example/rnn/char-rnn.ipynb, I know I have to load data and set the right data and model path.

I added comments in the code regarding how to get demo data and set default value for data/model path and hopefully to make it easier to run it directly.

**Comment by Ldpe2G** [comment]
ok, please update the branch 
@javelinjs

**Pull request merged**
