### PR TITLE
Remove for loop in roi pooling operator #4752

### PR DESCRIPTION
**Pull request by jyotilakra92**
Remove the unnecessary for loop.

### CODE REVIEW

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
The change is wrong. If you pool a (1000, 1000) map into (10, 10) and phstart is 0, then ph_end is 100.

Additionally, I propose to move ROIPooling into example/rcnn/operator in order to remove a strange operator for users who have nothing to do with object detection.

**Comment by Godricly** [comment]
@precedenceguo I think using Dtype [here](https://github.com/dmlc/mxnet/blob/master/src/operator/roi_pooling.cu#L164-L173) is not safe. Since we are computing the logic here, not the feature map.
```
      Dtype bin_size_h = static_cast<Dtype>(roi_height)
                         / static_cast<Dtype>(pooled_height);
      Dtype bin_size_w = static_cast<Dtype>(roi_width)
                         / static_cast<Dtype>(pooled_width);

      int phstart = floor(static_cast<Dtype>(h - roi_start_h) / bin_size_h);
      int phend = ceil(static_cast<Dtype>(h - roi_start_h + 1) / bin_size_h);
      int pwstart = floor(static_cast<Dtype>(w - roi_start_w) / bin_size_w);
      int pwend = ceil(static_cast<Dtype>(w - roi_start_w + 1) / bin_size_w);
```

**Comment by sxjscience** [comment]
I feel the DType to be okay since we will cast them to int using floor and ceil. Also, the for loops can not be removed.

**Comment by Godricly** [comment]
It actually depends on the type ur using before casting to int. if the size of feature nao is small, it's ok. But for larger ones, you might overflow.

**Comment by sxjscience** [comment]
@Godricly In that case, we may consider revising it to 
```c++
int phstart = floor(static_cast<Dtype>((h - roi_start_h) * pooled_height) / static_cast<Dtype>(roi_height));
```

**Comment by sxjscience** [comment]
@jyotilakra92 @starimpact There is one way to eliminate the for-loop. We can consider using `AtomicAdd` to accumulate the output gradient to the chosen indices. Like to use ```AtomicAdd(&g[chosen_ind], out_grad[ind])```. This will accelerate the speed of the backward computation.

**Pull request closed without merging**
