### PR TITLE
DType dropout

### PR DESCRIPTION
**Pull request by Godricly**
Supporting DType dropout using real_t rng with type cast.

### CODE REVIEW

**Comment by Godricly** [comment]
The [travis](https://travis-ci.org/Godricly/mxnet/builds/144908964) was passed for myself. :disappointed:

**Comment by piiswrong** [comment]
It segfaults sometimes, you just have to restart it

**Comment by Godricly** [comment]
The testing dot failed in the OS X python_test.

**Comment by piiswrong** [comment]
it randomly fails. @sxjscience Could you fix it?

**Comment by Godricly** [comment]
Can you guys check my note In #2585? I think that InferShape maybe not act as expected.
@piiswrong @sxjscience

**Comment by sxjscience** [comment]
@Godricly I've checked and it's a bug. We need to save the parameters as `int`.

**Pull request closed without merging**
