### PR TITLE
[Doc] Enable the new docs at readthedocs build

### PR DESCRIPTION
**Pull request by tqchen**
Guidelines:
- Always use .md suffix, avoid use "./myfile.md" instead use "myfile.md" instead.
- Always add space between Parameter and Return sections in numpydocs.

The doc can be previewed at http://mxnet-tqchen.readthedocs.org/en/latest/

We can switch the default trigger over after this PR is merged. However, we do need to fix the links to the docs from main repo

### CODE REVIEW

**Comment by pluskid** [comment]
Great! Is there anyway to add those autodocs to the table of contents?

**Comment by tqchen** [comment]
Actually this was quite tricky.. I do not yet know a way to do so..

**Comment by tqchen** [comment]
@pluskid I looked into automatically generate toc for the methods before but was not successful. Maybe some advanced hack was needed to get the list of the generated docs and add them to the tree

**Comment by pluskid** [comment]
@tqchen Does this [autosummary](http://www.sphinx-doc.org/en/stable/ext/autosummary.html#directive-autosummary) command work for our case?

**Comment by tqchen** [comment]
I remembered I tried autosummary before and find it does not serve the purpose. But you can try it locally  by simply creating a new doc folder and see if it works

**Comment by tqchen** [comment]
Specifically, autosummary still need you to enumerate the things to summarize in the argument, instead of doing it automatically

**Comment by pluskid** [comment]
Oh, I see. I think a simple javascript hook could do the job. I will look into that.

**Pull request merged**
