### PR TITLE
add mshadow lint

### PR DESCRIPTION
**Pull request by yajiedesign**
add missing code group
depend on https://github.com/dmlc/mshadow/pull/238 and https://github.com/dmlc/dmlc-core/pull/244

### CODE REVIEW

**Comment by piiswrong** [comment]
can we do a traversal and include every thing?

**Comment by yajiedesign** [comment]
i will try

**Comment by yajiedesign** [comment]
@piiswrong dll dep is merged

**Comment by piiswrong** [comment]
You need to replace all occurrences of MX_TREAD_LOCAL with MX_THREAD_LOCAL

**Comment by yajiedesign** [comment]
@piiswrong ok. field

**Pull request merged**
