### PR TITLE
fix l2_normalization shape bug

### PR DESCRIPTION
**Pull request by ZhreShold**
Found a bug when using L2Normalizatino layer. Shape inconsistent.
Dig into the code and found the original code tried to "FlatTo2D" which collapse the higher dimensions first.
If I didn't get it wrong, we should keep the first dimension which is the batch number, and fold the lower dimensions all together.

### CODE REVIEW

**Comment by piiswrong** [comment]
@winstywang

**Comment by winstywang** [comment]
@piiswrong I remember that we have already fixed the behavior of FlatTo2D. It should maintain the first dim unchanged, right? 

For 4-dim data, it depends on the application. We may need normalize across channel in some cases, while normalize within channel but across feature map in other cases. So it is better to have a choice on that. @ZhreShold

**Comment by piiswrong** [comment]
flatto2d's behavior hasn't been changed. A lot of existing code depends on it

**Comment by ZhreShold** [comment]
So what do you guys recommend to do right now? I've double checked the behaviour of FlatTo2D hasn't been changed as @piiswrong has mentioned.  

If the intended operation is ambiguous, how about using two parameters, "across_channel" and "across_spatial", and perform normalization accordingly?

**Comment by pluskid** [comment]
The behavior of `FlatTo2D` has not changed for backward compatibility, we used `get_with_shape` and `ProdShape` instead, for [example](https://github.com/dmlc/mxnet/blob/master/src/operator/fully_connected-inl.h#L75).

**Comment by piiswrong** [comment]
@ZhreShold Yes a switch would be good. Lets use channel/instance to be consistent with softmaxActivation

**Pull request closed without merging**
