### PR TITLE
[WIP] Proposal: Extend imdecode to uint16

### PR DESCRIPTION
**Pull request by jmerkow**
I am working with image data that does not fit well into uint8.  Given that I am working with 100k-1M images, I need a data iterator that is fast, such as the ImageIter.  I have been looking into extending the ImageIter to use other types besides uint8 for reading data.  It appears that after the initial read, there is no problem with container type.
I've tried writing a new iter in python (using python reads), and they are still slow.

So I've turned my attention to extending mxnet's imdecode function to work with uint16 in addition to uint8. This PR is a sketch, if there is interest I will continue.

There are a number of issues remaining, just as [mshadow has no uint16 type](https://github.com/dmlc/mshadow/blob/a9d70f06b791f42277ccd76a50d571495de9ca66/mshadow/base.h#L264-L270) (to replace `mshadow::kUint8`).

I am open to comments on my approach. An alternative would be to allow I/O from CV mat files, which can store any format.

### CODE REVIEW

**Comment by piiswrong** [comment]
How about add a dtype parameter to allow uint8, int32, and float32?
I don't there there would be much difference speed wise between int16 and int32.
Also since you are going to convert it to float later anyway, why not directly convert to float in imdecode

**Comment by jmerkow** [comment]
The idea behind `uint16` is that they can be stored in tifs which I know opencv can read, I am not sure about int32 and imdecode. 
In the end, what image formats should this thing read?

We could make a new templated version of mxnet::io::Imdecode, then the orginal (and exposed) mxnet::io::Imdecode contain a have a switch, which choses the correct templated function based on the dtype param.

So you are suggesting that we drop mshadow::kUint8 and replace with mshadow::float16? I have not looked in depth at mxnet and mshadow, but I assume most processing is done on singles (float16).

**Comment by piiswrong** [comment]
yes something like mx.io.imdecode(..., dtype='float32') should work.
We don't need to make imdecode templated. We only need to do a conversion at the end with MSHADOW_DTYPE_SWITCH like the other ops.

**Comment by jmerkow** [comment]
I went back and re-read the opencv docs on imencode and imdecode.  opencv only supports uint8 and uint16 formats for all image encoding and decoding.  If we wanted an alternative image io format, one that can use a larger variety of dtypes, it think we need to look outside opencv.

* NDArrays load very fast, but the files are quite large (unsure if there is a way to change this), and does not offer compression?
* Pillow supports a [lot of formats ](http://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html), but it is python only, and I would want to test what formats+dtypes it can actually save/read.  Given that imagerecio can be handled mostly in python now, python only might not be a problem (for the python platform).

I would want the final result of all this is fast i/o such as those offered by RecordIO.

**Comment by piiswrong** [comment]
I doesn't matter what format cudnn supports. You can use opencv to decode into a temporary buffer of whatever type and convert it to the target output format mxnet supports

**Comment by jmerkow** [comment]
Im saying, that if you want to save/read dtypes that are not uint8 or uint16, you cannot use opencv for img encoding or decoding.

**Comment by piiswrong** [comment]
Can one of the admins verify this patch?

**Comment by piiswrong** [comment]
We only support images that opencv can read.

**Comment by jmerkow** [comment]
Ok. Let's close this. The effort is not worth the one uncommon new format.  I now use a simpler approach to pack images with other dtypes.

**Pull request closed without merging**
