### PR TITLE
Improved caffe converter

### PR DESCRIPTION
**Pull request by arikpoz**
Extended caffe-to-mxnet converter and improved converter test

- Added support for networks which uses batch normalization without a scale layer following the batch norm, i.e. gamma is fixed to 1
- Extended naming convention used when implementing batch normalization in caffe
- Added support for old caffe versions where dilation didn't exist. This is needed to convert models which depends on old caffe
- Added support for deconvolution layer
- Added support for older version of caffe where kernel_size, pad and stride parameters were not iterable
- Fixed crash happening when a bottom layer doesn't exist in the internal top_to_layers dictionary, this can happen if the name of the input is not 'data'
- Added ignore-by-design support for converting 'Crop' layers
- Fixed batch norm layer comparison to take into account the rescaling factor
- Added careful condition in tester to swap (RGB,BGR) input channels only if they are of size 3 or 4, which is the same check the conversion does
- Allow comparing layers of models with no mean file
- Added support for comparing the parameters of deconvolution layers

### CODE REVIEW

**Comment by piiswrong** [comment]
Please revert the submodule change.

**Comment by arikpoz** [comment]
Done.

**Comment by arikpoz** [comment]
build still fails, @piiswrong can you check the log to see if this is something I can fix?

**Comment by piiswrong** [comment]
Error is due to you changed submodule: https://github.com/dmlc/mxnet/pull/6822/files

**Comment by arikpoz** [comment]
But I reverted this change, or so I thought.
And I think rebase from upstream made it in the first place..
Can you suggest how to fix?

**Comment by piiswrong** [comment]
Try checkout master and cherry pick your changes.

**Comment by arikpoz** [comment]
submodules issue seem resolved.

**Comment by piiswrong** [comment]
Is caffe converter tested? Maybe we should setup CI?

@mli Could you have a look?

**Comment by arikpoz** [comment]
The only error is due to test timeout, can someone check this, maybe update the timeout?

**Comment by mli** [comment]
the caffe converter is tested in the CI, but we only tried to convert a few commonly cnns, such as vgg/resnet. Each test is expensive. 

@arikpoz do you have a better idea how to test the converter?

**Comment by arikpoz** [comment]
The current test seems good to me, checking both performance and layer by layer outputs.

What takes times is the performance test since we run inference on many images.
To save time, we can remove the performance test, and trust that if the layer by layer outputs are close enough, then the end performance should be the same. 

The layer by layer test is done on a single image comparing all the outputs (and network parameters) of the caffe network and the mxnet network. Since we run inference on one image only, it is very fast to execute.

my 2c.

**Pull request merged**
