### PR TITLE
Revert "Revert "contrib fft,ifft,countsketch""

### PR DESCRIPTION
**Pull request by piiswrong**
Reverts dmlc/mxnet#5634

@shiyangdaisy23 @cjolivier01 Looks like this still gives cufft error on windows

### CODE REVIEW

**Comment by shiyangdaisy23** [comment]
@cjolivier01 I searched for possible solution: what you are probably missing is the cufft.lib in your linker input. (in VS: Project Properties->Linker->Input->Additional Dependencies

**Comment by sxjscience** [comment]
@shiyangdaisy23 Have cufft been included in CMake?

**Comment by sxjscience** [comment]
@shiyangdaisy23 I find that in the cmake the cufft library has been added like this https://github.com/dmlc/mxnet/blob/master/CMakeLists.txt#L355-L358. This will generate paths like `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64\nvrtc.lib\..\cuda.lib` and `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64\nvrtc.lib\..\cufft.lib`. I feel that we can change it to be
```cmake
FIND_LIBRARY(CUDA_nvrtc_LIBRARY nvrtc "${CUDA_TOOLKIT_ROOT_DIR}/lib/x64" "${CUDA_TOOLKIT_ROOT_DIR}/lib/win32")
FIND_LIBRARY(CUDA_cuda_LIBRARY cuda "${CUDA_TOOLKIT_ROOT_DIR}/lib/x64" "${CUDA_TOOLKIT_ROOT_DIR}/lib/win32")
FIND_LIBRARY(CUDA_cufft_LIBRARY cufft "${CUDA_TOOLKIT_ROOT_DIR}/lib/x64" "${CUDA_TOOLKIT_ROOT_DIR}/lib/win32")
list(APPEND mxnet_LINKER_LIBS ${CUDA_nvrtc_LIBRARY})
list(APPEND mxnet_LINKER_LIBS ${CUDA_cuda_LIBRARY})
list(APPEND mxnet_LINKER_LIBS ${CUDA_cufft_LIBRARY})
```
Also, I haven't tested the code so I'm not sure if it will solve the problem. Could you test it on a window machine? If not, I can spend some time testing it.

**Comment by shiyangdaisy23** [comment]
@sxjscience I don't have a windows machine. That would be very nice if you can test it. There was errors saying:  cuda_compile_1_generated_fft.cu.obj : error LNK2019: unresolved external symbol cufftPlanMany referenced in function..........

**Comment by cjolivier01** [comment]
I believe that I fixed it already for the Windows build

**Comment by cjolivier01** [comment]
I think that I have fixed it -- please update your branch and try the build again.

**Pull request merged**
