### PR TITLE
make caffe converter tool available without caffe installation

### PR DESCRIPTION
**Pull request by dongguosheng**
according to https://github.com/kitofans/caffe-theano-conversion, from #597

### CODE REVIEW

**Comment by winstywang** [comment]
Hi. thanks for the PR. Could you please update the README as well?

**Comment by mli** [comment]
great PR, thanks!

beside naiyan's comment, could you please acknowledge that we used caffe's .proto in tools/cafe_converter/readme.md. also do we still need google protobuf? if yes, we probably remove the auto generated pb.py file and provide a makefile to generate it instead. since the file varies for different protobuf version.

**Comment by dongguosheng** [comment]
readme updated.
the proto file was removed and readme shows how pb.py was generated.

**Comment by mli** [comment]
LGTM, thanks

**Comment by mli** [comment]
@dongguosheng my apologies that i didn't check it clearly. 

my question is, does a user needs to install `protobuf` to the codes. in other words, does the `xxx.pb.py` requires `protobuf` to run. If not, then it is fine. But if yes, I suggest to 

- only keeps the .proto file while delete the .pb.py file, since the latter varies for different versions of google protobuf
- add a `makefile` which will compile the .pb.py using the protobuf 
- add a readme to tell the users how to install the google protobuf

**Comment by piiswrong** [comment]
Also add an option to turn it off so we don't have to depend on protobuf

**Comment by dongguosheng** [comment]
@mli i got your idea :)
```protobuf``` isn't needed to use this tool, i mean the ```protoc ``` bin and ```protobuf.so.xxx``` aren't needed. 
The ```google protobuf``` python package is definely needed.
```xxx.pb.py``` left to make this tool easier to use. even without ```google protobuf``` python package, ```pip intall``` is simple, maybe i should add ```google protobuf``` python package's version in readme?

**Comment by dongguosheng** [comment]
update in #662

**Comment by tqchen** [comment]
Thanks for the contribution! Have added you to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md Please feel free to update more information about you and contribute more of your wisdom to mxnet!

**Pull request merged**
