### PR TITLE
Half2 implementation

### PR DESCRIPTION
**Pull request by ap-hynninen**

### CODE REVIEW

**Comment by piiswrong** [comment]
Could you update mshadow?

**Comment by eric-haibin-lin** [comment]
The compilation gives a lot of warnings (not errors) at commit 38f7c5584016e92ba1e0ee1b00ea6632740f67ce 

Environment: Deep Learning AMI Ubuntu Linux - 1.3_Apr2017 (ami-638c1e03)

Is this expected?
```
src/operator/tensor/./../mxnet_op.h(210): here
            instantiation of "void mxnet::op::mxnet_op::Kernel<OP, mxnet::gpu>::Launch(mshadow::Stream<mshadow::gpu> *, int, Args...) [with OP=mxnet::op::Sum, Args=<mshadow::half::h
alf2_t *, mxnet::OpReqType, mshadow::half::half2_t *>]"
(75): here
            instantiation of "void mxnet::op::ElementWiseSumCompute_<xpu,DType>(const nnvm::NodeAttrs &, const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxn
et::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu, DType=
mshadow::half::half2_t]"
(104): here
            instantiation of "void mxnet::op::ElementWiseSumComputeWithHalf2<xpu>(const nnvm::NodeAttrs &, const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<m
xnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]"
src/operator/tensor/elemwise_sum.cu(12): here

/home/ubuntu/haibin/mshadow/mshadow/././half2.h(81): warning: calling a __host__ function("mshadow::half::half2_t::operator =") from a __host__ __device__ function("mshadow::half::h
alf2_t::operator +=<mshadow::half::half2_t> ") is not allowed

src/operator/tensor/./elemwise_sum.h(33): warning: calling a __host__ function("mshadow::half::half2_t::operator =") from a __host__ __device__ function("mxnet::op::Sum::Map<mshadow
::half::half2_t, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(28): warning: calling a __host__ function("mshadow::half::operator +") from a __host__ __device__ function("mxnet::op::Sum::sum<mshadow::half::h
alf2_t, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(33): warning: calling a __host__ function("mshadow::half::half2_t::operator =") from a __host__ __device__ function("mxnet::op::Sum::Map<mshadow
::half::half2_t, mshadow::half::half2_t *, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(28): warning: calling a __host__ function("mshadow::half::operator +") from a __host__ __device__ function("mxnet::op::Sum::sum<mshadow::half::h
alf2_t, mshadow::half::half2_t *, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(33): warning: calling a __host__ function("mshadow::half::half2_t::operator =") from a __host__ __device__ function("mxnet::op::Sum::Map<mshadow
::half::half2_t, mshadow::half::half2_t *, mshadow::half::half2_t *, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(28): warning: calling a __host__ function("mshadow::half::operator +") from a __host__ __device__ function("mxnet::op::Sum::sum<mshadow::half::h
alf2_t, mshadow::half::half2_t *, mshadow::half::half2_t *, mshadow::half::half2_t * > ") is not allowed

src/operator/tensor/./elemwise_sum.h(33): warning: calling a __host__ function("mshadow::half::half2_t::operator =") from a __host__ __device__ function("mxnet::op::Sum::Map<mshadow
::half::half2_t  > ") is not allowed
```

**Comment by ap-hynninen** [comment]
I don't see this when I compile on my system. The #ifdef in
https://github.com/dmlc/mshadow/blob/1d633cbf0bf5b13196cfbd95e6666df3c5f4a8a7/mshadow/half2.h#L11
Should insert __device__ into source code. Are some of the conditions of the #ifdef not met?

**Comment by piiswrong** [comment]
MSHADOW_FORCE_INLINE should already have `__device__`. Why do you need to put it again?

**Comment by piiswrong** [comment]
I think you should replace all MSHADOW_HALF2_INLINE with MSHADOW_XINLINE.
Even if cuda_arch is < 530, you still want the functions to be host/device

**Comment by ap-hynninen** [comment]
Fixed in https://github.com/dmlc/mshadow/pull/249

**Comment by piiswrong** [comment]
merged. Please submit pr to update mxnet submodule

**Pull request merged**
