### PR TITLE
Checkpoint optimizer states

### PR DESCRIPTION
**Pull request by zorksylar**
Currently, mxnet only checkpoint the model. In practice, the computation states are not only model but also states of the optimizer. For SGD with momentum enabled, momentum is the state of the SGD optimizer, and it saves something like `history of gradient`. So, when checkpointing, the states of optimizer should be saved as well.

If the optimizer state is not saved, when load a checkpoint and continue training, there will be a sharp decline for both training-accuracy and validation-accuracy.

This PR saves optimizer states when checkpointing.

### CODE REVIEW

**Comment by piiswrong** [comment]
The change in function interface will break many functionalities. New arguments should have a default value, e.g. None.

There are multiple optimizer states for each weight when training with multiple gpus

**Comment by zorksylar** [comment]
Sorry for the late reply. Yes, you're right, in a mutli-gpu setting, the optimizer states are co-located with kvstore.

**Comment by zorksylar** [comment]
Hi @piiswrong, sorry for the late reply. I don't quite understand "multiple optimizer states for each weight". Do you mean "for each weight, there are many optimizer states replicas on each GPU" or "for each weight, there are many kinds of optimizer states".
Because, in the case of using kv-store, the optimizer states are partitioned among multiple GPUs. For a single weight, the optimizer state is not replicated, right? In my implementation, the optimizer states and model are checkpointed within the same file(``'%s-%04d.params' % (prefix, epoch)``, prefix contains kv.rank). I think it is correct. If I missed something, please let me know.

**Comment by zorksylar** [comment]
Solved by #4408

**Pull request closed without merging**
