### PR TITLE
add nnvm cmake with windows

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks, please fix the lint check and I can merge it in https://travis-ci.org/dmlc/mxnet/jobs/158383418

**Comment by tqchen** [comment]
please rebase against the recent nnvm(or start as a clean fork) as there is a force push to bring in master status

**Comment by yajiedesign** [comment]
@tqchen ok i am rebase

**Comment by tqchen** [comment]
great, thanks a lot for the effort!

**Pull request merged**
