### PR TITLE
[Bug]: RNN symbol doesn't work correctly with LSTM mode

### PR DESCRIPTION
**Pull request by sbodenstein**
Currently, forward evaluation is broken for LSTM when "state_outputs" is False. This fixes it.

### CODE REVIEW

**Comment by sbodenstein** [comment]
Currently, forward evaluation is broken for LSTM when "state_outputs" is False. This fixes it.

**Comment by winstywang** [comment]
@pluskid

**Comment by pluskid** [comment]
LGTM

**Comment by winstywang** [comment]
@sbodenstein Please update to latest master and merge

**Pull request merged**
