### PR TITLE
[scala] change proj version

### PR DESCRIPTION
**Pull request by javelinjs**
@piiswrong Could you verify if this version works?

### CODE REVIEW

**Comment by piiswrong** [comment]
we are at 9.5 now...
We need to figure out how to do versioning for different languages.

Either bump all of them at the same time, or each language have a different version system.

**Comment by javelinjs** [comment]
I vote for the first way - bump at the same time.

**Comment by piiswrong** [comment]
Then we need a list of all places. Or better, a script for doing this.

**Comment by sergeykolychev** [comment]
I'd vote for separate versioning scheme, though I try to keep the same major version. For example
currently perl api has version 0.95. But it would be nice to have flexibility release to cpan 0.9501, 02, etc. with incremental updates and bugfixes.

**Comment by piiswrong** [comment]
closed for now

**Comment by javelinjs** [comment]
@piiswrong What if I change the version to 0.9.5 for now?

**Pull request closed without merging**
