### PR TITLE
Expandable toc

### PR DESCRIPTION
**Pull request by kevinthesun**
Build expandable sidebar.

### CODE REVIEW

**Comment by piiswrong** [comment]
@kevinthesun Looks like all the sub titles just disapeared

**Comment by kevinthesun** [comment]
Yes. It's weird since my local branch just works fine.

**Comment by kevinthesun** [comment]
I refreshed the page and it works now. Don't know what the problem is.

**Comment by sandeep-krishnamurthy** [comment]
Surprisingly it is working now. I can see expandable menus. Looks very useful for users reading mxnet docs.

**Comment by andremoeller** [comment]
The sidebars are collapsed by default, which makes it hard to see the topics that the page goes over. I imagine that some users won't even realize that the sidebar is expandable -- I think at least one or two levels should be expanded by default: https://github.com/dmlc/mxnet/issues/3888

**Pull request merged**
