### PR TITLE
Truncate operator implementation

### PR DESCRIPTION
**Pull request by apaleyes**
As proposed in #3201. Tested with unit tests and interactive shell.

### CODE REVIEW

**Comment by piiswrong** [comment]
please follow the signature and doc of numpy
https://docs.scipy.org/doc/numpy/reference/generated/numpy.trunc.html

**Comment by apaleyes** [comment]
Both fixed according to numpy. Somehow I did not immediately realize exact mirror of numpy was the purpose here.

**Comment by piiswrong** [comment]
Please also include this sentence:
The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. In short, the fractional part of the signed number x is discarded.

**Comment by apaleyes** [comment]
Added. I guess we should also consider improving docs for other similar math operators. For example, compare these docs:

http://mxnet.io/api/python/symbol.html#mxnet.symbol.floor
https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor.html#numpy.floor

http://mxnet.io/api/python/symbol.html#mxnet.symbol.ceil
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ceil.html#numpy.ceil

**Comment by piiswrong** [comment]
Sure

**Comment by apaleyes** [comment]
Turned out floor and ceil were the only ones that needed improvement, out of rounding operators at least

**Pull request merged**
