### PR TITLE
add the mnist example in R

### PR DESCRIPTION
**Pull request by ziyeqinghan**
I added the mnist example in R according to https://github.com/dmlc/mxnet/tree/master/example/image-classification. 
I will add other examples in image-classification if it is needed.

### CODE REVIEW

**Comment by thirdwing** [comment]
@ziyeqinghan Can you update this? I will merge it then.

**Comment by ziyeqinghan** [comment]
@thirdwing okay, I will update this soon. :)

PS: May I ask that whether I have an chance to be a candidate of gsoc project for mxnet?

**Comment by Sandy4321** [comment]
Super, may you add examples for short text sentiments analysis
classifications
For rnn, lstm, gru pls

**Comment by ziyeqinghan** [comment]
@Sandy4321 ok, I will try my best to add some examples.

**Comment by Sandy4321** [comment]
Great, when it is possible to expect to see one

**Comment by tqchen** [comment]
@thirdwing what is the status on this PR?

**Comment by thirdwing** [comment]
Personally I want to test it on Windows, but not enough time right now.

**Comment by thirdwing** [comment]
@ziyeqinghan As you said in #1618 , there seem some problems in cifar10.

Can you remove it for now and let's merge the mnist example?

**Comment by ziyeqinghan** [comment]
@thirdwing I have removed the cifar example and moved mnist example to the same folder with python one.

**Pull request merged**
