### PR TITLE
fix deconvolution

### PR DESCRIPTION
**Pull request by tornadomeet**
i'm so sorry did not give the test function of deconvolution since last came , now fill it up.
the test of deconv is based on conv.
ths~

### CODE REVIEW

**Comment by antinucleon** [comment]
Seems test failed?

**Comment by tornadomeet** [comment]
yes, last time it failed in the line of ```assert reldiff(conv_args_grad[1].asnumpy(), deconv_args_grad[1].asnumpy()) < 1e-6```; i run the test_operator.py in my local PC many times and all passed,  the value of reldiff is about 1e-7.  
when i fix the workspace refer to (prevent workspace from being bigger than anticipated)[https://github.com/dmlc/mxnet/commit/0e680e0bd256a2878bbc82a0ba92a7f1c3ad6bb9], the reldiff is perfect and equal zero(it don't  know why);

**Comment by tornadomeet** [comment]
another 2 tips puzzled me in conv and deconv:
1. i think https://github.com/tornadomeet/mxnet/blob/master/src/operator/deconvolution-inl.h#L242 should be changed to ```index_t nstep = std::max(std::min(static_cast<index_t>(workspace_size / (shape_colunit_.Size()+shape_dstunit_ .Size())),ishape[0]), 1U);``` for the workspace is used for "indata" and "outdata";
2. why it must add ```if (nstep_ == nstep) {nstep_ = std::max(nstep_ - 1, 1U); } ```?

**Comment by tornadomeet** [comment]
@antinucleon  could you please take a look at this? ths~

**Comment by antinucleon** [comment]
I will look at it in morning, sorry for the delay.

**Comment by antinucleon** [comment]
For 1. In original conv code, after decide ```nstep```, there is one step to re-calculate space requirement. I checked deconv code, and I think we should fix it.
For 2. I think it seems useless or harmful but not quite sure why it is there. @tqchen Could you review it?

**Comment by antinucleon** [comment]
For 2, could you remove ```if (nstep_ == nstep) {nstep_ = std::max(nstep_ - 1, 1U); }``` and update the PR? Thanks

**Comment by tqchen** [comment]
Thanks for all the updates, will let @antinucleon to track this

**Comment by tornadomeet** [comment]
@tqchen @antinucleon , ok, for the prob 2 deconv here,we let it be consistent with conv first.  
rebase had been done~

**Pull request merged**
