### PR TITLE
backward headgrads and detach

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by sneakerkg** [comment]
Great to see this PR:)

**Comment by piiswrong** [comment]
@sneakerkg @ZihengJiang Added updated_grad flag to indicate whether this gradient has been updated by last backward call.
I'm not sure if updated_grad is a good name. open to suggestions

**Comment by sneakerkg** [comment]
One question, has the change in this PR applied to the nn branch? Or I need to cherry pick into that one?

**Comment by piiswrong** [comment]
you need to rebase

Tianjun Xiao <notifications@github.com>于2017年5月20日 周六上午9:53写道：

**Comment by sneakerkg** [comment]
This PR works on my task. Thanks

**Pull request merged**
