### PR TITLE
Add state support for Custom Operator API functions.

### PR DESCRIPTION
**Pull request by sbodenstein**
@piiswrong: As per discussion in #2051, let me know if this is correct.

This doesn't fix the potential bug in #2180.

### CODE REVIEW

**Comment by vchuravy** [comment]
Looks right to me.

**Comment by piiswrong** [comment]
LGTM. Could you verify that the custom_op example still works and we can merge.

**Comment by sbodenstein** [comment]
I can confirm that running `custom_softmax.py` works perfectly (on GPU) with this commit. 

I have also obviously ensured that my Python is using this commits version of MXNet (I used print statements in the new `operator.py` to confirm).

**Comment by tqchen** [comment]
@piiswrong any updates on this? I hope this can be merged in before we tag 0.7

**Comment by piiswrong** [comment]
This is good to merge. Just need to pass the check

**Pull request merged**
