### PR TITLE
Fix RMSProp update rule

### PR DESCRIPTION
**Pull request by sifmelcara**
When using Alex's version of RMSProp to train a network, I found it sometimes update some network weights to NaN.
After that, I found the RMSProp implementation is a little bit different from [Alex's paper](https://arxiv.org/pdf/1308.0850v5.pdf). In equation 40, the epsilon should be under the square root.

I guess I got `NaN` because `state_n - state_g * state_g` can sometimes be something like `-1e-20` (because of floating point arithmetic error). Indeed, after I applied this patch, it stops update network weights to `NaN`.

### CODE REVIEW

**Comment by piiswrong** [comment]
Could you also modify the non-alex version RMSPropUpdate?

**Comment by piiswrong** [comment]
You need to fix the tests in tests/python/unittests/test_optimizer to

**Comment by sifmelcara** [comment]
Although I do not know how to write Perl, I also updated the test in perl module. (Hope it will pass)

**Comment by sergeykolychev** [comment]
@sifmelcara thank you for updating perl test.

**Pull request merged**
