### PR TITLE
update lstm.py reshape using shape

### PR DESCRIPTION
**Pull request by Godricly**
changing target_shape to shape

### CODE REVIEW

**Comment by sxjscience** [comment]
How about to rebase the code using `git rebase -i dmlc/master`. The commit list is too long.

**Comment by Godricly** [comment]
ah ... sorry for ...I was syncing mine with github tool so its 2 messy. I'll try

**Comment by sxjscience** [comment]
@Godricly For details about how to stash multiple commits, http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit is a good reference.

**Comment by Godricly** [comment]
Fancy approach is efficient. So I delete my old fork. :laughing:

**Pull request closed without merging**
