### PR TITLE
Add predict sample code for lstm+ctc ocr. Also update it's README.md

### PR DESCRIPTION
**Pull request by BobLiu20**
I think a predict sample code for lstm+ctc ocr is very useful. 

Related issue point: [issue](https://github.com/dmlc/mxnet/issues/4169)

### CODE REVIEW

**Comment by piiswrong** [comment]
Thanks. Somehow I missed this. Merged

**Comment by fanlu** [comment]
When I compile make in mxnet/amalgamation
The following error occurred
/workspace/mxnet/amalgamation/../include/mxnet/base.h:15:21: fatal error: nnvm/op.h: 没有那个文件或目录

**Comment by BobLiu20** [comment]
@fanlu  Hi , first of all your compile error has no direct bearing upon the PR.   

I guess you are using a incorrect git clone to get source code. checking this [page](http://mxnet.io/get_started/ubuntu_setup.html).
and take care:

    git clone https://github.com/dmlc/mxnet.git --recursive

do not lost --recursive argument in here.

**Comment by fanlu** [comment]
@BobLiu20 I have used the compiler before --recursive, the latest cod include the nnvm module, but you fork out of the time there is no such this module. This should be inside the issue #4667

**Comment by fanlu** [comment]
@BobLiu20 I forked your branch from [https://github.com/BobLiu20/mxnet](url), and I got an error

plugin/warpctc/./warpctc-inl.h:123:5: error: 'ctcComputeInfo' was not declared in this scope
     ctcComputeInfo info;
     ^
plugin/warpctc/./warpctc-inl.h:125:7: error: 'info' was not declared in this scope
       info.loc = CTC_CPU;
       ^
plugin/warpctc/./warpctc-inl.h:175:61: error: 'info' was not declared in this scope
                                       input_lengths.size(), info,
                                                             ^
Makefile:197: recipe for target 'build/plugin/warpctc/warpctc.o' failed
make: *** [build/plugin/warpctc/warpctc.o] Error 1
make: *** Waiting for unfinished jobs....
can you help me about this problum? thx

**Comment by BobLiu20** [comment]
@fanlu Hi, Regrading to this issue, a solution appear in this [site](https://github.com/dmlc/mxnet/pull/3853).  You can get the reason and solution after review it.

**Comment by fanlu** [comment]
@BobLiu20 It worked, thx

2017-01-19 14:00:13,361 Saved checkpoint to "model-0010.params"
iter
2017-01-19 14:04:21,496 Epoch[9] Validation-Accuracy=0.958906
2017-01-19 14:04:21,505 Saved checkpoint to "ocr-0010.params"

the Validation-Accuracy is 0.958906, but the Inference is almost wrong
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 764, Result: 74454
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 558, Result: 758
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 5117, Result: 7117
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 447, Result: 907
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 708, Result: 708
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 519, Result: 7842
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 416, Result: 7416
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 302, Result: 7302
admin@8f585fd9686f:/export/App/work/data/bob_mxnet/example/warpctc$ python ocr_predict.py
the num is 728, Result: 7428

**Comment by xinghedyc** [comment]
@fanlu @BobLiu20 I think I meet the same problem, the accuracies dose not match between inference and training.

**Comment by lji72** [comment]
@fanlu @xinghedyc To solve it, you just provide the init_states values which are zeros. and https://github.com/dmlc/mxnet/issues/5047

**Comment by fanlu** [comment]
@lji72 It workes well,thx

**Pull request merged**
