### PR TITLE
Add example with sub-word units representation for word2vec.

### PR DESCRIPTION
**Pull request by zihaolucky**
I've implemented another word2vec example based on NCE, and change the word-level vector representation down to triple-letter representations.

The original work was introduced from MSR in CIKM'14 as a part of their DSSM model. Please review and feel free to discuss, I put some details in README.

### CODE REVIEW

**Comment by andremoeller** [comment]
Some notes:

1. Since, as you mention in the README, this is built on example/nce-loss, I think it would be better to just extend nce-loss to run the original or yours optionally, to reduce code duplication and make the examples maintainable -- then we won't end up with two nce-loss examples and directories with a lot of the same code.

2. DMLC keeps their binaries for mxnet.io in https://github.com/dmlc/web-data -- if you'd like to write up a tutorial in markdown, you could put them there. Otherwise, it would be better to just link to wherever they're hosted rather than keep them in this repo.

3. It would be nice to have pydocs for these -- I know the original didn't have pydocs, but since you're familiar with it and are currently working on it, it would be great if the original code were documented as well.

**Comment by piiswrong** [comment]
Please move the images to web-data.
Also consider @andremoeller 's comment. If you don't want to work on it now we can merge in this and refactor later.

**Comment by zihaolucky** [comment]
@andremoeller Thank you so much and I could do it better. @piiswrong let me clean it up before merge this.

I'm going to strip tensorboard for logging and visualization as mentioned in #3306 and have started working on it. It's my pleasure to learn from you guys and I think your suggestions are helpful.

**Comment by piiswrong** [comment]
@zihaolucky Thanks!
Glad to hear you are working on it. Consider putting your work in progress on github (make a repo or make a PR).
Having early feedback is really helpful sometimes.

**Comment by zihaolucky** [comment]
@piiswrong Now better. I refactored the code to make it more clear and remove the images, also update the README :)

I've just started thinking how to reuse tensorboard for our own logging and visualization last night, and I'm going to start from logging first by reusing `tf.SummaryWriter` and `tf.scalar_summary`. I would give a roadmap/proposal to discuss with you all once I make some progress on this direction.

**Comment by piiswrong** [comment]
@andremoeller Could you review again?

**Pull request merged**
