### PR TITLE
fix ssd demo

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by piiswrong** [comment]
Why? These were added to fix bugs

**Comment by howard0su** [comment]
because 571b9a4592bd648d341704c8af7d457215a0e89a breaks this

**Comment by piiswrong** [comment]
Is it due to this:
```

def array(source_array, ctx=None, dtype=mx_real_t):
    """Create a new NDArray that copies content from source_array.

    Parameters
    ----------
    source_array : array_like
        Source data to create NDArray from.

    ctx : Context, optional
        The context of the NDArray, default to current default context.

    Returns
    -------
    out: Array
        The created NDArray.
    """

    if not isinstance(source_array, np.ndarray):
```
?
If yes we should change isinstance(source_array, np.ndarray): to isinstance(source_array, (np.ndarray, NDArray)):

**Comment by howard0su** [comment]
No. I think the only place which needs mean_pixel is in iterator.py. So it should allow to pass in any array like things like array or tuple. and convert it to ndarray in iterator.py. I am not sure what's intention of original fix to convert to ndarray in higher level of code. However it doesn't make sense to me.

**Pull request merged**
