### PR TITLE
set __layout__  attribute for FusedRNNCell output states

### PR DESCRIPTION
**Pull request by formath**
https://github.com/dmlc/mxnet/issues/6736
In `FusedRNNCell`, default layout `N...` is not possible for its output states which should be 'LNC'.
@piiswrong

### CODE REVIEW

**Comment by leezu** [comment]
Thanks

**Comment by piiswrong** [comment]
This should be done in _normalize_sequence

**Comment by piiswrong** [comment]
Actually, I think this commit's approach is better: https://github.com/dmlc/mxnet/pull/6747/commits/c1fd7889a6700b005989e8d5bef45c626a45ca64

swapping contradicts state_info

**Comment by formath** [comment]
Yes. So I have reverted it.

**Pull request merged**
