### PR TITLE
Fix data number computation in NDArrayIter

### LINKED ISSUE #2951: Bug in NDArrayIter when last_batch_handle="discard"
The NDArrayIter defined in [`io.py`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py) has the following codes (Lines 359-369):

    if last_batch_handle == 'discard':
        new_n = self.data_list[0].shape[0] - self.data_list[0].shape[0] % batch_size
        data_dict = OrderedDict(self.data)
        label_dict = OrderedDict(self.label)
        for k, _ in self.data:
            data_dict[k] = data_dict[k][:new_n]
        for k, _ in self.label:
            label_dict[k] = label_dict[k][:new_n]
        self.data = data_dict.items()
        self.label = label_dict.items()
    self.num_data = self.data_list[0].shape[0]

It seems that `self.num_data` is not updated to the correct shape (which should be `self.data[0][1].shape[0]`). As a result, a dimension-mismatch error may occur at runtime.

### PR DESCRIPTION
**Pull request by ArtanisCV**
Fix #2951

### CODE REVIEW

**Comment by piiswrong** [comment]
LGTM

**Comment by winstywang** [comment]
It is good to merge this PR. @ArtanisCV Could you update it to the latest master?

**Comment by ArtanisCV** [comment]
I rebased the PR on the lastest master branch.
Currently, the cpp_test on osx platform failed. This is somewhat strange since this PR only modified several python codes. Unfortunately, Travis didn't provide any log for the failed build (https://travis-ci.org/dmlc/mxnet/jobs/152989680).  Is there any way to reproduce the error?
Thank you.

**Comment by ArtanisCV** [comment]
Seems to be a bug of Travis. The test (cpp_test on osx) passed after rebuild.

**Comment by tornadomeet** [comment]
@ArtanisCV  travis will failed randomly sometimes for unknown reasons.

**Pull request merged**
