### PR TITLE
refactor slice

### PR DESCRIPTION
**Pull request by piiswrong**
incomplete shape for broadcast

### CODE REVIEW

**Comment by piiswrong** [comment]
@yajiedesign @howard0su You need this for keras

**Comment by Piyush3dB** [comment]
@piiswrong mxnet @  252ac62 gives the following compilation error which is not there in df9f612.  Do you think this error is somehow related to this commit?  I'm still investigating...

```
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/piyush/Downloads/GitHub/mxnet/mshadow/ -I/home/piyush/Downloads/GitHub/mxnet/dmlc-core/include -fPIC -I/home/piyush/Downloads/GitHub/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=0  -I/home/piyush/Downloads/GitHub/mxnet/cub -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/matrix_op.cc -o build/src/operator/tensor/matrix_op.o
In file included from include/mxnet/./base.h:16:0,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./matrix_op-inl.h:9,
                 from src/operator/tensor/matrix_op.cc:7:
/home/piyush/Downloads/GitHub/mxnet/nnvm/include/nnvm/tuple.h: In instantiation of ‘class nnvm::Tuple<dmlc::optional<int> >’:
src/operator/tensor/./matrix_op-inl.h:687:37:   required from here
/home/piyush/Downloads/GitHub/mxnet/nnvm/include/nnvm/tuple.h:35:3: error: static assertion failed: Tuple only support simple data type like int
   static_assert(std::is_pod<ValueType>::value,
   ^
In file included from /home/piyush/Downloads/GitHub/mxnet/dmlc-core/include/dmlc/registry.h:13:0,
                 from include/mxnet/operator_util.h:18,
                 from src/operator/tensor/./matrix_op-inl.h:9,
                 from src/operator/tensor/matrix_op.cc:7:
```

**Comment by piiswrong** [comment]
Do this:
`git submodule update && make clean && make`

**Comment by Piyush3dB** [comment]
fixed now, thanks.

**Pull request merged**
