### PR TITLE
fix the implementation bug of "mae" and "mse".

### PR DESCRIPTION
**Pull request by Ldpe2G**

### CODE REVIEW

**Comment by vchuravy** [comment]
Instead of reopening your pull request and losing the ongoing discussion you can force-push to the *same* branch and that will update the PR automatically.

**Comment by Ldpe2G** [comment]
o, I seen, thanks @vchuravy.

**Comment by javelinjs** [comment]
LGTM. Please squash the commits then I'll merge. http://mxnet.readthedocs.org/en/latest/contribute.html#how-to-combine-multiple-commits-into-one

**Comment by Ldpe2G** [comment]
I follow the instruction of the document, but it seems that I have done something wrong.

**Comment by javelinjs** [comment]
@Ldpe2G Thanks, add to the [contributors list](https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md)

Next time when you try to merge from the upstream, consider `git rebase` first, it treats your commits as patches instead of a new branch, which could make you PR cleaner.

**Comment by Ldpe2G** [comment]
I got it thanks @javelinjs

**Pull request merged**
