### PR TITLE
Add deconvolution operator, and the corresponding implement using cudnn_v3

### PR DESCRIPTION
**Pull request by tornadomeet**
1. have done a simple deconvolution_shape_check;  

2. when using deconvolution layer, the mxnet's implemention and cudnn's implemention give the same  output almostly. using the follow example: replace one line of the example/mnist/lenet.py , refer to [deconv_lenet.py](https://github.com/tornadomeet/mxnet/blob/4bdd3a4a52e8ccd7b882fe0f070cc27b81cc0061/example/mnist/deconv_lenet.py)

### CODE REVIEW

**Comment by antinucleon** [comment]
Thanks for the great PR! Could you fix the lint?

**Comment by antinucleon** [comment]
You can try make lint to see the lint result locally.

**Comment by tornadomeet** [comment]
fix lint now.

**Comment by antinucleon** [comment]
Thanks! Another issue is could you add namespace for enum? for example https://github.com/dmlc/mxnet/blob/master/src/operator/convolution-inl.h#L24 . Because we will soon provide  amalgamation version code, this part will make name conflict..

**Comment by tornadomeet** [comment]
i'll add these and check now.

**Comment by tornadomeet** [comment]
now have added the namespace for deconvolution-inl.h and cudnn_deconvolution-inl.h.

**Comment by mli** [comment]
thanks for the PR! but what does deconvolution do? in my understanding it can be used to reserve a convolution layer and used for visualization. but in your lenet example, you just replace the conv layer by deconv layer for training?

**Comment by tornadomeet** [comment]
deconvolution mostly used for upsampling, for example, in image segmentation, can refer [fcn-xs](https://github.com/BVLC/caffe/wiki/Model-Zoo#fully-convolutional-semantic-segmentation-models-fcn-xs), [deconvnet](http://cvlab.postech.ac.kr/research/deconvnet/), [crfasrnn](http://www.robots.ox.ac.uk/~szheng/CRFasRNN.html).
the lenet example here is just for unitest, and i'm implenmenting the fcn-xs in mxnet now, but not very soon.

**Comment by mli** [comment]
@tornadomeet very helpful, thanks!

**Comment by antinucleon** [comment]
Last thing, could you add your name in Contributor.md? then I will merge it

**Comment by tornadomeet** [comment]
ok, i have added my name now.

**Pull request merged**
