### PR TITLE
[Scala] Bucketing API Support

### PR DESCRIPTION
**Pull request by javelinjs**
https://github.com/dmlc/mxnet/issues/3084

* ExecutorManager refactor
* Bucketing api support (include some example bug fixes @Ldpe2G )
* Change DataIter `provideData` and `provideLabel` to `ListMap` to keep the input order

I'll modify the NNVM branch soon.

### CODE REVIEW

**Comment by Ldpe2G** [comment]
by the way, isn't it the order of elements in ListMap in the opposite order you insert them ?

**Comment by javelinjs** [comment]
@Ldpe2G I don't think so.

**Comment by Ldpe2G** [comment]
@javelinjs , I have tried it at the REPL, here is what I got: 
```scala
scala> import scala.collection.mutable.ListMap                                                         
import scala.collection.mutable.ListMap                                                                
scala> val test = ListMap(1 -> 1)                                                                      
test: scala.collection.mutable.ListMap[Int,Int] = Map(1 -> 1)                                                                                                                                
scala> test + (2 -> 2) + (3 -> 3)                                                                      
res3: scala.collection.mutable.Map[Int,Int] = Map(3 -> 3, 2 -> 2, 1 -> 1)  
```

**Comment by javelinjs** [comment]
@Ldpe2G The immutable one lists the elements the same order as we init it (and the `+` or `++` operator, you can try). But for mutable one, you're right, it is confusing. Or we shall use `mutable.LinkedHashMap` instead? While I don't like mutable here.

**Comment by Ldpe2G** [comment]
@javelinjs I see, so, I think using the immutable.ListMap is ok, if the user mistakenly pass the mutable.ListMap will get compile error.

**Pull request merged**
