### PR TITLE
Implementing support for NativeOps in Julia

### PR DESCRIPTION
**Pull request by vchuravy**
I am currently trying to implement NativeOps in Julia. (see https://github.com/dmlc/MXNet.jl/issues/15)

One of the issues is that calling a Julia function directly is not possible. Instead one has to provide a opaque pointer to the julia function one actually wants to call.

See http://julialang.org/blog/2013/05/callback/ and https://github.com/dmlc/MXNet.jl/blob/master/src/kvstore.jl#L115

### CODE REVIEW

**Comment by jermainewang** [comment]
Thanks! @pluskid could you take time to have a look at this?

**Comment by pluskid** [comment]
This looks good to me. I think it is ready to be merged once @vchuravy rebase it to the latest master.

The rational for this modification is that currently Julia is unable to use function with closure capturing for C callbacks. So an opaque pointer object needs to be passed into the backend to hold necessary closure values. This also follows the `updater` API design in the KVStore.

**Comment by piiswrong** [comment]
So the p_forward pointers are pointing to the callback in julia and unused in python?
Looks good to me.

**Comment by pluskid** [comment]
@piiswrong Yes.

**Comment by vchuravy** [comment]
Rebased

**Pull request merged**
