### PR TITLE
Perl interface for MXNet

### PR DESCRIPTION
**Pull request by sergeykolychev**
Hello all,
Let me introduce myself, I am Sergey Kolychev, a Perl programmer from Portland, OR.
First and foremost, thank you for writing such an impressive library!
I really like the design decisions that you guys made!
Here I am proposing a work in progress on an interface to MXNet for Perl programming language.
It's not yet full parity with Python interface, but I plan to get to full parity in coming weeks. 
This is not yet probably ready to be merged in, I am mostly trying to gather your reaction and thoughts about my work.
My final view for this piece is to become integral seamless part of mxnet repository, with a setup as simple as Python one and automated creation of self contained Ubuntu deb packages.
I am striving to keep my Perl code as close as possible to the Python code in order to be able to easy incorporate changes made in the Python interface.
I plan to support this project for foreseeable future.
I used Modern Perl techniques for writing this interface in hopes to make it more readable for a person with no prior Perl knowledge.
Thank you and please consider having this interface a part of your distribution.

### CODE REVIEW

**Comment by piiswrong** [comment]
Hi Sergey,
Thanks a lot for this effort. 34k LOC is really impressive...
As I don't know perl and looks like you didn't modify cpp code I think we can merge this after you add some testing. 
You don't need to test operators as they are tested in python, but you should test your frontend code like tests/python/unittests/test_module.py

**Comment by sergeykolychev** [comment]
Hi @piiswrong,
Thank you for checking it out. 
There's a few test files already, take look at *.t files.

**Comment by piiswrong** [comment]
Ok. Then we just need to expand those and get them running on travis.

**Comment by sergeykolychev** [comment]
@piiswrong Got it, I'll spend some time learning about travis and your usage of it and will update this PR with the requested changes, thanks.

**Comment by thirdwing** [comment]
@sergeykolychev Just a small suggestion. Can you switch to Apache 2 license?

**Comment by sergeykolychev** [comment]
@thirdwing I am completely clueless in this LICENSE business, what's the difference ?
Currently my LICENSE file says that the code is protected either by GNU or Perl Artistic license whichever one will decide to elect, I can certainly add Apache 2 to the mix if it helps.

**Comment by thirdwing** [comment]
The reason is simple: MXNet has been accepted to Apache Incubator and currently the whole repo is using the Apache license.

**Comment by sergeykolychev** [comment]
@thirdwing Cool I'll do that, no difference for me.

**Comment by sergeykolychev** [comment]
@piiswrong 
I checked travis out and looks like you guys running tests on "osx", tried to run my code on osx (I am a Linux guy) and it fails. Is it ok for this interface to be Linux only initially ?

**Comment by piiswrong** [comment]
Yes you can specify to run it on linux in .travis.yml

**Comment by sergeykolychev** [comment]
I'll close this for now and will reopen when I have travis and tests working, thank you guys.

**Pull request closed without merging**
