### PR TITLE
Add zeros, ones, fix compiler warnings

### PR DESCRIPTION
**Pull request by tqchen**
@piiswrong

### CODE REVIEW

**Comment by piiswrong** [comment]
scala test broken

**Comment by tqchen** [comment]
@javelinjs Seems this was due to I explicitly added zeros and ones as symbolic functions. I will change them to _zeros and _ones for now, can you see what happens here?

**Comment by javelinjs** [comment]
@tqchen Yes, it conflicts with code generated `zeros` and `ones`. Thanks.

**Comment by tqchen** [comment]
@javelinjs Do you think if there is ways to fix this? e.g. in python the function is not inserted to the namespace when there is already a function there.

The case is that we want to expose mx.sym.zeros and mx.sym.ones, along with mx.nd.zeros and mx.nd.ones

**Pull request merged**
