### PR TITLE
mshadow updated to include half2 inline change

### PR DESCRIPTION
**Pull request by ap-hynninen**

### CODE REVIEW

**Comment by piiswrong** [comment]
@ap-hynninen Was the previous warning harmful? If so could you add a test that can catch it?

**Comment by ap-hynninen** [comment]
I suppose if someone would run on sm < 530 using float16, but this should be caught by the tests already. I'll try this on older GPU and let you know.

**Comment by piiswrong** [comment]
is K80 < 530?

**Comment by ap-hynninen** [comment]
Yes

**Comment by ap-hynninen** [comment]
If you can test this, that would be great since I won't be able to get to this immediately.

**Comment by piiswrong** [comment]
The test server is K80. So I think it wasn't tested. Probably because test binary is only run on flaot32

**Pull request merged**
