### PR TITLE
Wrote Amazon Linux CPU CI setup

### PR DESCRIPTION
**Pull request by lxn2**
Wrote Dockerfile for Amazon Linux CPU tests environment, dependency installation scripts, and fix for lint failure.

### CODE REVIEW

**Comment by piiswrong** [comment]
does this install jenkins?

**Comment by lxn2** [comment]
No, this itself doesn't build Jenkins. This is for Jenkins to set up build slaves. 

The Dockerfile is the build slave image, the test script will be called as a build step in Jenkins.

**Comment by piiswrong** [comment]
ok. CPU only? Are you going to make seperate gpu testing image?

**Comment by lxn2** [comment]
Yes, CPU only for this commit. I'll write more for Ubuntu and GPU, plus any other varieties of environments we need.

**Pull request merged**
