### PR TITLE
[faster-rcnn] support joint end2end training

### PR DESCRIPTION
**Pull request by tornadomeet**
i have test it on pascal voc 2007, map=69.09% when training 6 epoch, and map=69.3% when training 7 epoch. (map value will increase if we train more epochs), so this training code should be ok. 
@precedenceguo @winstywang @antinucleon

### CODE REVIEW

**Comment by piiswrong** [comment]
@precedenceguo Could you review this?

**Comment by piiswrong** [comment]
@tornadomeet Let's merge this in if you are sure that the results when training without end2end is the same as before

**Comment by tornadomeet** [comment]
@piiswrong yes, the result is almost the same with alternate training(map=69.56%).  but the code design may be discussed, such as the name of fun/var or other design part.

**Comment by precedenceguo** [comment]
Thanks for this great work. Yes indeed, the design of such system is important. However, it is nontrivial to figure out which part is truly essential. So I think we should accept a working version and focus on creating more applications and building more features.

**Comment by piiswrong** [comment]
@precedenceguo @tornadomeet  Let's merge this as long as it doesn't break old non-end2end training and test passes

**Comment by tornadomeet** [comment]
ok, we can merge this first.

**Pull request merged**
