### PR TITLE
Exposing iscontiguous property

### PR DESCRIPTION
**Pull request by JeanKossaifi**
Added a `iscontiguous` property to mx.nd.array.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
@piiswrong Should be OK, not sure about passing an mx_uint instead of a boo though.

**Comment by piiswrong** [comment]
we never use stride so it's always contiguous. There is no need to expose that concept to front end for now.

**Comment by JeanKossaifi** [comment]
Yes, this is pre-work before adding support for strides.

**Comment by piiswrong** [comment]
stride is a huge effort. We'll probably add it after the dlpack refactor. But currently we don't want to commit to any inferface

**Comment by piiswrong** [comment]
closing for now.

**Comment by wkcn** [comment]
I think it's useful to add iscontiguous function in c_api.

I use _LIB.MXNDArrayGetData to get the pointer of a mx.nd.NDArray, and compute it in an external module.
It need to check the contiguous of ndarray in the external module.

**Pull request closed without merging**
