### PR TITLE
A small example for CPP version MLP

### PR DESCRIPTION
**Pull request by zhangchen-qinyinghua**
I make a small example for CPP version MLP.
Hope it to be useful.

### CODE REVIEW

**Comment by piiswrong** [comment]
Thanks for your contribution. This is super helpful!

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong 
I add a Makefile.
And this is just a small example, and I think it is easy to extend to a mnist trainer.
I will try to make a mnist trainer at leisure.

**Comment by piiswrong** [comment]
@zhangchen-qinyinghua I'm not very familiar with makefiles but there may be easier ways of doing this. Like this one https://github.com/pertusa/mxnet_predict_cc/blob/master/Makefile. Please check if it works for your case

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong 
Yeah, like you say, the Makefile could be a lot easier, so I clean it.

However, in my opinion, that way it may become less portable.

For exmeple, -lopenblas only works when the user is using openblas, and in my situation, a -DMSHADOW_USE_CBLAS=1 is also necessary.
And if the user is using a GPU, something like -DMSHADOW_USE_CUDA may be necessary.

Still my Makefile is not portable either, I think add a tail to original Makefile is the best (for portable).
Feel free to modify it if there's better solution.

**Comment by piiswrong** [comment]
I see your point. I think we can
1. add a target to root makefile
2. add a unified makefile for all cpp exmaples that include all the flags and options

@hjk41 @mli What do you think

**Comment by piiswrong** [comment]
Looks good, thanks
one more question: where is use_ndarray.cpp?

**Comment by hjk41** [comment]
@piiswrong I think a CMake file is better for portability. We should have a root CMake file for all the cpp examples, so that when other examples are added, they can be easily built.

**Comment by hjk41** [comment]
@zhangchen-qinyinghua I see you already wrapped some layers including FullyConnected and Softmax into C++. Are you interested in make it complete so users can use the C++ interface just as they do with Python?

**Comment by toothacher17** [comment]
Hi, all

I am trying the mlp.cpp code and I think it is good and able to be understood and able to compile. However, I met some problems and have no idea how to debug for it. The error is:

Cannot find Operator FullyConnected in registry.

So it should be related with the MXNET_REGISTER_OP_PROPERTY. I checked the code in fully_connected.cc, it should have already been registered.

image

As you suggested in the doc on how to build a new operator, I tried to REGISTER the FullyConnected in the operator.h file which are included in my project. However it failed to compile, giving the error, unknown Type Error.

I was not familiar with cpp. I have finished a runnable python version, and now I am trying a cpp version for several reasons. So if I could finish the cpp version, it could be a good example for those who are trying cpp.

The whole project should be runnable, I tested with the NDArray example and it is runnable with NDArray. So I believe my C_FLAGS and L_FLAGS are correct and the problem should be REGISTER related. Can you give any suggestions? Thanks a lot.

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong 
I just put the ndarray example and mlp example together into the same Makefile.
Still, it is not good enough.

@hjk41 
That sounds cool and maybe I will try to make a header file or something as some kind of wrapper latter.
And I think you can try to make a wrapper by your own the way I did in mlp.cpp, or maybe some better ways.

@toothacher17 
As you say, FullyConnected operator is already registered. I can't figure out what exactly is going wrong, so my suggestion is to recompile the mxnet library or even fetch the latest codes before you doing so.

**Comment by tqchen** [comment]
@zhangchen-qinyinghua Thanks for the good job, can you please send another PR to cleanup the code style to Google C++ style, and use lint check as in scripts/lint.py to pass the lint?  It is great to make everything in consistent style

Thanks!

**Comment by tqchen** [comment]
Added you to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md please feel free to push updates about yourself

**Comment by zhangchen-qinyinghua** [comment]
@tqchen 
yeah, sure.
I will do the cleanup during this weekend.

**Comment by toothacher17** [comment]
@zhangchen-qinyinghua @tqchen I fetched the newest code and rebuild it. It is able to compile and the use_ndarray.cpp is able to work. However, for mlp.cpp, it is still Cannot find Operator FullyConnected in registry error...

**Pull request merged**
