### PR TITLE
Improvements to ndarray tutorial

### PR DESCRIPTION
**Pull request by madjam**

### CODE REVIEW

**Comment by nswamy** [comment]
@madjam, we have updated the tutorial with new content, same for the symbol, 
Your changes are based on old content.

**Comment by madjam** [comment]
Sounds good. Where is the new content?

**Comment by nswamy** [comment]
Its under review here
https://github.com/dmlc/mxnet/pull/6196

**Comment by madjam** [comment]
@nswamy the above pr link you shared is for symbol. Where is the one for ndarray?

**Pull request closed without merging**
