### PR TITLE
add error rate metric

### PR DESCRIPTION
**Pull request by wangg12**

### CODE REVIEW

**Comment by winstywang** [comment]
Why do we need it since we have already had accuray metric?

**Comment by wangg12** [comment]
More flexible to choose either accuracy or error rate?

**Comment by winstywang** [comment]
I don't see the reason for that... acc + err always equal to 1, right?

**Comment by wangg12** [comment]
Yeah. They are actually equivalent. But some one may like to see the error rate and others may like to see the accuracy. It's just a matter of taste. I just want it to be more flexible.

**Pull request closed without merging**
