### PR TITLE
Typo fix: MX_THREAD_LOCAL

### PR DESCRIPTION
**Pull request by ZihengJiang**

### CODE REVIEW

**Comment by tqchen** [comment]
This file should be simply removed in favor of dmlc-core/thread_local

**Comment by ZihengJiang** [comment]
@tqchen I see

**Comment by ZihengJiang** [comment]
please hold until this has been merged: https://github.com/dmlc/dmlc-core/pull/247

**Comment by piiswrong** [comment]
@ZihengJiang could you remove the file and update dmlc-core?

**Pull request closed without merging**
