### PR TITLE
[OP] Add expand_dims

### PR DESCRIPTION
**Pull request by tqchen**
cc @piiswrong

### CODE REVIEW

**Comment by jermainewang** [comment]
Cool, does this require deep copy?

**Comment by tqchen** [comment]
For ndarray actually yes unless you do nd.expand_dims(x, out=x, axis=1). For symbolic operator, usually inplace will happen and no operations will be taken

**Comment by jermainewang** [comment]
Hmm, is this because we don't have view layer for ndarray?

**Comment by tqchen** [comment]
Yes.  I think so

**Pull request merged**
