### PR TITLE
DType support using fp32 random only

### PR DESCRIPTION
**Pull request by Godricly**
previous fp64 random generation is removed. All DTypes random number are generated with fp32 then cast to DType.
@tqchen @sxjscience

### CODE REVIEW

**Comment by piiswrong** [comment]
why remove fp64?

**Comment by Godricly** [comment]
Tianqi has some concern with on fp64 random generation so It is replaced with current approach using fp32 and type casting.

**Comment by tqchen** [comment]
we can change the implementation back later once resource support getter of double randomstream, or when mshadow's random class support both float and double

**Comment by Godricly** [comment]
I think it dose support double, if you look at [random.h](https://github.com/dmlc/mshadow/blob/master/mshadow/random.h).

**Comment by tqchen** [comment]
Yes, the problem is that we need a separate generator for double and float, the current resource manager only provide float generator

**Comment by Godricly** [comment]
Is [this](https://github.com/dmlc/mxnet/blob/master/include/mxnet/resource.h#L64) what you are talking about? This is defined as DType, which should be compatible with double.

**Comment by Godricly** [comment]
temporary closed for lstm fails

**Comment by Godricly** [comment]
Some type issue with simpleop. working on it.

**Comment by Godricly** [comment]
Now it works for lstm 2. Another more pretty approach to fix it is to modify io.py which is not compatible with previous written iters as provieded_type is not defined before.

**Comment by tqchen** [comment]
@piiswrong please have another round of review, and we can merge it in. Let us make sure that provide_type is optional

**Comment by Godricly** [comment]
This one is still not able to run in multi device scenario. I'm working on it.

**Comment by Godricly** [comment]
I updated kvstore so it can run in multi-device case.

**Pull request closed without merging**
