### PR TITLE
[R-package] R example cifar10 - implement auto load data

### PR DESCRIPTION
**Pull request by matt32106**
R examples don't work out of the box. This pr implements auto data load for the cifar10 one.

### CODE REVIEW

**Comment by matt32106** [comment]
mxnet-pr-gpu test has failed but i have no clue what i can do about it!? i don't understand if the error is specific to my code or not

**Comment by piiswrong** [comment]
@thirdwing

**Comment by matt32106** [comment]
@thirdwing please tell me if this kind of PR is worthwhile or if data loading should be kept separate (in that case, it should be documented in the code i think)

**Comment by thirdwing** [comment]
I will look into it today. Sorry that super busy recently.

**Comment by piiswrong** [comment]
Can one of the admins verify this patch?

**Comment by mli** [comment]
I'm going to close this PR since there is no activity for more than 2 months. But please feel free to re-open it and update this branch with the master.

**Pull request closed without merging**
