### PR TITLE
Lazy Refactor Native OP

### PR DESCRIPTION
**Pull request by antinucleon**
@piiswrong @tqchen 

The purpose of refactor is to simplify C++ NativeOp. For aug_state, it is still left there.

### CODE REVIEW

**Comment by piiswrong** [comment]
why do we still need nativeop?

**Comment by antinucleon** [comment]
It is easy to write C++ Native Op. For CustomOp, as reported there is memory leak in  multi-device, so we still need NativeOp for a while.

**Comment by sxjscience** [comment]
@antinucleon Could you tell more about the memory leakage problem? I've recently changed all my python-side Ops to CustomOp

**Comment by antinucleon** [comment]
@sxjscience One user reported there is memory leak when CustomOp runs on multi device for a long time, I don't verify it by myself yet. As I need C++ NativeOp so I refactor this first.

**Comment by piiswrong** [comment]
did he create symbols repeatedly? Currently created symbol and operators will never be deleted

**Comment by antinucleon** [comment]
Yes, in faster rcnn, it requires bind at each batch. Before fix it, I am
thinking to make NativeOp support save & load.
On Sun, May 29, 2016 at 00:13 Eric Junyuan Xie <notifications@github.com>
wrote:

> did he create symbols repeatedly? Currently created symbol and operators
> will never be deleted
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/pull/2272#issuecomment-222346485>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13svmKdAcySYM74__tF4ned-iaoAOks5qGTyAgaJpZM4IpNXu>
> .
>
-- 
Sent from mobile phone

**Comment by piiswrong** [comment]
Ok. Should be easy to fix. Just clear the ref_holders when operators are deleted

**Comment by antinucleon** [comment]
@winstywang I think the lazy refactor is done, please help me review it. Basically, I changed it to Async and replace buffer with fixed host memory. For saving and loading, we may postpone for a while because it is not urgent.

**Pull request merged**
