### PR TITLE
Amalgamation test failure solved

### PR DESCRIPTION
**Pull request by Roshrini**
Thanks @lxn2 for helping with this.
@piiswrong This should solve amalgamation test failure.

### CODE REVIEW

**Comment by piiswrong** [comment]
Is `-I ${MXNET_ROOT}/dmlc-core/src` necessary?

**Comment by Roshrini** [comment]
Yes otherwise it fails saying didn't find .cc files

**Comment by piiswrong** [comment]
@ZihengJiang Any idea why we need dmlc-core/src now?

**Comment by piiswrong** [comment]
Any idea why jenkins amalgamation tests didn't catch this?

**Pull request merged**
