### PR TITLE
Add pickleIter and fixed a bug when last_batch_handle is 'discard'

### PR DESCRIPTION
**Pull request by sophie4869**
The pickleIter uses pickle to load data from separate files instead of loading everything into memory at the same time. It starts a new thread that read data asynchronously.

### CODE REVIEW

**Comment by piiswrong** [comment]
It's usually much faster to use numpy's own serialization than pickle.

**Comment by winstywang** [comment]
The data is stored in a dictionary instead of a simple numpy array. And the data loading is asynchronously, it should be fine.

**Comment by piiswrong** [comment]
pickle can be really slow on large nparrays and it sometimes take up several times more disk space. 

Also I think we should refactor the dataiterators to separate iterator and data source. One iterator should be able to provide data from many data source times as long as they have a common interface.

**Comment by winstywang** [comment]
OK, we will turn to numpy serialization first.

**Comment by winstywang** [comment]
close for now. Will contribute a new PR soon.

**Pull request closed without merging**
