### PR TITLE
add cudnn v4 with CUDNN_MAJOR auto switch v3/v4

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Comment by piiswrong** [comment]
Have you tested whether this indeed works with both v3 and v4? Also do we need to check for minor? Is minor always 0 for all v3 and v4 libs?

**Comment by yajiedesign** [comment]
you means only check MAJOR?

**Comment by piiswrong** [comment]
I'm not sure. Does cudnn v3 R1-3 all have minor 0?

**Comment by antinucleon** [comment]
I don't think we need to support CuDNN v3 R1-3 because CuDNN v3 Prod is the final product version. Support CuDNN v3 is temporary. I think it is ready to be merged.

**Comment by antinucleon** [comment]
I checked V3 prod and V4, and I think this PR is fine.

**Comment by wangg12** [comment]
So the doc(http://mxnet.readthedocs.org/en/latest/build.html) is out of date? It says only cuDNN v3 is supported.

**Pull request merged**
