### PR TITLE
add keep_highest to reshape op

### PR DESCRIPTION
**Pull request by winstywang**
Current reshape implementation will fail in multi-gpu case, since in multi-gpu case the batch size will be changed, but current implementation can only hardcode highest dim.

### CODE REVIEW

**Comment by piiswrong** [comment]
You can leave the highest dim 0 and it will be inferred

**Comment by tqchen** [comment]
@piiswrong maybe we need to add an explaination of this behavior

**Comment by piiswrong** [comment]
Its in the doc.

**Comment by winstywang** [comment]
@tqchen @piiswrong No, that does not fit our need. We want to reshape the 3rd dim, so we keep it as 0.

**Comment by winstywang** [comment]
And more importantly, we should never reshape the highest dim by hard coding a number. It will always break the multi-gpu function. @piiswrong @tqchen

**Comment by piiswrong** [comment]
Some times you want to change the batch size because of different batch size between data/label.

**Comment by winstywang** [comment]
@piiswrong Yes, but it still will fail the multi-gpu case, right? Because the we cannot know the actual batch size beforehand in the multi-gpu case.

Our case is simply reshape the 3rd dim, and keep the highest dim. However, current implementation will incur infer shape error in multi-gpu case. That is why we need this fix.

**Comment by tqchen** [comment]
I think in multi-GPU case, simple bind was performed on each device with their batch-size.
I still think  @piiswrong could be right that setting the batch dimension to 0 should work, the logic seems to be identical to the keep_highest

**Pull request merged**
