### PR TITLE
A3C example

### PR DESCRIPTION
**Pull request by piiswrong**
@winstywang @tornadomeet @sxjscience

### CODE REVIEW

**Comment by sxjscience** [comment]
@peterzcc

**Comment by loofahcus** [comment]
Here is a group of possible hyperparameters: [async-rl/wiki](https://github.com/muupan/async-rl/wiki)

**Comment by apeng5399** [comment]
+ batch = mx.io.DataBatch(data=S[i], label=[mx.nd.array(A[i]), mx.nd.array(R)])
+                module.forward(batch, is_train=True)
+
+                pi = module.get_outputs()[1]
+                h = args.beta*(mx.nd.log(pi+1e-6)+1)
+                module.backward([mx.nd.array(adv), h])

I can not undertand the label in DataBatch and the module.backward([mx.nd.array(adv), h]), please help

**Comment by apeng5399** [comment]
label=[mx.nd.array(A[i]), mx.nd.array(R)]) i think A[i] shape is 1 * batch_size, R is batch_size * 1,
however in sym file output is [batch_size*act_dim,batch_size*act_dim,batch_size*1]
But the gradient for backward is [batch_size * act_dim,batch_size * act_dim], I am really confused, maybe
something wrong with my uderstanding of dataBatch or symbol or gredient, please help

**Pull request merged**
