### PR TITLE
Update new AMI Ids

### PR DESCRIPTION
**Pull request by nswamy**

### CODE REVIEW

**Comment by piiswrong** [comment]
we need a better solution than updating code everytime ...

**Comment by mli** [comment]
do we need to change the ids for every update? i think we have secret weapons to update ami while keeping the id

**Comment by piiswrong** [comment]
@mli Make it use module instead of model while you are at it?

**Comment by piiswrong** [comment]
@mli Also I think we should put some of the logic into functions and move them into the main repo.
Currently I frequently have to copy large chunk of code like argparser, log config, kv store create, model load/save

Here is an idea:
```

def log_config(log_dir=None, log_file=None, prefix=None, rank=0):
    reload(logging)
    head = '%(asctime)-15s Node[' + str(rank) + '] %(message)s'
    if log_dir:
        logging.basicConfig(level=logging.DEBUG, format=head)
        if not os.path.exists(log_dir):
            os.makedirs(log_dir)
        if not log_file:
            log_file = (prefix if prefix else '') + datetime.now().strftime('_%Y_%m_%d-%H_%M.log')
            log_file = log_file.replace('/', '-')
        else:
            log_file = log_file
        log_file_full_name = os.path.join(log_dir, log_file)
        handler = logging.FileHandler(log_file_full_name, mode='w')
        formatter = logging.Formatter(head)
        handler.setFormatter(formatter)
        logging.getLogger().addHandler(handler)
        logging.info('start with arguments %s', args)
    else:
        logging.basicConfig(level=logging.DEBUG, format=head)
        logging.info('start with arguments %s', args)
```

**Comment by nswamy** [comment]
I agree, it is not feasible to keep updating everytime a new AMI is made
available. As far as I know there is no other straight forward way other
than to make it a user defined parameter and ask to the user to pickup the
AMI-Ids from S3 file which will always contain the latest AMI ids.
I think we can also make a AWS Lambda Function return the AMI-Id given a
region, I will explore that further.

Thanks for your patience.

-Naveen


On Mon, Nov 14, 2016 at 10:32 AM, Eric Junyuan Xie <notifications@github.com

**Pull request merged**
