### PR TITLE
Add Google Group

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by mli** [comment]
but i remember most people voted disqus on #1020

**Comment by tqchen** [comment]
The original proposal actually meant  https://www.discourse.org/ . Anyway, we can go with either option but stick to one as long as it is good for the user

**Comment by mli** [comment]
got it. we can host it at dmlc.ml, but needs some maintian effect then...

**Comment by tqchen** [comment]
Let us use google group for now then, since it does not require hosting effort

**Comment by vchuravy** [comment]
I would be willing/interested to help out with maintaining a discourse installation. It seems the easiest thing is to install it via docker. https://github.com/discourse/discourse/blob/master/docs/INSTALL.md

**Comment by mli** [comment]
@vchuravy up now, http://forum.dmlc.ml/c/mxnet

**Comment by mli** [comment]
@vchuravy discourse is surprisingly fancy, love it a lot:)

**Comment by vchuravy** [comment]
Nice! Just signed up.

**Comment by tqchen** [comment]
OK, after discussion with @mli I think we will advocate discourse as main community support, close this for now

**Pull request closed without merging**
