### PR TITLE
fix docs

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by leopd** [comment]
Is this going to bring back the symbol reference?

**Comment by piiswrong** [comment]
This did it on my machine. Somehow it's still not working on the server

**Comment by piiswrong** [comment]
@mli Could you update sphinx version on the server?

**Comment by leopd** [comment]
Makes me think we should move to doing docs builds in a docker container so the build environment can be reliably specified & managed in a Dockerfile.

**Pull request merged**
