### PR TITLE
fix a few dependence issues in install-mxnet-ubuntu-r.sh

### PR DESCRIPTION
**Pull request by lazyparser**

### CODE REVIEW

**Comment by miguelgfierro** [comment]
Hi @lazyparser for R it's recommended to install MRI or MRS rather than the distribution that comes with Ubuntu, which is quite old.

**Comment by lazyparser** [comment]
Hi @miguelgfierro thank you for your recommendation :-). Although MRO is a good distro, the default packages are more easier for beginners to config and install. A better solution would be install r-base-core only when 'Rscript' is absent on user's environment. I'll update the patch.

**Comment by piiswrong** [comment]
@lazyparser Does this patch fix it for the default distro?
@miguelgfierro Does this patch break it for MRO or MRS? If not we should merge it

**Comment by miguelgfierro** [comment]
It shouldn't break

**Comment by thirdwing** [comment]
`libcurl4-openssl-dev` and `libssl-dev` are required by `devtools`.

@miguelgfierro You can add the PPA for latest R build if necessary.

**Pull request merged**
