### PR TITLE
[R] add R test into jenkins; add rpkgtest into makefile

### PR DESCRIPTION
**Pull request by thirdwing**
The R test will exceed the time limit on Travis CI if more tests are added. Adding R task on the Jenkins server might be better.

@mli Do we have R installed on the Jenkins servers?

### CODE REVIEW

**Comment by piiswrong** [comment]
I think you need to modify the install script and create the right environment to install R. You are currently using scale-env, which own't work.
https://github.com/dmlc/mxnet/blob/master/docker/install/r.sh

**Comment by thirdwing** [comment]
My mistake. Not notice that. Will update this.

**Comment by thirdwing** [comment]
`fatal: write error: No space left on device`

**Comment by piiswrong** [comment]
Each time you modify jenkinsfile a docker image will be created. So the server quickly run out of storage.

Please verify that every works locally before pushing

**Comment by szha** [comment]
Should the wrong docker images be cleaned up then?

**Comment by thirdwing** [comment]
screenshot from 2017-06-19 13-47-01

I think no more `No space left on device` error.

**Comment by thirdwing** [comment]
Passed on Jenkins server.

screenshot from 2017-06-21 10-54-26

**Comment by piiswrong** [comment]
Is this mergable?

**Comment by thirdwing** [comment]
This is mergable, but this will a new task into Jenkins server.

**Comment by thirdwing** [comment]
This is mergeable if it is fine to add R test into Jenkins servers. @piiswrong

**Comment by mli** [comment]
how about gpu and windows?

**Comment by thirdwing** [comment]
Of course. But I am afraid it will take me several days to learn how to set up the Windows testing.

**Comment by piiswrong** [comment]
@mli 
Since R is merged now let's close the old jenkins: http://jenkins-master-elb-1979848568.us-east-1.elb.amazonaws.com/job/mxnet-pr-r/3233/console

**Pull request merged**
