### PR TITLE
[scala-package] improve the readability of Spark-Mxnet implementation 

### PR DESCRIPTION
**Pull request by CodingCat**
the basic approach is to disassemble the long method into several shorter ones...

### CODE REVIEW

**Comment by CodingCat** [comment]
@javelinjs @Ldpe2G would you mind giving a review?

**Comment by Ldpe2G** [comment]
I am not farniliar with spark @javelinjs

**Comment by javelinjs** [comment]
Thanks!

**Comment by CodingCat** [comment]
thanks

**Pull request merged**
