### PR TITLE
Add `CPDecomp3D` till `CPDecomp6D` for CP Decomposition

### PR DESCRIPTION
**Pull request by jli05**
These Operators perform the CANDECOMP/PARAFAC Decomposition, which can be compared to extension of SVD to higher-order tensors. Denote by `T` an order-n input tensor of shape d_1-by-...-by-d_n. To perform a rank k CP Decomposition, in pseudo code,

```python
results = CPDecomp<n>d(data=T, k=<k>)
```

 will produce the length-k eigenvalue vector in `results[0]`, and k-by-d_i transposed factor matrix in `results[i]`, for i = 1,..,n.

### CODE REVIEW

**Comment by piiswrong** [comment]
please move these operators to contrib. https://github.com/dmlc/mxnet/pull/5499

**Comment by jli05** [comment]
Sure would you want them to be under `src/operator/contrib/tensor` or `src/operator/tensor/contrib`?

Could you advise how to get a `Tensor` variable from `TBlob` whose `dim` we cannot know at compile time?

**Comment by jli05** [comment]
We register `CPDecomp3D` till `CPDecomp6D` Ops in MXNet. The forward calculation of these ops would all call `CDDecomp()` in `src/operator/contrib/tensor/cp_decomp.h`. The current code only works with MKL as BLAS/LAPACK lib.

**Comment by piiswrong** [comment]
You don't need to make 3 ops. You can get input dimensions in infershape and create operator

**Comment by jli05** [comment]
Do you have code example how? I can work with Op shape in `inferShape()` but somewhere I have to write

```c++
tensor<xpu, dim, DType> ts = in_data[0].get<xpu, dim, DType>(stream);
```

before feeding `ts` into the core function `CPDecomp()`. This line doesn't compile unless maybe we do something similar to the macro `MSHADOW_TYPE_SWITCH` but then we could only cover a finite number of cases for `dim`?

**Comment by piiswrong** [comment]
You can see the input shape in create operater ex so you can decide which template argument to use there

**Comment by jli05** [comment]
I understand what you say. My problem is I already had to template `CPDecompProp` as I had to define properly `NumVisibleOutputs()` and `NumOutputs()` as below. What do you think?

```c++
template <int order>
class CPDecompProp : public OperatorProperty {
  // ...

  int NumVisibleOutputs() const override {
    return order + 1;
  }

  int NumOutputs() const override {
    return order + 1;
  }
}
```

**Comment by jli05** [comment]
Another problem I have is that the current code is written for MKL (it uses the C LAPACK interface in MKL), it fails all online Travis tests. What would you suggest doing? Shall I write for ATLAS/OpenBLAS as well? The problem is the C LAPACK interface in these libs all differ a bit; and I'll have to modify the `Makefile` to export environment variables signalling the current LAPACK lib.

**Comment by piiswrong** [comment]
Yes, please wrap blas call in a function, e.g. mxnet_gemm and toggle with compile flag inside it:
```
void mxnet_gemm(...) {
#if MSHADOW_USE_MKL
...
#else
...
#endif
}
```

**Comment by jli05** [comment]
Thanks Eric. The C BLAS function signatures are uniform across all libs. However when it comes to the C LAPACK interface, vecLib, ATLAS support the dated CLAPACK interface (direct translation of the Fortran interface to C); NetLib, MKL, OpenBLAS support the newer LAPACKE interface. Therefore I may need to modify the global `Makefile` to define macro corresponding to the exact BLAS/LAPACK lib in use?

Example of `dposv` (linear solver for symmetric, semi-positive A):

Under CLAPACK interface, 

```c
int dposv_(char *__uplo, 
        __CLPK_integer *__n, __CLPK_integer *__nrhs,
        __CLPK_doublereal *__a, __CLPK_integer *__lda, 
        __CLPK_doublereal *__b, __CLPK_integer *__ldb,
        __CLPK_integer *__info);
``` 

Under LAPACKE interface,

```c
lapack_int LAPACKE_dposv (int matrix_layout, char uplo, 
        lapack_int n, lapack_int nrhs, 
        double * a, lapack_int lda, 
        double * b, lapack_int ldb);
```

**Comment by piiswrong** [comment]
config.mk has a USE_BLAS option. I think you can test that.

**Comment by jli05** [comment]
Does the CI build for MS Windows use MKL for BLAS?

**Comment by jli05** [comment]
The `libopenblas.so` in the package `libopenblas-dev` in Ubuntu 14.04 didn't include the LAPACK routines that the code links to, I had to change the CI Docker base image to Ubuntu 16.04 to correct the problem. An ensuing problem was that the Ubuntu 16.04 Docker image only includes a minimal list of packages and doesn't include `sudo`, so I had to comment out `sudo` in the CI build script.

**Comment by jli05** [comment]
Under `mshadow`, `mshadow/extension/implicit_gemm.h` L70-71,

```c++
    const size_t packetSize = Packet::Size();
    DType lhs_temp[packetSize], rhs_temp[packetSize];
```

The 2nd line is allowed by GCC/Clang but not by MSVC for the uncertain array length. Do you want me to do a PR in `mshadow` to fix this?

**Comment by mli** [comment]
I'm going to close the PR since there is no activity for more than 2 months. But please feel free to re-open it and update with the master.

**Pull request closed without merging**
