### PR TITLE
a tutorial for multi-task

### PR DESCRIPTION
**Pull request by haria**
@tqchen

I just write a tutorial to introduce my work on multi-task using mxnet.

I am not a English native speaker, so there should be some Gramma mistake, welcome to point out and fix it.

thank you very much!
Haria

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks a lot for the contribution! We are planning to move the notebooks to a separate repo to reduce the burden of the main one. 

For now, what we can do instead is you can open a repo called mxnet-multi-task-example on your side, and we can add a link to your repo  from example. This can increase visibility of your contribution, and we can do more comments on the issues there

**Comment by piiswrong** [comment]
we can create a notebook repo and make it a sub module under example

**Comment by haria** [comment]
Hi @tqchen 

I move the notebooks to https://github.com/haria/mxnet-multi-task-example

the file URL is: https://github.com/haria/mxnet-multi-task-example/blob/master/multi-task.ipynb

Thanks!

**Comment by tqchen** [comment]
sounds great, I am closing this PR. Please send another PR to add the link to your notebook in multi task example's markdown as well as example/README.md

**Pull request closed without merging**
