### PR TITLE
Make the range function compatible to both Python 2 and 3.

### PR DESCRIPTION
**Pull request by lazywei**
- Changed the `xrange` to compatible `range`.

I noticed this incompatibility when trying the new interface. And this was also mentioned in https://github.com/dmlc/mxnet/pull/4618#discussion_r100542992.

### CODE REVIEW

**Comment by yajiedesign** [comment]
you can use `from future.builtins import range`

**Comment by lazywei** [comment]
@yajiedesign 
Thanks for your feedback. So we have the `future` package as dependencies in mxnet, right? I didn't find the specification of the dependencies mxnet relied on so I'm not sure if I can use it directly.
Also, how can I find the lint message?

Thanks.

**Comment by sxjscience** [comment]
I think we could use "range" directly if there is not much speed difference.

**Comment by lazywei** [comment]
@sxjscience I agreed. I have updated it to use the `range` function directly.
@yajiedesign I saw a bunch of lint warning in my editor, which used PEP8 as standard. Yet, these warnings are coming from previous commit and have nothing to do with this PR. I'm wondering should I fix them in this PR or submit another PR later to fix them?

Thanks

**Comment by yajiedesign** [comment]
@lazywei Taking into account the possible difficulties in merging, do not modify the code format in a large area

**Comment by piiswrong** [comment]
closed due to already fixed

**Pull request closed without merging**
