### PR TITLE
custom op

### PR DESCRIPTION
**Pull request by piiswrong**
This fixes the problem that NDArrayOp and NativeOp cannot be save/loaded.
Also allow op with state to be used on multi cards.
I'm also planning to add more options like inplace

### CODE REVIEW

**Comment by vchuravy** [comment]
How does this differ from `NativeOp` and `NDArrayOp`?

**Comment by piiswrong** [comment]
@vchuravy updated description

**Comment by vchuravy** [comment]
So this would supersede both `NativeOp` and `NDArrayOp` and from looking over the code it seems that it also addresses the issues I had with porting this to the Julia side. Will give it another try after this has been merged.

**Comment by piiswrong** [comment]
Yes. I intend to deprecate those after we fix the interface for this.

**Comment by Godricly** [comment]
so are we inheriting this custmOp in C++? or the Operator class?

**Comment by piiswrong** [comment]
@Godricly see the example under examples/numpy-ops/custom_softmax.py

**Comment by Godricly** [comment]
This is the one posted on online doc. If I have to write a cuda kernel, do I need to use the mx.rtc?

**Comment by sbodenstein** [comment]
@piiswrong: is this CustomOp API compatible with other languages, like R via Rcpp? In the previous API, the custom forward and backward function pointers in NativeOpInfo could be given state via a void* argument. This is no longer the case. What was the motivation for dropping this? (perhaps I'm missing something)

**Comment by piiswrong** [comment]
@sbodenstein They can be added. Usually the people using julia or R does this since python doesn't need it.

**Comment by sbodenstein** [comment]
@piiswrong: can I add support for this, copying how it was done for NDArrayOpInfo/NativeOpInfo? Or do you have another preference?

**Comment by vchuravy** [comment]
@sbodenstein We will probably need it for Julia, but I haven't looked into the best way of doing this with Julia v0.5.

**Comment by sbodenstein** [comment]
@vchuravy: ok, then your feedback for the design will be very useful.

Here is one proposal: each function pointer takes an additional argument, the name of the op (char* op_type). This seems simpler and more intuitive than using void pointers to do the dispatch (like the old NDArrayOpInfo used).

**Comment by vchuravy** [comment]
Hm how do you deal with different instance of the same operator? The reason
for using void pointer is so that the front-end can attach an arbitrary
payload.

**Comment by sbodenstein** [comment]
How useful is it to allow multiple instances of the same operator? The current design seems to explicitly disallow this: there is a check in `custom-inl.h`: 
```
  static void Register(const std::string &op_type, CustomOpPropCreator creator) {
    if (registry_.find(op_type) != registry_.end()) {
      LOG(WARNING) << "New registration is overriding existing custom operator " << op_type;
```

**Comment by tqchen** [comment]
you can have multiple of them as long as they are registered to different names.

https://github.com/dmlc/mxnet/pull/2051/files#diff-234886ea4087927b3aadc36ec77635c4R21

**Comment by piiswrong** [comment]
this is registration of op classes. Insstances can then by created from the
class. Instances can have internal state.

**Comment by sbodenstein** [comment]
@piiswrong: Ah, I see. Should I go the void* route, make a pull request, and you decide whether its the correct approach?

**Comment by piiswrong** [comment]
of course. it should basically be mimicking native op and numpyop

**Pull request merged**
