### PR TITLE
quick fix fcn-xs example

### PR DESCRIPTION
**Pull request by tornadomeet**
this is a quick fix.

Due to the pool/conv shape is changed currently , so the fcn-xs example is broken, such as https://github.com/dmlc/mxnet/issues/2925 https://github.com/dmlc/mxnet/issues/3638 https://github.com/dmlc/mxnet/issues/3634  
the reason for this issue should due to the shape before deconv is smaller than old-mxnet-version, so we just make the output shape of deconv bigger than before, i test in on fcn-32 training, and it seems ok.

### CODE REVIEW

**Comment by animebing** [comment]
@tornadomeet so i need to pull the latest version of MXNet, then compile again or something else?

**Comment by tornadomeet** [comment]
no need compile again,just change some line of symbol_fcnxs.py as this pr does.

**Comment by GMarzinotto** [comment]
I still get this error despite the changes.
For me it is not an error training the system (it is not my intention to do so) but an error using the model to segment certain images.
It works for 95% of the images but for some of them the program crashes.

To evaluate the images I run the example:
fcnxs_args["data"] = mx.nd.array(get_data(fullimagePath), ctx)
            data_shape = fcnxs_args["data"].shape
            label_shape = (1, data_shape[2]*data_shape[3])
            fcnxs_args["softmax_label"] = mx.nd.empty(label_shape, ctx)
            exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
            exector.forward(is_train=False)
            output = exector.outputs[0]

and I get the following error:

 /home/gabriel/MXNet/mxnet/dmlc-core/include/dmlc/logging.h:235: [22:29:41] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
[22:29:41] /home/gabriel/MXNet/mxnet/dmlc-core/include/dmlc/logging.h:235: [22:29:41] src/engine/./threaded_engine.h:306: [22:29:41] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [22:29:41] src/engine/./threaded_engine.h:306: [22:29:41] src/operator/./crop-inl.h:117: Check failed: (static_cast<int>(param_.offset[0])) <= (data_shape[2]-out_shape[2]) offset[0] should be less than the residual space of height
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)

I'm also attaching  the image that makes the system crash 

n02084071_1

**Comment by tornadomeet** [comment]
hello, @GMarzinotto  because the model is trained with old version of mxnet, so it may crash when used in the newest mxnet. the model provided will crash with some size of input image with newest mxnet, so you'd better resize the image to a good size(which not crash, should just try)at first

**Comment by colorfulCloud** [comment]
I was wondering if I use not real RGB- image that composed by 3 same gray image ,Can that be worked?

**Comment by lucky-ing** [comment]
you can convert your old json file into lastest version to solve this problem. there are three deconvolution nodes in this fcn network. Add "adj": "(0, 0)" after "workspace": "****" line in the first two deconvolution nodes' params, and add "adj": "(0, 0)" ( I use it and bingo~) or "adj": "(7, 7)" after  "workspace": "****" line in the last deconvolution node's params.

**Pull request merged**
