### PR TITLE
Add RNN model in R

### PR DESCRIPTION
**Pull request by ziyeqinghan**
I add Custom RNN model and some high-level reusable APIs is provided which is similar to the APIs for LSTM in [#2329]
- `mx.rnn` Training RNN Unrolled Model
- `mx.rnn`.inference Create a RNN Inference Model
- `mx.rnn.forward` Forward function for RNN inference model

### CODE REVIEW

**Comment by tqchen** [comment]
@thirdwing can you review this?

**Comment by thirdwing** [comment]
LGTM. This is mostly refactoring work.

Sorry for the delay. I was caught in a bad cold while in Texas.

@terrytangyuan I will merge this if you agree.

**Comment by terrytangyuan** [comment]
@thirdwing Go ahead. Looks good. @ziyeqinghan You might need to rebase.

**Comment by ziyeqinghan** [comment]
The branch is rebased.

**Pull request merged**
