### PR TITLE
Repository is missing

### PR DESCRIPTION
**Pull request by Abusnina**
The repository field in the package description is missing. This is needed so that we can deploy shiny packages on shinyapp.io. Currently the deployApp function can not detect where to grab the money packe from. Please add the missing field.

### CODE REVIEW

**Comment by piiswrong** [comment]
@miguelgfierro @thirdwing

**Comment by thirdwing** [comment]
Personally I think even we have this field, you still can't deploy on shinyapp.io. We don't host any `mxnet` package for linux machine.

**Comment by AAbusnina** [comment]
I sent the output of the following command "packageDescription("mxnet")" to the shinyapp.io support team, and they advised to pull this request. 
Does that mean we won't be able to deploy apps in shinyapp.io that use mxnet?

**Comment by thirdwing** [comment]
Currently I am afraid you can't use `mxnet` directly.

What `shinyapp.io` does is to get the pkg from some repo, including the CRAN and github.

I believe they are using Linux as the backend, however, we don't host any Linux pkg in any repos.

I will double check with them.

**Pull request merged**
