### PR TITLE
Fix for WarpCTC conflict

### PR DESCRIPTION
**Pull request by sbodenstein**
This seems enough to fix https://github.com/dmlc/mxnet/issues/6603

### CODE REVIEW

**Comment by sbodenstein** [comment]
This is compiling and passing tests on OSX and Linux, but failing on VS:
```
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(72): error C2143: syntax error : missing ';' before '<' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
                 c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(91) : see reference to class template instantiation 'mxnet_warpctc::CpuCTC<ProbT>' being compiled
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(72): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(75): error C2238: unexpected token(s) preceding ';' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(178): error C2039: 'tuple' : is not a member of 'mxnet_warpctc::std' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(178): error C2143: syntax error : missing ';' before '<' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(178): error C2988: unrecognizable template declaration/definition (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(178): error C2059: syntax error : '<' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(179): error C2065: 'ProbT' : undeclared identifier (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(179): error C2923: 'mxnet_warpctc::CpuCTC' : 'ProbT' is not a valid template type argument for parameter 'ProbT' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(179): error C2039: 'cost_and_grad_kernel' : is not a member of 'mxnet_warpctc::CpuCTC' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
                 c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(16) : see declaration of 'mxnet_warpctc::CpuCTC'
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(214): error C2065: 'ProbT' : undeclared identifier (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(214): error C2923: 'mxnet_warpctc::CpuCTC' : 'ProbT' is not a valid template type argument for parameter 'ProbT' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(218): error C2143: syntax error : missing ';' before '{' (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) [C:\projects\mxnet\build\mxnet.vcxproj]
     8>c:\projects\mxnet\src\operator\contrib\./ctc_include/detail/cpu_ctc.h(218): error C2447: '{' : missing function header (old-style formal list?) (C:\projects\mxnet\src\operator\contrib\ctc_loss.cc) 
```
I don't have much experience with VS. Any ideas for what is going wrong here?

**Comment by piiswrong** [comment]
I think you should put namespace after all includes

**Comment by alues** [comment]
@sbodenstein Any updates?

**Comment by sbodenstein** [comment]
@piiswrong: I put the namespaces before the includes so that everything was namespaced (it worked fine for Clang + GCC), which seemed safer.

However: I've done some tests, and moving the namespaces after the includes still fixes this problem. Training the speech_recognition example seems to work fine. So lets go with this for now.

**Comment by sbodenstein** [comment]
@alues: apologies, was away for the last few days. Should be working now (hopefully it passes all the tests so it can be merged).

**Comment by alues** [comment]
@sbodenstein thx a lot.

**Pull request merged**
