### PR TITLE
Add a ternary ndarray operator `fill_element_0index`

### PR DESCRIPTION
**Pull request by sxjscience**
Add  a ternary operator `fill_element_0index` , which fills the specific element in each line of the `lhs` according to the index in `rhs` and value in `mhs`.

The functionality inside `fill_element_0index` is implemented using the `MatFillRowElement` in this PR of mshadow https://github.com/dmlc/mshadow/pull/92

Also, revised a naming error in `test_ndarray.py`, which names `test_ndarray_onehot` as `test_ndarray_choose`.

### CODE REVIEW

**Comment by piiswrong** [comment]
How is this different from OneHotEncoding?

**Comment by sxjscience** [comment]
It can be seen as a generalized version of onehot_encoding
This operator does something like `new_arr[np.arange(shape[0]), indices] = val`.

**Comment by sxjscience** [comment]
@piiswrong I choose a ternary operation in order to infer the shape of the resulting matrix without adding other arguments in the mshadow side.
It'll be better to make it an inplace OP. Could you briefly tell how can I do that? I haven't found inplace OP example in https://mxnet.readthedocs.org/en/latest/python/ndarray.html .

**Comment by piiswrong** [comment]
You need to define a structure with a GetShape Method and pass it to DECL_BINARY. Please refer to ndarray_function.h:70-95

**Comment by sxjscience** [comment]
@piiswrong I've fixed the code.

**Comment by sxjscience** [comment]
@piiswrong Could this be merged?

**Comment by winstywang** [comment]
@piiswrong Is it OK to merge it in?

**Comment by winstywang** [comment]
@sxjscience Update and then merge

**Comment by sxjscience** [comment]
Check passed.

**Pull request merged**
