### PR TITLE
bug when renaming the lst file from im2rec.py in Windows

### PR DESCRIPTION
**Pull request by hoaphumanoid**
When computing im2rec.py in Windows you get the following error: 
```
os.rename(fname+'.tmp', fname)
WindowsError: [Error 183] Cannot create a file when that file already exists
```
Doesn't happen in Linux

### CODE REVIEW

**Comment by hoaphumanoid** [comment]
@piiswrong Why is this guy a float instead of an int??

`line += '%f\t' % j`

In the lst file I get a big number of 0s like: `1.00000000000`

**Comment by hoaphumanoid** [comment]
@piiswrong why you haven't merge?

**Comment by piiswrong** [comment]
This part has changed. You can try rebase to master

**Comment by hoaphumanoid** [comment]
Hi @piiswrong I checked again and the bug is still in master branch. You can not compute im2rec.py in windows with the current code you have. The fix I made solves the issue

**Pull request closed without merging**
