### PR TITLE
[OP] Move Elementwise binary scalar ops to SimpleOp Registry

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
cc @pluskid @javelinjs 

This PR cause a backward compatible break in symbolic API.

- Overload of scalar - symbol
    - ```_DivScalar(lhs, scalar_on_left=true)``` is changed to ```_RDivScalar```
- Same stands for ```_RPowerScalar```, ```_RMinusScalar```

I have updated the python API, but maybe changes in julia and scala is needed if you overloaded the operator. Since these symbols are not frequently used, I plan to merge this in when ok

**Comment by javelinjs** [comment]
I'll fix it this weekend.

**Comment by tqchen** [comment]
@javelinjs please do a PR to my repo so the things can be fixed when I merge this in.

@thirdwing can you also do so for the R testcase?

**Comment by thirdwing** [comment]
OK. I will do that tonight.

**Comment by tqchen** [comment]
@thirdwing @javelinjs any update on this?

**Comment by thirdwing** [comment]
Sorry for the late reply. Working on a conference paper. Will update this
soon.

On Sun, Apr 17, 2016 at 1:49 AM, Tianqi Chen <notifications@github.com>
wrote:

> @thirdwing <https://github.com/thirdwing> @javelinjs
> <https://github.com/javelinjs> any update on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/pull/1857#issuecomment-210960863>
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by pluskid** [comment]
I think it would be good to set a goal to introduce versioning into libmxnet. Then this kind of breaking changes will not be a disaster for other language bindings.

**Comment by tqchen** [comment]
agreed

**Comment by tqchen** [comment]
@thirdwing @pluskid @javelinjs this is now merged

**Comment by pluskid** [comment]
Thanks! I fixed the Julia side.

**Comment by javelinjs** [comment]
@tqchen Shall we also modify the divide and subtract function in python/mxnet/ndarray.py, as I mentioned in https://github.com/tqchen/mxnet/pull/1 ?

**Comment by tqchen** [comment]
@javelinjs I changed the convention back, and changed the scala version as well.

**Comment by javelinjs** [comment]
Oh, I see.

**Pull request merged**
