### PR TITLE
fix batchNorm cpp example

### PR DESCRIPTION
**Pull request by vsooda**

### CODE REVIEW

**Comment by piiswrong** [comment]
There are a few other places that calls bn

**Comment by vsooda** [comment]
in cpp-package/include/mxnet-cpp/symbol.h(hpp)

the construct function of Symbol is: 

```cpp
Symbol() {}

inline Symbol::Symbol(SymbolHandle handle) {
  blob_ptr_ = std::make_shared<SymBlob>(handle);
}
inline Symbol::Symbol(const char *name) {
  SymbolHandle handle;
  CHECK_EQ(MXSymbolCreateVariable(name, &(handle)), 0);
  blob_ptr_ = std::make_shared<SymBlob>(handle);
}
```

so if use the **original code**, 

```cpp
 Symbol bn = BatchNorm("bn_" + name + suffix, conv, Symbol(), Symbol(), Symbol(), Symbol());
```

the **blob_ptr_** is `NULL`,

then, in the call stack:

```cpp
Operator("BatchNorm")->SetInput("gamma", gamma)  
=> SetInput():   input_symbols_.push_back(symbol.GetHandle());
=> symbol.GetHandle() :   blob_ptr_->handle_; //error: blob_ptr_ is NULL 
```
runtime error occurs.

**Comment by vsooda** [comment]
I have not found other usage of BatchNorm in the cpp-package

**Comment by piiswrong** [comment]
ok. Thanks.

**Pull request merged**
