### PR TITLE
Cudnnv4 [No batch-norm]

### PR DESCRIPTION
**Pull request by antinucleon**

### CODE REVIEW

**Comment by piiswrong** [comment]
Maybe we should add a compiler flag for backward compatibility?
like USE_CUDNN_V4

**Comment by antinucleon** [comment]
How about use different branch, such as v3, v4?

**Comment by piiswrong** [comment]
Then the v3 branch will basically stop developing. Since v4 didn't change the interface much from v3, we can make it easier for people with a very low cost. I think it's worth it.

**Comment by piiswrong** [comment]
Or USE_CUDNN and USE_CUDNN_v3 and make v4 the default

**Comment by vchuravy** [comment]
I would prefer compile time flags, with CUDNNv4 being the default.

**Comment by antinucleon** [comment]
How about use branch first, then change to ENV some time later? At least we have something usable now

**Comment by mli** [comment]
we can detect cudnn version by `CUDNN_MAJOR`

see cudnn.h `#define CUDNN_MAJOR      3`

**Comment by piiswrong** [comment]
@mli This sounds like a good solution

**Comment by tqchen** [comment]
seems CUDNN_MAJOR is a good way to do so, let us stick with that

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/search?utf8=%E2%9C%93&q=CUDNN_VERSION_MIN

**Comment by tqchen** [comment]
@antinucleon can you check this PR and make updates to merge it in?

**Comment by yajiedesign** [comment]
i am pr https://github.com/dmlc/mxnet/pull/974

**Comment by antinucleon** [comment]
Close for Auto Switch PR

**Pull request closed without merging**
