### PR TITLE
Update rcnn example with accleration, module, resnet, coco and nnvm

### PR DESCRIPTION
**Pull request by precedenceguo**
Issue #4713 collected all current issues with rcnn example. This pr is tested on MXNet Jan.12 (a week ago). All VOC experiments have been verified and reported using MXNet-v0.9.1. I don't think there is any need to verify the 12 commits added since last week.

With this pr:
1. training and testing speed is accelerated.
2. module testing replaced executor.reshape.
3. added resnet support.
4. added coco dataset, where the performance with resnet will be tuned in the future.
5. minor adjustments for nnvm.
6. solved many issues collected.

Relationship with past pr on rcnn example:
(in short, I have included or used equivalent implementation)
#3173: wont fix, because numpy 1.8.2+ supports blank indexing, i.e. a[b] where b = []
#3327: changes are equivalent.
example/rcnn/demo.py: load_param returns num_class. changed to config controlled behavior.
example/rcnn/helper/processing/bbox_transform.py: clip is not necessary to stablize training.
#3495: windows string template support, included
executor.reshape, ignored (replaced by module.predict)
symbol BlockGrad, included
remove warmup scheduler, ignored because it is not necessary at first.
#3641: remove an argument, ignored (not necessary)
#4136: install monitor, included
#4221: ignored, need more experiments on zfnet to merge

Remaining issues:
(all of the following will not work in v0.8 either)
1. Python3/Windows environment unknown
2. No mx.image usage
3. 4G memory for VGG. py-faster-rcnn(caffe) uses 3G. May have to solve it later.

All in all:
At least everything works if they worked before.

### CODE REVIEW

**Comment by sxjscience** [comment]
What's the major reason python3/windows are not supported? nms?

**Comment by precedenceguo** [comment]
Actually I don't know. There is actually nothing binded to python2 or ubuntu.

**Comment by piiswrong** [comment]
LGTM

Suggestion for future reference: tried IndexedRecordIO instead of IMDB. IMDB has weird performance issue sometimes.

**Comment by piiswrong** [comment]
@zhreshold @precedenceguo @andreaolgiati @howard0su 
Should we start making an unified detection data pipeline?

**Comment by zhreshold** [comment]
@piiswrong  Do you have a plan? I think we could start with image.ImageIter and image.CreateAugmenter

**Comment by precedenceguo** [comment]
You might want to do that earlier because I have not built an operator for label transform (like assign anchor, bounding box regression) yet. Faster R-CNN needs a portion of SSD io (i.e. without image augmentation).

**Pull request merged**
