### PR TITLE
More imperative friendly high level model API (modules)

### PR DESCRIPTION
**Pull request by pluskid**
This is a work-in-progress attempt to refactor the current high-level model API. Because the refactoring is major, to avoid breaking existing code, I started a different set of API. The main component is `Module`, which looks very similar to Torch's modules. We will have both intermediate-level API like `forward`, `backward` on modules, as well as high-level API like `fit`, `score`. The end goal is to allow the modules to be easily composed with high-level imperative API.

TODOs:

- [x] intermediate-level API `forward`, `backward`, `update`, etc.
- [x] high-level API `fit`, `predict`, `score`
- [x] running example, MNIST & CIFAR-10
- [x] `BucketingModule` and ptb example
- [x] model saving and loading
- [ ] ~~`SequentialModule`: a container that connect multiple `Module`s sequentially~~
    - will come in another PR
- [x] comments and docs

### CODE REVIEW

**Comment by piiswrong** [comment]
This sounds more like container than modules?

**Comment by pluskid** [comment]
@piiswrong Yes. A module is (essentially the same as `FeedForward`) like a container a symbol, considered a huge operator, that could be manipulated easily with imperative API. Ideally we will have other container modules that could compose other modules using imperative API. This is useful, for example, for implementing back-prop through time.

**Comment by tqchen** [comment]
- If some of the states are exclusive to each other, maybe consider using enum style as opposed to indicator bools

**Comment by tqchen** [comment]
One thing we did not consider carefully before is how to use metrics for multiple outputs. 
- For RNN cases, the metrics need to be summed up
- For multiple output nets, maybe separate  is needed? or a customization is needed for the metric of multiple outputs.

**Comment by pluskid** [comment]
@tqchen Only three states are related. `binded`, `param_initialized` and `optimizer_initialized`. They are kind of stages. For example, parameters cannot be initialized before executors are binded. Maybe enums could be used, but I am not sure if it could simplify.

Yes metrics should also be updated. Ideally user should write metric for the specific task, as it is usually simple Python code. But maybe allowing the metric to access more information (e.g. bucket key) might help its implementation.

**Comment by tqchen** [comment]
- As long as we have a clear instruction on how to define metric, it is fine.
- Use enum can avoid possible bad state (e.g. binded=False and initialized=True). Apart from that, it is OK to use the bools

**Comment by pluskid** [comment]
Now all the three example runs (mnist, cifar, lstm). Basically now `Module` serves as a drop-in replacement of `FeedForward`. Except its internal is re-factored, so for example, now `BucketingModule` can utilize `score`, `prediction`, etc. automatically.

One important thing that I left out is distributed training. Because I do not have environment to test, I'm postponing this. Or maybe @mli could add the functionality later on. But I am expecting the old `FeedForward` module to co-exist for a long time. So should not be a big problem for now.

Original plan was to add a stochastic depth example with this. But it seems weights-copying might be a better way, as was suggested at GTC.

**Comment by mli** [comment]
great work, thanks! a naive question: will it be easy to get module to implement 

- model parallelism for multiple gpu in a single machine 
- data parallelism over multiple machines with model parallelism in a single machine.

**Comment by pluskid** [comment]
@mli it depends on how do you want to implement it. If you want to use symbolic API, then it is the same as before (as @tqchen 's example shows, we use attributes to hint which part should be computed on which gpu). What module api makes it easier is imperative api. For example, (after we add some sequential container module) we can define two parts of the network directly as two different symbols and the container will be able to chain the two modules, so model parallel is implemented.

In general imperative API will be slightly less efficient because memory optimization can only be carried within one atomic module. And there will be state copying cost. But I guess for model parallel those cannot be avoided even with pure symbolic API.

**Comment by terrytangyuan** [comment]
Probably should've squashed this...

**Comment by pluskid** [comment]
Good idea, I guess that makes the history cleaner.

**Comment by tqchen** [comment]
Let us keep things as it is as it is already merged in and it could be a bad idea to squash things in the main repo. Just keep things in mind next time

**Pull request merged**
