### PR TITLE
[WIP / RFC] numeric gradient for testing

### PR DESCRIPTION
**Pull request by lukemetz**
Pull request includes a few things needed to create numeric gradient test function.
Not sure this is something that is wanted or needed but I find it quite useful at-least in Theano to ensure that ops are doing what one expects them to be doing.

It includes
* SumAll Op, that sums a tensor.
* Loss Op that converts a Symbol to a output / loss symbol.
* actual numeric grad testing code.

### CODE REVIEW

**Comment by piiswrong** [comment]
Hi @lukemetz,
Thanks for the contribution. This is definitely a useful feature. Just two comments:
1) I would recommend remove loss_op and sum_all_op and implement those functions in python with imperative operations, e.g. x.asnumpy().sum(). And add a python class GradientChecker.
2) Your doesn't seem to build under linux.

**Comment by lukemetz** [comment]
1) Will do. What is the logic for which ops to drop down to cpp? 
Also, Should GradientChecker be in the test module or the mxnet module? 
2) ya. sorry about that. One to many late night changes...

**Comment by piiswrong** [comment]
I think the logic is:
a) generic ops useful for many tasks, or
b) performance critical.
Gradient checker doesn't really justify b) since you only run it once for each op.
loss_op doesn't justify a) either. Sum_all op however, does fit in a). But you actually can implement it with much less code by using src/ndarray/ndarray_function.
Some thing like this:
MXNET_REGISTER_TBLOB_FUN(square, XPU)
.set_function(XPU::kDevMask, UnaryForward_<XPU, op::mshadow_op::square>, true)
.set_gradient(XPU::kDevMask, UnaryBackwardUseIn_<XPU, op::mshadow_op::square_grad>, true)
.describe("Take square of the src");

**Comment by tqchen** [comment]
Sumall should go to https://github.com/dmlc/mxnet/blob/master/src/ndarray/unary_function-inl.h 

Reference the implementation of norm. I am a bit sorry for the confusion in code locations, in a sense that they should be moved to op and more highlighted, this file is the place to implement the Unary operator easily and being exposed to both NDArray and symbolic api.

Thanks for the contribution!

**Comment by lukemetz** [comment]
Deleted all of the cpp code infavor of a NumpyOp. This will work perfectly fine for tests but will not scale as talked about. I figured this was way less code as this SumAll would need to be converted to a "loss" op anyway.

Sorry for all the questions, but one more thing: What exactly do you mean by a GradientChecker class? The function itself is stateless so what would go in this class? Utilities to check relative / absolute error like in [theano](https://github.com/Theano/Theano/blob/master/theano/gradient.py#L1353)?

**Comment by tqchen** [comment]
Looks nice, @piiswrong can you do another round of review and merge it in? Also cc @sneakerkg who did gradient checker before

**Pull request merged**
