### PR TITLE
create squeezenet

### PR DESCRIPTION
**Pull request by qiaohaijun**

### CODE REVIEW

**Comment by qiaohaijun** [comment]
Top1 result:
Epoch[0] Validation-accuracy=0.022162
Epoch[1] Validation-accuracy=0.077706
Epoch[2] Validation-accuracy=0.159512
Epoch[3] Validation-accuracy=0.214047
Epoch[4] Validation-accuracy=0.254604
Epoch[5] Validation-accuracy=0.286223
Epoch[6] Validation-accuracy=0.322604
Epoch[7] Validation-accuracy=0.340362
Epoch[8] Validation-accuracy=0.353355
Epoch[9] Validation-accuracy=0.377770
Epoch[10] Validation-accuracy=0.383929
Epoch[11] Validation-accuracy=0.395719
Epoch[12] Validation-accuracy=0.407187
Epoch[13] Validation-accuracy=0.422513
Epoch[14] Validation-accuracy=0.411445
Epoch[15] Validation-accuracy=0.429787
Epoch[16] Validation-accuracy=0.440171
Epoch[17] Validation-accuracy=0.448293
Epoch[18] Validation-accuracy=0.450375
Epoch[19] Validation-accuracy=0.463289
Epoch[20] Validation-accuracy=0.460333
Epoch[21] Validation-accuracy=0.467395
Epoch[22] Validation-accuracy=0.468770
Epoch[23] Validation-accuracy=0.473502

**Comment by qiaohaijun** [comment]
Top5 result
Epoch[0] Validation-top_k_accuracy_5=0.078205
Epoch[1] Validation-top_k_accuracy_5=0.207151
Epoch[2] Validation-top_k_accuracy_5=0.354402
Epoch[3] Validation-top_k_accuracy_5=0.433394
Epoch[4] Validation-top_k_accuracy_5=0.484714
Epoch[5] Validation-top_k_accuracy_5=0.524042
Epoch[6] Validation-top_k_accuracy_5=0.568060
Epoch[7] Validation-top_k_accuracy_5=0.586814
Epoch[8] Validation-top_k_accuracy_5=0.602932
Epoch[9] Validation-top_k_accuracy_5=0.627730
Epoch[10] Validation-top_k_accuracy_5=0.636201
Epoch[11] Validation-top_k_accuracy_5=0.644149
Epoch[12] Validation-top_k_accuracy_5=0.656270
Epoch[13] Validation-top_k_accuracy_5=0.666474
Epoch[14] Validation-top_k_accuracy_5=0.660881
Epoch[15] Validation-top_k_accuracy_5=0.679548
Epoch[16] Validation-top_k_accuracy_5=0.691067
Epoch[17] Validation-top_k_accuracy_5=0.695876
Epoch[18] Validation-top_k_accuracy_5=0.699000
Epoch[19] Validation-top_k_accuracy_5=0.710499
Epoch[20] Validation-top_k_accuracy_5=0.709810
Epoch[21] Validation-top_k_accuracy_5=0.711854
Epoch[22] Validation-top_k_accuracy_5=0.714525
Epoch[23] Validation-top_k_accuracy_5=0.718730

**Comment by qiaohaijun** [comment]
train scripts:
``` bash

python train_imagenet.py \
  --batch-size  512 \
  --lr 0.04 \
  --lr-factor .94  \
  --gpus 0,1,2,3 \
  --num-epoch 1000 \
  --network squeezenet \
  --model-prefix model/squeezenet \
  --data-dir /search/data/1k/20160704/ \
  --train-dataset train_1k_256.rec \
  --val-dataset val_1k_256.rec \
  --data-shape 227 \
  --log-dir /search/data/user/logs/ \
  --log-file squeezenet-1m-20160707.log
```

**Comment by piiswrong** [comment]
Thanks. Could you put the results in the code header?

**Comment by qiaohaijun** [comment]
@piiswrong I will train it longer

**Pull request closed without merging**
