### PR TITLE
add round ceil floor

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Comment by piiswrong** [comment]
I'm not sure how gradients should be computed for these functions. Do you have reference?

**Comment by yajiedesign** [comment]
@piiswrong  i am find reference 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L441

**Comment by piiswrong** [comment]
I'm still not sure about this, but since tensorflow is doing the same thing, maybe we can merge is first. @tqchen what do you think?

**Comment by tqchen** [comment]
Identity should be OK approximately as they are functions. I can hardly imagine things like ciel and floor can have a gradient. I guess alternatively we should not register the gradient, and leave them empty

**Comment by tqchen** [comment]
So gradient is not defined for these functions

**Comment by yajiedesign** [comment]
@tqchen  I tried not to register the gradient function, but could not pass the test.

**Comment by tqchen** [comment]
You need to remove the gradient(backward test), since gradient is not available

**Comment by yajiedesign** [comment]
I removed the gradient function, but I'm afraid it can't work well with other ops..

**Comment by tqchen** [comment]
Thanks, this is merged. I can hardly imagine how can gradient can be taken on these functions, the identity could only mean an approximate version of such gradient. We can always add it back when it is needed :)

**Comment by vchuravy** [comment]
Since `floor` and `ceil`are piecewise functions they should differentiate to 0 if the numer is *not* and integer and the derivative is undefined for integers (because of the discontinuity). http://www.wolframalpha.com/input/?i=gradient+of+floor%28x%29 

If such a gradient would be helpful is another question.

**Pull request merged**
