### PR TITLE
Add install btn

### PR DESCRIPTION
**Pull request by kevinthesun**
1. Change 'Get Started' tab to 'Install'
2. Add 'Install' Button

addinstallbtn2

### CODE REVIEW

**Comment by piiswrong** [comment]
`why mxnet` -> `Learn More`?

**Comment by zackchase** [comment]
The spacing looks problematic. Star and Fork and the two buttons are not centered / aligned. Also can we do something to make the buttons more stylish? See Pytorch for an example of sexier button.

Also I just noticed that the very title of our page ("Flexible and Efficient Library for Deep Learning") is wrong. Should be: "A Flexible and Efficient Library for Deep Learning"

**Comment by kevinthesun** [comment]
For the star and folk button, sometimes the numbers behind them are not shown. Actually they are centered.

**Comment by piiswrong** [comment]
This star button actually doesn't work. It only points to github front page.
Maybe we should replace star and fork with a standard "fork me on github" ribbon

**Pull request merged**
