### PR TITLE
Add RMSProp optimizer in R

### PR DESCRIPTION
**Pull request by ziyeqinghan**
Add RMSProp optimizer in R and test it  in [mnist classification](https://github.com/dmlc/mxnet/tree/master/example/image-classification) with parameters `learning.rate=0.002`, `optimizer="rmsprop"`. Part of the test result is:
```
Batch [50] Train-accuracy=0.1125
Batch [100] Train-accuracy=0.335234375
...
Batch [450] Train-accuracy=0.783871527777778
[1] Train-accuracy=0.789848768736617
[1] Validation-accuracy=0.939102564102564
Batch [50] Train-accuracy=0.95375
...
[3] Train-accuracy=0.970302483974359
[3] Validation-accuracy=0.965845352564103
Batch [50] Train-accuracy=0.97203125                                                                                                                                                              [462/523]
...
[5] Train-accuracy=0.979767628205128
[5] Validation-accuracy=0.96875
...
[9] Train-accuracy=0.985259748931624
[9] Validation-accuracy=0.977664262820513
...
[10] Train-accuracy=0.986328125
[10] Validation-accuracy=0.975460737179487
```

### CODE REVIEW

**Comment by thirdwing** [comment]
LGTM.

Please also take a look @terrytangyuan

**Comment by terrytangyuan** [comment]
Looks good! Please rebase and we'll merge.

**Comment by ziyeqinghan** [comment]
The branch is rebased.

**Comment by terrytangyuan** [comment]
@tqchen Could you pick this commit? Any idea why it's so easy to be out-of-date?

**Comment by ziyeqinghan** [comment]
The branch is rebased again. :)

**Comment by terrytangyuan** [comment]
@ziyeqinghan Thanks!

**Pull request merged**
