### PR TITLE
Fix RCNN pascal evaluations for float bboxes and empty classes.

### PR DESCRIPTION
**Pull request by krosaen**
A couple of small fixes:

1. Allow for floating point bounding box predictions when reading in evaluations. The provided `test_rcnn` function outputs results as floats (perhaps only when evaluating on VOC-like datasets with different image dimensions?)
2. Allow for zero detections of some classes during evaluation. This is handy when evaluating on another dataset in VOC-like format with a subset of the original VOC classes.

These fixes have been necessary when training and evaluating on non-VOC datasets in VOC format as described [here](https://github.com/umautobots/nn-dockerfiles/tree/master/mxnet-rcnn).

### CODE REVIEW

**Comment by piiswrong** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
The proposed change will not influence current results. It will fix issues as you proposed.

**Comment by krosaen** [comment]
@precedenceguo I'm not sure I understand: is it that this doesn't fix any issues with the example if run verbatim? That's true, but the code as it stands is pretty brittle, why not allow it to work with very similar examples if others wish to train on other datasets that adhere to VOC format? We cite MXNet in [soon to be published research](https://arxiv.org/abs/1610.01983) and we are hoping to make our work as reproducible as possible.

**Comment by precedenceguo** [comment]
Thank you for making it more flexible and robust. What I meant was that this change would not impact any existing results (so we wouldn't need to verify them again) and that this change will fix the issues you mentioned.

**Comment by krosaen** [comment]
Oh, I misinterpreted your original comment thinking you were suggesting this change not be merged, sorry about that. I appreciate you taking a look.

**Pull request merged**
