### PR TITLE
Add epoch_metric_callback to Module.fit to easily monitor model conve…

### PR DESCRIPTION
**Pull request by larroy**
…rgence

### CODE REVIEW

**Comment by piiswrong** [comment]
You can move epoch end callback to after eval_data then do something like this:
metric = ...
val_metric = ...
def callback(...):
    metric.get()
    val_metrci.get()

module.fit(metric, val_metric, epoch end callback=callback)

**Comment by larroy** [comment]
@piiswrong I don't get your comment. You want epoch_metric_callback to moved to after eval_data so it's next to the other callbacks? I put it last so it doesn't break compatibility to usages of positional parameters to fit

**Comment by piiswrong** [comment]
I meant you don't need to add an additional argument to fit to do this. You can write a callback that is a closure wrapping around eval_metric and val_metric

**Comment by larroy** [comment]
@piiswrong is not really comfortable, which callback do you suggest to use? As far as I know, no callback presents both losses in a convenient way, it's very convoluted to get them otherwise. Right now the alternative is:
```
    "def eval_end_callback(batchEndParam):\n",
    "    meas = list(batchEndParam.eval_metric.get_name_value())[0][1]\n",
    "    epoch = batchEndParam.epoch\n",
    "    logging.info(\"Eval --- END --- callback {}\".format(meas))\n",
    "    valAccuracy.append((epoch,meas))\n",
    "\n",
    "def batch_end_callback(batchEndParam):\n",
    "    meas = list(batchEndParam.eval_metric.get_name_value())[0][1]\n",
    "    epoch = batchEndParam.epoch\n",
    "    logging.info(\"{}\".format(meas))\n",
    "    if trainAccuracy:\n",
    "        if trainAccuracy[-1][0] != epoch:\n",
    "            trainAccuracy.append((epoch,meas))\n",
    "        else:\n",
    "            trainAccuracy[-1] = (epoch, meas)\n",
    "    else:\n",
    "        trainAccuracy.append((epoch,meas))


```

**Comment by larroy** [comment]
@piiswrong ping, shall we discard this PR or are there some changes that could get it merged? I think it would be useful to have it.

**Comment by mli** [comment]
I'm going to close the PR since there is no activity for more than 2 months. But please feel free to re-open it and update with the master.

**Pull request closed without merging**
