### PR TITLE
add data_callback for image data preprocessing

### PR DESCRIPTION
**Pull request by clcarwin**
Local Contrast Normalization or other algorithm can be implemented by passing data_callback to mx.io.ImageRecordIter

### CODE REVIEW

**Comment by tqchen** [comment]
I think a better approach could be add a process iterator that takes the callback, and chains with the ImageRecordIter.

So it won't affect the current ImageRecordIter explicitly

**Comment by clcarwin** [comment]
Hi Tianqi,
    How to code with the process iterator? Can you share some code gist?

    The multi-label regression result can be improved significantly by
Local Contrast Normalization. Can we add a new parameter to ImageRecordIter
"lcn(boolean, optional, default=False)"?


Thanks

**Comment by tqchen** [comment]
Basically, create another DataIter, that takes a ImageRecordIter, and runs the preprocessing function you suggested.


``` python
class ProcessIter(DataIter):
    def __init__(self, base, proc_func):
        self.base = base
        self.proc_func = proc_func
    
   def next():
       return self.proc_func(base.next())     

```

**Comment by tqchen** [comment]
Here base is ImageRecordIter

**Comment by clcarwin** [comment]
Thanks!

**Pull request closed without merging**
