### PR TITLE
fix dtype of workspace in cudnn convolution

### PR DESCRIPTION
**Pull request by vchuravy**
I think that was just a small oversight?

### CODE REVIEW

**Comment by vchuravy** [comment]
Hm, Why is github considering branches so often out of data with master. This is a very simple and clean merge with the current master. 

I think the problem is the protected branch feature from github [1], which is encouraging merging master onto the branch before merging this branch back. I feel this clutters the commit history, so I perform a manual rebase locally and then force push. But then I have to race the clock and I have to do it several times until the PR is merged, even if every rebase is clean.

@tqchen @piiswrong Could we maybe set the required status set to `Loose` after [2] to reduce friction?

[1] https://github.com/blog/2051-protected-branches-and-required-status-checks
[2] https://help.github.com/articles/types-of-required-status-checks/

**Comment by piiswrong** [comment]
The problem with that is it can break the master. Since we don't have a dev  branch it can be very bad

**Comment by piiswrong** [comment]
It wouldn't have been so annoying if we had a faster test server...

**Comment by vchuravy** [comment]
One possibility would be to use gerrit. Pull request are rebased onto master and it enforces a stronger review culture. But that is coming from my point of view, where I find merge-commit really annoying and I prefer a linear code history to make `git bisect` work well. 

https://gist.github.com/mbbx6spp/70fd2d6bf113b87c2719

**Comment by vchuravy** [comment]
@piiswrong Is this good to merge? If so I can rebase for merging.

**Comment by piiswrong** [comment]
@tqchen Good for merge

**Comment by vchuravy** [comment]
rebased.

**Comment by piiswrong** [comment]
@tqchen plz merge this

**Pull request merged**
