### PR TITLE
Update README with Apache mailing list and Slack channel

### PR DESCRIPTION
**Pull request by dleen**

### CODE REVIEW

**Comment by piiswrong** [comment]
Please move this to the top and replace the current gitter.
there are 3 apache email lists. We should list them all and provide concise descriptions of each.

sending email for joining the slack doesn't look scalable.

**Comment by dleen** [comment]
@piiswrong Hi Eric, I have moved it to the top and removed the gitter. I agree the email is not scalable. Dominic is working on it. 

I see 2 email addresses here: http://incubator.apache.org/projects/mxnet.html I am not sure what the third one is and I don't know what commits@ is. So not sure how to describe them.

**Comment by piiswrong** [comment]
Should we merge this in now? Or wait after things are sorted out?

We should 2 other mailing lists:
announcements: for infrequent big announcements
user: for user q&a

**Comment by domdivakaruni** [comment]
@hyandell can you tell us what the other mailing list addresses are for Apache MXNet (for small and big announcements)?
@piiswrong @dleen On Slack dont post my email. let me talk to the ASF guys on Tuesday and apache con and report back

**Comment by mli** [comment]
I'm going to close the PR since there is no activity for more than 2 months. But please feel free to re-open it and update with the master.

**Pull request closed without merging**
