### PR TITLE
Enable testing of the Julia bindings

### PR DESCRIPTION
**Pull request by vchuravy**
Currently only the R and Python bindings are tested and it is possible that changes to upstream mxnet could break the Julia bindings. 

@pluskid

### CODE REVIEW

**Comment by pluskid** [comment]
Thanks a lot! I think this makes a lot of sense, though Travis CI time is further elongated.

**Comment by pluskid** [comment]
I see no objection from other developer. @vchuravy Can you do a rebase so that we can merge? Thanks!

**Comment by vchuravy** [comment]
rebased

**Comment by vchuravy** [comment]
There seems to be a time-out in the cpp_tests

**Comment by pluskid** [comment]
Yes it looks strange. Unfortunately it is configured to disallow PR merging unless the travis CI says OK. Can you do some trivial change to trigger the travis CI again?

**Comment by vchuravy** [comment]
rerun tests, all green now

**Comment by pluskid** [comment]
Hmm, it seems the C++ test somehow still time out. And the Julia test is failing.

**Comment by javelinjs** [comment]
@pluskid Hi Kid, collaborator should be able to rerun the test through the travis webpage

**Comment by pluskid** [comment]
@javelinjs Ah! I see. That is much better! Thanks! :)

**Comment by mli** [comment]
Can one of the admins verify this patch?

**Comment by pluskid** [comment]
I'm re-running the travis CI to see what happens.

**Comment by pluskid** [comment]
@vchuravy There were seg-faults in the Julia testing. This is due to an upstream change in the C-API functions. I have updated the Julia code to adapt this change. I will make a new release of the Julia package soon.

**Comment by vchuravy** [comment]
This is running using the master branch of Julia.

**Pull request merged**
