### PR TITLE
don't intermingle type switch and preprocessing directives in deconvolution.cu

### LINKED ISSUE #2384: compilation error deconvolution.cu
```
Error	41	error : "#" not expected here	C:\Users\chuaf\Downloads\mxnet\src\operator\deconvolution.cu	18	1	mxnet
Error	47	error : expected a ";"	C:\Users\chuaf\Downloads\mxnet\src\operator\deconvolution.cu	18	1	mxnet
Error	44	error : expected an expression	C:\Users\chuaf\Downloads\mxnet\src\operator\deconvolution.cu	18	1	mxnet
```

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #2384 

@freddycct could you tests this? I don't have a windows machine available.

### CODE REVIEW

**Comment by freddycct** [comment]
how do I test ??

**Comment by vchuravy** [comment]
Since the changes are on a different fork the easiest is probably:

```bash
git remote add oist https://github.com/oist/mxnet.git
git fetch oist
git checkout vc/deconv_compileerror
```

**Comment by freddycct** [comment]
ok, compiled successfully. thanks

**Comment by vchuravy** [comment]
Good. Thank you for testing and sorry for breaking the build with your compiler.

@tqchen @piiswrong Please merge at your convenience

**Comment by sxjscience** [comment]
I've also verified the compilation. @vchuravy Merge from master and rebase?

**Pull request merged**
