### PR TITLE
[Operator] Bilinear upsamping

### PR DESCRIPTION
**Pull request by antinucleon**
@piiswrong @winstywang Init is not implemented and not test yet, seems don't need concat

### CODE REVIEW

**Comment by piiswrong** [comment]
what do you mean dont need concat? does this handle multiple input without duplicating memory?

**Comment by antinucleon** [comment]
After init the bilinear weight with
```
weight = np.zeros(np.prod(shape))
f = shape[3] / 2.
c = (2 * f - 1 - f % 2) / (2. * f)
for i in range(np.prod(shape)):
    x = i % shape[3]
    y = (i / shape[3]) % shape[2]
    weight[i] = (1 - abs(x / f - c)) * (1 - abs(y / f - c));
```
the result is:

original image:
original


nearest result:
nearest


bilinear result:
bilinear

**Comment by antinucleon** [comment]
@piiswrong I have finished bilinear upsampling. For hypercolumn or concat, I am not very clear about these and feel free to refactor for your purpose.

**Comment by piiswrong** [comment]
I think it's easy to do for nearest neighbor. I'll do it after you merge this.

**Comment by piiswrong** [comment]
What happened to travis lint? Did the rule set change?

**Comment by antinucleon** [comment]
https://travis-ci.org/dmlc/mxnet/jobs/93842415 ,seems are errors with numpy and some more strict rules.

**Comment by antinucleon** [comment]
Right

**Pull request merged**
