### PR TITLE
OnlyImplementedInNDArray

### PR DESCRIPTION
**Pull request by szha**
@piiswrong

### CODE REVIEW

**Comment by piiswrong** [comment]
What does the error look like?

**Comment by szha** [comment]
```
In [1]: import mxnet as mx

In [2]: a = mx.sym.var('a')

In [3]: a += 3
---------------------------------------------------------------------------
OnlyImplementedInNDArray                  Traceback (most recent call last)
<ipython-input-3-dced8f4de5c5> in <module>()
----> 1 a += 3

/Users/zhasheng/mxnet/python/mxnet/symbol.py in __iadd__(self, other)
     96
     97     def __iadd__(self, other):
---> 98         raise OnlyImplementedInNDArray(self.__iadd__, other)
     99
    100     def __radd__(self, other):

OnlyImplementedInNDArray: (<bound method Symbol.__iadd__ of <Symbol a>>, 3)
```

**Comment by piiswrong** [comment]
This looks cryptic. It should be human readable text

**Comment by mli** [comment]
may just print `self.__name__`

**Comment by szha** [comment]
Does this look better?
```
In [1]: import mxnet as mx

In [2]: a = mx.sym.var('a')

In [3]: a += 3
---------------------------------------------------------------------------
OnlyImplementedInNDArray                  Traceback (most recent call last)
<ipython-input-3-dced8f4de5c5> in <module>()
----> 1 a += 3

/Users/zhasheng/mxnet/python/mxnet/symbol.pyc in __iadd__(self, other)
     96
     97     def __iadd__(self, other):
---> 98         raise OnlyImplementedInNDArray(self.__iadd__, other)
     99
    100     def __radd__(self, other):

OnlyImplementedInNDArray: __iadd__, <type 'int'>
```

**Comment by piiswrong** [comment]
Rename the error to NotImplementedForSymbol.
Add some text explain it.
xxx function/+= operator is not implemented for Symbol and only available in NDArray

**Comment by szha** [comment]
Now looks like:
```
In [1]: import mxnet as mx; a=mx.sym.var('a'); a+=1
---------------------------------------------------------------------------
NotImplementedForSymbol                   Traceback (most recent call last)
<ipython-input-1-6fe2e910ee4b> in <module>()
----> 1 import mxnet as mx; a=mx.sym.var('a'); a+=1

/Users/zhasheng/mxnet/python/mxnet/symbol.py in __iadd__(self, other)
     96
     97     def __iadd__(self, other):
---> 98         raise NotImplementedForSymbol(self.__iadd__, '+=', other, 1)
     99
    100     def __radd__(self, other):

NotImplementedForSymbol: Function __iadd__ (namely operator +=) with arguments (<type 'int'>, <type 'int'>) is not implemented for Symbol and only available in NDArray.
```

**Comment by haoliyoupai09** [comment]
raise NotImplementedForSymbol(self.iadd, '+=', other, 1)
mxnet.base.NotImplementedForSymbol: Function iadd (namely operator "+=") with arguments (<class 'mxnet.symbol.symbol.Symbol'>, <type 'int'>) is not implemented for Symbol and only available in NDArray.

When I compile a project using mxnet, I met the error like this. The mxnet is complied successfully and import mxnet in python is also right. Could you tell me what to do?

**Comment by szha** [comment]
The error message you got is accurate in that the in-place add is indeed not available in symbol. Instead of doing `sym_a += sym_b`, you can do `sym_a = sym_a + sym_b`.

**Comment by haoliyoupai09** [comment]
That helps, thanks a lot.

**Pull request merged**
