### PR TITLE
Add function 'print_summary' and some revise

### PR DESCRIPTION
**Pull request by Trangle**
Add function 'print_summary' for print detail information of network, and format argument was add in 'plot_network'.
You can use 'print_summary' like:
"""
net = get_symbol(1000)
shape = {'softmax_label': (64, 1000), 'data': (64, 3, 224, 224)}
mx.viz.print_summary(net, shape=shape)
"""
If without shape, the number of arguments would be nonsense currently.

### CODE REVIEW

**Comment by pluskid** [comment]
LGTM. Can you update the branch?

**Comment by Trangle** [comment]
@pluskid OK.

**Comment by pluskid** [comment]
hmm..., it seems to be out-of-date again. Can you update again?

**Comment by Trangle** [comment]
@pluskid don't know why this out of date so fast...

**Pull request merged**
