### PR TITLE
batchnorm gradient test

### PR DESCRIPTION
**Pull request by lukemetz**
I was curious about #1053 so I wrote a test for it. All seems to be good except for a little weirdness around `fixed_gamma = True`. The gradient appears to only be correct if gamma is set to 1 (I think. Its hard to tell 100% if I am messing something else up). I took a look in the cpp code and this assumption seems to be reflected there. This to me seems like a bug to me but I am not sure what the correct behaviour is.

### CODE REVIEW

**Comment by winstywang** [comment]
Fix gamma means set gamma=1. This is the expected behavior.

**Comment by winstywang** [comment]
Could you please rebase it so that I can merge in?

**Comment by lukemetz** [comment]
Updated @winstywang. Thank you.

**Comment by tqchen** [comment]
Thanks for the great job!

**Comment by jimxinbo** [comment]
Great job!. Seems the ICML version of BN overlooked the second term of delta_mu. Thank you.

**Pull request merged**
