### PR TITLE
add Adamax & Nadam

### PR DESCRIPTION
**Pull request by CNevd**
1. fix Ftrl
2. add Adamax and Nadam
@piiswrong @sxjscience

### CODE REVIEW

**Comment by sxjscience** [comment]
Working on the CIKM AnalytiCup competition these weeks. @szhengac @leezu could you help check the implementation?

**Comment by piiswrong** [comment]
Please fix lint.
don't override abs, rename it

**Comment by CNevd** [comment]
@piiswrong done

**Comment by piiswrong** [comment]
Thanks.

Can someone check the implementation against the papers?
@leezu @szhengac

**Comment by leezu** [comment]
@piiswrong @sxjscience Adamax implemention seems correct to me. Instead of introducing a new Adamax optimizer one could also add a new `norm` argument to the Adam optimizer (`norm=2` being the default and `norm=max` leading to Adamax). Independently from this suggestion, the Adamax logic could be implemented on the C++ side in [AdamUpdate](https://github.com/dmlc/mxnet/blob/e4c7bfc/src/operator/optimizer_op-inl.h#L297) so that Adamax can be shared with the other language bindings.
But this can also be addressed in a later pull request.

I'll check Nadam later today.

**Comment by leezu** [comment]
@CNevd for Nadam you seem to assume that `\hat g = g, \hat m = m, \hat n = n`. Can you clarify why you do this? Comparing to Algorithm 8 from the paper it seems wrong?

**Comment by CNevd** [comment]
@leezu we implement nadam assume that u^t and v^t is small as nadam_optimizer.py[https://github.com/tensorflow/tensorflow/blob/03beb65cecbc1e49ea477bca7f54543134b31d53/tensorflow/contrib/opt/python/training/nadam_optimizer.py] does or we can change it to Algorithm 8 from the paper just like keras-nadam[https://github.com/tensorflow/tensorflow/blob/cc8b0f7fa972b8b73f0178bcfdb94106ba894187/tensorflow/contrib/keras/python/keras/optimizers.py#L550]

**Comment by CNevd** [comment]
@leezu we implement nadam assume that u^t and v^t is small as [nadam_optimizer.py](https://github.com/tensorflow/tensorflow/blob/03beb65cecbc1e49ea477bca7f54543134b31d53/tensorflow/contrib/opt/python/training/nadam_optimizer.py) does or we can change it to Algorithm 8 from the paper just like [keras-nadam](https://github.com/tensorflow/tensorflow/blob/cc8b0f7fa972b8b73f0178bcfdb94106ba894187/tensorflow/contrib/keras/python/keras/optimizers.py#L550)

**Comment by leezu** [comment]
@CNevd let's wait for a comment from @piiswrong @sxjscience . If we choose to go with this assumption we should document it, as currently the docstring suggests that we follow the papers approach.

**Comment by piiswrong** [comment]
Let's stick with the paper. optimizations can be added as options

**Comment by CNevd** [comment]
@piiswrong @leezu update Nadam

**Comment by leezu** [comment]
@piiswrong Looks good to me. Thanks @CNevd

**Comment by sxjscience** [comment]
LGTM. I'll merge it.

**Pull request merged**
