### PR TITLE
initializer.py revised to allow any shape of NDArray and built-in cuDNN RNN operator example remove the LSTM_bias workaround naming

### PR DESCRIPTION
**Pull request by mz24cn**
bucket_io.py: revised to be compatible with python 3.x;
initializer.py: revised to support built-in RNN operator parameters,
which has only one shape dimension;
rnn_cell_demo.py: renames LSTM_bias workaround name with LSTM_parameters
and gains better convergence speed.

        # The original example, rnn_cell_demo.py, uses default Xavier as initalizer, 
        # which relies on variable name, cannot initialize LSTM_parameters. Thus it was
        # renamed to LSTM_bias, which can be initialized as zero. It weakens the converge
        # speed. Here I use revised initializer.py and introduce class RNNXavier to 
        # initialize LSTM_parameters. I attached the first epoch comparison:
        # The old LSTM_bias case:
	# 2017-01-28 01:56:19,164 Epoch[0] Batch [50]    Speed: 1081.03 samples/sec    Train-Perplexity=4506.515945
	# 2017-01-28 01:56:25,360 Epoch[0] Batch [100]    Speed: 1033.19 samples/sec    Train-Perplexity=797.195374
	# 2017-01-28 01:56:31,394 Epoch[0] Batch [150]    Speed: 1060.61 samples/sec    Train-Perplexity=569.822128
	# 2017-01-28 01:56:37,784 Epoch[0] Batch [200]    Speed: 1001.64 samples/sec    Train-Perplexity=469.483883
	# 2017-01-28 01:56:43,424 Epoch[0] Batch [250]    Speed: 1134.96 samples/sec    Train-Perplexity=341.282116
	# 2017-01-28 01:56:49,097 Epoch[0] Batch [300]    Speed: 1128.55 samples/sec    Train-Perplexity=327.141254
	# 2017-01-28 01:56:54,667 Epoch[0] Batch [350]    Speed: 1149.03 samples/sec    Train-Perplexity=321.201624
	# 2017-01-28 01:57:00,193 Epoch[0] Batch [400]    Speed: 1158.18 samples/sec    Train-Perplexity=293.513695
	# 2017-01-28 01:57:04,366 Epoch[0] Train-Perplexity=335.999086
	# 2017-01-28 01:57:04,366 Epoch[0] Time cost=51.624
	# 2017-01-28 01:57:07,082 Epoch[0] Validation-Perplexity=276.119522

		# The new LSTM_parameters case (based on RNNXavier and revised initializer.py):          
	# 2017-01-28 01:54:08,342 Epoch[0] Batch [50]    Speed: 1272.47 samples/sec    Train-Perplexity=3510.636976
	# 2017-01-28 01:54:14,230 Epoch[0] Batch [100]    Speed: 1087.30 samples/sec    Train-Perplexity=849.972727
	# 2017-01-28 01:54:20,326 Epoch[0] Batch [150]    Speed: 1049.99 samples/sec    Train-Perplexity=496.757170
	# 2017-01-28 01:54:25,690 Epoch[0] Batch [200]    Speed: 1193.19 samples/sec    Train-Perplexity=324.072778
	# 2017-01-28 01:54:31,388 Epoch[0] Batch [250]    Speed: 1123.19 samples/sec    Train-Perplexity=278.631529
	# 2017-01-28 01:54:37,856 Epoch[0] Batch [300]    Speed: 989.55 samples/sec    Train-Perplexity=271.496667
	# 2017-01-28 01:54:43,726 Epoch[0] Batch [350]    Speed: 1090.45 samples/sec    Train-Perplexity=210.853686
	# 2017-01-28 01:54:49,338 Epoch[0] Batch [400]    Speed: 1140.62 samples/sec    Train-Perplexity=198.847126
	# 2017-01-28 01:54:53,062 Epoch[0] Train-Perplexity=186.354118
	# 2017-01-28 01:54:53,063 Epoch[0] Time cost=50.277
	# 2017-01-28 01:54:55,770 Epoch[0] Validation-Perplexity=181.052411

### CODE REVIEW

**Comment by mz24cn** [comment]
C++ version: https://github.com/dmlc/MXNet.cpp/pull/67
mxnet.cpp's initializer.h also should be revised to support one dimension NDArray. Once this PR was accepted, I will revise the C++ version's initializer.h

**Comment by piiswrong** [comment]
See https://github.com/dmlc/mxnet/pull/4644

**Comment by mz24cn** [comment]
Hi, @piiswrong, previously I have seen "cuDNN RNN Cell parameter initialization"  #3573 and your alternative solution #4644. #4644 doesn't conflict with this PR and cannot substitute this one. 

This PR revised Xavier implementation, which can bee seen as 'fault-tolerant' for any NDArray shape. For one dimension shape (such as cuDNN parameters), the key is using sqrt to 'mimic' two dimension shape, which has been verified as an effective method by test.

#4644 proposes an initializer registeration mechanism to adapt with various situations, which is compatible with RNNXavier that I introduced in rnn_cell_demo.py. But #4644 itself cannot resolve the 'LSTM_bias' defect. I think you can accept this PR firstly, then merge #4644, after that I can revise rnn_cell_demo.py again to use your registeration mechanism.

Besides, bucket_io.py revised to be compatible with python 3.x. Otherwise the program exit abnormally.

**Comment by mz24cn** [comment]
detailed explanations (in Chinese) :  https://github.com/dmlc/mxnet/issues/4878

**Pull request closed without merging**
