### PR TITLE
Copy code button

### PR DESCRIPTION
**Pull request by kevinthesun**
Copy code button:
copycode1

copycode2

It will automatically remove all texts which are not executable, except code comments.

@zackchase Can you review this change? Thanks!

### CODE REVIEW

**Comment by zackchase** [comment]
I like this! Good work @kevinthesun. @mli, @madjam, @piiswrong - what do you think about this?

**Comment by piiswrong** [comment]
cool. how do we tell users that it will only copy code?

**Comment by mli** [comment]
does it work if we have a code block does not contain '<<<' such as 

```python
import mxnet 
```

**Comment by madjam** [comment]
@kevinthesun this is very good. Did you also look at what numpy has in their documentation? https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

I like that better.

**Comment by kevinthesun** [comment]
@mli Yes. If will automatically check whether code contains leading gap symbol.

**Comment by kevinthesun** [comment]
@piiswrong Maybe we can change the tooltip to notice user that only executable codes are copied.

**Comment by kevinthesun** [comment]
@madjam The issue for mxnet.io is we have multiple languages and each of them has different leading gap symbols. For languages other than python, leading gap symbol can't be picked out by simply calling "find('.go, .gp, .gt')", which is done by numpy.

**Comment by mli** [comment]
i'm going to merge this pr now. we can open another PR for other features

**Pull request merged**
