### PR TITLE
adding scala docs

### PR DESCRIPTION
**Pull request by andremoeller**
scaladoc needs to be installed on the docs build server. I think that's installed alongside scala. In any case, please ensure that you can run "scaladoc" on the build server.

### CODE REVIEW

**Comment by piiswrong** [comment]
@mli Does mxnet.io have scaladoc installed?

**Comment by mli** [comment]
which scala version is needed?

i installed it by `apt-get install scala` 

```
~/mxnet/docs$ scala
Welcome to Scala version 2.9.2 (OpenJDK 64-Bit Server VM, Java 1.7.0_111).
Type in expressions to have them evaluated.
Type :help for more information.
```
but get a bunch of errors:
```
 ^
./Symbol.scala:864: error: not found: value s
    val docStr = s"${name.value}\n${desc.value}\n\n$paramStr\n"
                 ^
./Symbol.scala:914: error: not found: value s
    require(function != null, s"invalid operator name $operator")
                              ^
./Symbol.scala:956: error: not found: value s
    require(function != null, s"invalid operator name $operator")
                              ^
./Symbol.scala:1026: error: not found: value s
    require(args.length == argNames.length, s"Length of $argKey do not match number of arguments")
                                            ^
./Symbol.scala:1041: error: not found: value s
          require(allowMissing, s"Must specify all the arguments in $argKey")
                                ^
./Shape.scala:8: error: value toVector is not a member of Traversable[Int]
  private val shape = dims.toVector
                           ^
./Shape.scala:11: error: value toVector is not a member of Int*
    this(dims.toVector)
              ^
./Shape.scala:11: error: called constructor's definition must precede calling constructor's definition
    this(dims.toVector)
    ^
180 errors found
Exception in thread "main" java.lang.NullPointerException
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer.scala$tools$nsc$typechecker$SuperAccessors$SuperAccTransformer$$checkPackedConforms(SuperAccessors.scala:53)
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer$$anonfun$1$$anonfun$apply$1.apply(SuperAccessors.scala:47)
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer$$anonfun$1$$anonfun$apply$1.apply(SuperAccessors.scala:47)
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer.scala$tools$nsc$typechecker$SuperAccessors$SuperAccTransformer$$withInvalidOwner(SuperAccessors.scala:263)
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer$$anonfun$1.apply(SuperAccessors.scala:47)
	at scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer$$anonfun$1.apply(SuperAccessors.scala:45)
```

**Comment by andremoeller** [comment]
I have 2.11.7 installed.

Also, a heads-up: scaladoc throws errors since the dependencies aren't on the classpath, but they aren't needed for the docs to build

**Comment by mli** [comment]
i updated scala. but i still get an error message, 

```
import org.slf4j.{LoggerFactory, Logger}
```
and fail to build.

a naive question: how to install slf4j?

**Comment by andremoeller** [comment]
slf4j should be pulled in by the build system (mvn), but it shouldn't be necessary in this case. I get the same message, (http://pastebin.com/raw/X5cB4q2b) but it still yields the required files: index.html, index.js, package.html, ml/, lib/, and index/. If these aren't present, I can try debugging it on the server tomorrow.

**Comment by Ldpe2G** [comment]
Using the following command can successfully generate the scala doc html but first need to compile the scalapkg,

```bash
scaladoc -toolcp ./assembly/linux-x86_64-gpu/target/mxnet-full_2.11-linux-x86_64-gpu-0.1.2-SNAPSHOT.jar `find ./ -type f -name "*.scala" -not -path "*core/src/test*" -not -path "*examples*" -not -path "*spark*"`
```

because I don't have spark installed in my computer, so I need to exclude the spark folder.

**Pull request merged**
