### PR TITLE
Deep reinforcement learning for playing flappybird by mxnet

### PR DESCRIPTION
**Pull request by li-haoran**

### CODE REVIEW

**Comment by winstywang** [comment]
Please merge the latest changes, then I can merge it in.

**Comment by li-haoran** [comment]
i just merge the latest version before this pr., maybe i make some mistakes T。T  .

**Comment by tornadomeet** [comment]
@li-haoran hello, you can clone a newest mxnet, and then add that line in the readme, because your this pr was not based on the newest mxnet branch.

**Comment by li-haoran** [comment]
first time for pr, make me very embarrassed. so embarrassed.T.T

**Pull request closed without merging**
