### PR TITLE
Fix css

### PR DESCRIPTION
**Pull request by kevinthesun**
Fix doc website navigation bar css issues.

### CODE REVIEW

**Comment by piiswrong** [comment]
Please remove the DS_Store files

**Comment by kevinthesun** [comment]
I basically fixed all the major issues on index page except font.

**Comment by piiswrong** [comment]
Great! Thanks.
Please also have a look at api pages. i.e. http://mxnet.io/api/python/symbol.html

**Comment by kevinthesun** [comment]
Is there any major issue on this page?

**Comment by piiswrong** [comment]
Basically it's ugly...
Line spacing, indentation, coloring, font, etc
For example this looks prettier: https://keras.io/layers/embeddings/

**Comment by kevinthesun** [comment]
OK. I'll take a look.

**Comment by piiswrong** [comment]
Also this: https://www.tensorflow.org/versions/r0.11/api_docs/python/framework.html#Tensor

**Comment by pluskid** [comment]
Not sure if it is related to this PR: the top banner of the doc website now flashes a lot when you move the cursor on to it. I guess it is because there is a slight different color being used under some `:hover` event.

**Pull request merged**
