### PR TITLE
Fixing ConcatOp when one of the inputs doesn't have gradient

### LINKED ISSUE #1130: (req[i]) == (kWriteTo) in concat layer
I am building a Neural GPU from this paper: http://arxiv.org/pdf/1511.08228v1.pdf

I am facing an issue that I can't repro with a small demo. The code is here: https://github.com/SkidanovAlex/NeuralGPU/blob/49f4e83d46630132c67d470d5c96267ba1ddebcd/src/neuralgpu.py

When I run the code as it is right now, it runs. If I uncomment lines 15 and 25 and comment 24, the code fails when it binds with an error `(req[i]) == (kWriteTo)` when instantiating the ConcatLayer.

What I am trying to achieve is to pad my input with zeros. For that I create a new variable, which later will be initialized with zero, and concat my input with that variable (there's also BlockGrad there, which I assume is not needed, but removing it doesn't help). The error occurs when `i` is equal to `1`, and `req[i]` is equal to `kNullOp`. Am I missing some important step in initializing my `padding` variable?

Also, is there any better way to pad a tensor of shape `a x 1 x c x d` with zeros to shape `a x b x c x d` then concating it with a tensor of zeros?

And I have one more unrelated issue with the same code: all the weights of my model do not depend on the input size, yet the model itself does depend on it (some reshape layers use input size). I then want to train my model on inputs of different sizes sharing the weights. To achieve that I bind a model separately each time, and copy weights and biases from the last model. After several iterations I run out of GPU memory, so it seems like the parameters from the previous iterations are not freed up. Does mxnet free up the GPU memory as soon as the model symbol and all the parameters go out of scope?

### PR DESCRIPTION
**Pull request by SkidanovAlex**
Fixes #1130

### CODE REVIEW

**Comment by SkidanovAlex** [comment]
@piiswrong seems like github deleted your comment as I updated the PR O.o

Replaced the mask with a vector, and fixed the linter error that I introduced last time.

**Comment by SkidanovAlex** [comment]
Hi, guys,
Is there anything blocking from merging it in?

**Comment by piiswrong** [comment]
Sorry. Travis has been really slow recently. Merged.

**Comment by piiswrong** [comment]
Oops. I probably merged too soon. There is a potential problem: when req[i] = NullOp, the corresponding in_grad blob may not be initialized, so calling get_with_shape on it is not safe. Plus it would be good if you can also handle AddTo. 
two suggestions:
There is no need for a mask, just pass in req
Save the dimensions in forward pass. because in backward pass, for NullOp, neither in_data nor in_grad is available.

Could you do the fix and open another PR?

**Comment by tqchen** [comment]
Thanks for the contribution, I have added you to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md Please feel free to update contents about your self, and help making mxnet better

**Comment by SkidanovAlex** [comment]
@piiswrong, note that I do not call `get_with_shape` if `req[i]` is `kNullOp`, I moved it down after check. I only get one dimension of the shape from `in_grad`. The shape appears to be always initialized (the test I wrote intentionally runs the case with nullop before the case without so that properly initialized memory doesn't appear there by chance, and it seems to pass). 

I will apply your suggestions and send a PR. I might not be able to do it this/next week, but in the current state code seems to be not worse than before, so it is unlikely to cause any problems in the meantime.

**Pull request merged**
