### PR TITLE
Windows Compatibility

### PR DESCRIPTION
**Pull request by happynear**
Hi everyone,

I have created a Visual Studio 2013 solution to build MXNet in winodws. I have tried my best to make the solution as similar as the ones in dmlc-core & cxxnet's `windows` directory.

Some minor compatible problems are also fixed by adding some macros. However, some of them may also works in linux. You may have better choices to merge them.

The 3rdparty libraries are uploaded to [BaiduYun](http://pan.baidu.com/s/1x7fw6). Since I am in the mainland of China, it is difficult for me to access DropBox or OneDrive. May someone help me upload the `mxnet_3rdparty.zip` to one of the foreign online dsik and modify the link?

A build instruction is provided in `./windows/README.md`. To be honest, it is not easy to configure. May it helps the ones who can only work in windows.

### CODE REVIEW

**Comment by antinucleon** [comment]
Thanks for the PR. Could you work together with @jermainewang to use CMake to support Windows instead of using VSProject file directly? Also please fix the issue reported in https://travis-ci.org/dmlc/mxnet/builds/82698412

**Comment by tqchen** [comment]
@happynear  Thanks for the contribution! We are looking into using cmake to generate the VS solutions so that it can be easier for configuration and migration, do you have experience on that to see if it is feasible?

- Ideally, we want two types of builds, one with CUDA support, another without.

**Comment by happynear** [comment]
@antinucleon  @tqchen ,
Sorry I am not familiar with CMake. I'm afraid I cannot provide some help.

@jermainewang , can CMake create python project in visual studio? Jointly debuging Python and C++ codes is the most valuable feature of VS in my eyes. I strongly recommend you to realize it in CMake.

**Comment by tqchen** [comment]
Thanks @happynear ! The main reason that we want to go for CMake is for better maintainability. We are open to other options if that serves better.

Your changes to make windows compatibility is valuable. Can you update the PR, or create another PR to only contain the C++ MSVC compatible fix, and please add your name to  https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md in the PR as well.

Thanks!

**Comment by happynear** [comment]
OK, I will create another PR and leave the current branch in my repository.

**Pull request closed without merging**
