### PR TITLE
fix caffe stream

### PR DESCRIPTION
**Pull request by piiswrong**
@tqchen @HrWangChengdu

### CODE REVIEW

**Comment by HrWangChengdu** [comment]
@piiswrong I still cannot pass if kv = 'local_allreduce_device' on my machine. The gradient seems zero.

**Comment by HrWangChengdu** [comment]
@piiswrong I still cannot pass example after adding cudaStreamSyn on my machine.

**Comment by piiswrong** [comment]
@HrWangChengdu "device" works for me but 'local_allreduce_device' doesn't. It's so strange. They should be the same thing

**Comment by HrWangChengdu** [comment]
Me too. 'Device' could work with or without streamSync. 'local_allreduce_device' cannot work in either setting.

**Comment by piiswrong** [comment]
@HrWangChengdu Looks like caffeop is fine. It's local_allreduce_device that's broken @tqchen

**Comment by piiswrong** [comment]
@HrWangChengdu http://docs.nvidia.com/cuda/cuda-driver-api/stream-sync-behavior.html#stream-sync-behavior
looks like this fix is not necessary. Caffe uses the default stream. It blocks all other streams

**Comment by tqchen** [comment]
should be fixed by now, please check

**Comment by HrWangChengdu** [comment]
@tqchen It works now!
@piiswrong Yes. Example code could run without this fix. I'll double check this later this week. Thank you.

**Pull request merged**
