### PR TITLE
Improving SSD example

### PR DESCRIPTION
**Pull request by ikvision**
Adding 3 notebooks:
1. ssd_prepare for downloading data
2. ssd_predict for demo
3. ssd_train for training on VOC dataset

Moreover the ssd iterator has been adapted to python3

### CODE REVIEW

**Comment by piiswrong** [comment]
is python2 still supported?

**Comment by zhreshold** [comment]
@ikvision Why removing basic demo examples? ipynb should be a standalone example.  I don't think downloading model using notebook is a good idea.
BTW, I have rewritten a C++ iterator based on src.io.RecordIter, together with many optimizations to the structure, so there's a lot to update within this week or maybe next.
@ikvision Could you help me update the ipynb for the new version then?

**Comment by ikvision** [comment]
@zhreshold I would gladly update the notebooks for the optimized iterator
Please send me a link to the new iterator and I will try integrating it

**Comment by ikvision** [comment]
@piiswrong I made my best to be python2 compatible and did python2 tests along the way.
Today I am having troubles building mxnet on python2 on mac-osX, is it a know issue?
So the latest commit was test only on python3

**Comment by piiswrong** [comment]
You need to update the submodules

**Comment by ikvision** [comment]
After adapting the submodules - extra ssd operator moved to contrib
Apparently ./model/ssd_300-symbol.json needs to be updated.
"op": "MultiBoxPrior" or "MultiBoxTarget" need to be update to 
` "op": "__contrib__MultiBoxPrior" `
and 
`"op": "__contrib__MultiBoxTarget"`

**Comment by piiswrong** [comment]
@ikvision Any updates on this PR?

**Comment by ikvision** [comment]
The ssd example stop working due to the Scale operator that exist in the json architecture, but is not supported anymore.
What should I do to make it accepted

> detector.detect_and_visualize(image_list, args.dir, args.extension,
                               CLASSES, args.thresh, args.show_timer)
 returns:
nullptr Operator Scale is not registered.
 
json:
{
  "op": "null",
  "param": {},
  "name": "relu4_3_scale_20_scale",
  "inputs": [],
  "backward_source_id": -1
},
{
  "op": "Scale",
  "param": {"mode": "spatial"},
  "name": "relu4_3_scale_20",
  "inputs": [[44, 0], [45, 0]],
  "backward_source_id": -1
},

**Comment by ikvision** [comment]
Before the API changes it was supporting python2 and 3

**Comment by piiswrong** [comment]
any plan to update this

**Comment by mli** [comment]
as per discussion, we will create two pr to replace this one. 1) python3 compatibility, 2) a markdown file for ssd tutorial. for 2), i'll provide a template how to write such tutorial later

**Pull request closed without merging**
