### PR TITLE
model.fit eval_epoch support

### PR DESCRIPTION
**Pull request by taoari**
eval_epoch support. It is sometimes annoying to evaluate the test dataset after each epoch.

### CODE REVIEW

**Comment by piiswrong** [comment]
It's usually better to resize your train_iter with mx.io.resize

**Comment by taoari** [comment]
@piiswrong You mean mx.io.ResizeIter? Got it, but this ResizeIter breaks the meaning of "epoch", I think it is more meaningful to control the training process via some parameters like `eval_epoch` and `checkpoint_period`.

**Comment by piiswrong** [comment]
Ok.
Could you do the following:
change eval_epoch to eval_period.
Add comment for eval_period

**Comment by taoari** [comment]
@piiswrong The comment is added, but I think `eval_epoch` might be more consistent with the others such as `lr_factor_epoch` and `load_epoch`.

**Comment by piiswrong** [comment]
Those are one time timestamps. This is periodic and controls frequency. eval_epoch sounds like the model is only going to be evaluated once at that epoch

**Comment by taoari** [comment]
@piiswrong Thanks for your timely response, it is done!

**Pull request closed without merging**
