### PR TITLE
fix ndarray split

### PR DESCRIPTION
**Pull request by sxjscience**
Fix https://github.com/dmlc/mxnet/issues/5790 @Godricly

### CODE REVIEW

**Comment by Godricly** [comment]
It works! 
Do you think its better to change the 'split' to 'Split'? 
```c++
 	NNVM_REGISTER_OP(SliceChannel).add_alias("split");
```
```c++
 	NNVM_REGISTER_OP(SliceChannel).add_alias("Split");
```

**Comment by sxjscience** [comment]
@Godricly We could do that. But in numpy, it's numpy.split.

**Comment by Godricly** [comment]
I see. Maybe the existing concatenate should be replaced by Concat. 
Anyway, thank you for fixing it.

**Comment by sxjscience** [comment]
@Godricly Also, we can use `nd.concat` now. I think we can use `nd.concat`, `nd.Concat`, `nd.concatenate`, nd.Concatenate`

**Pull request merged**
