### PR TITLE
Stochastic Gradient Langevin Dynamics + Bayesian Dark Knowledge examples

### PR DESCRIPTION
**Pull request by sxjscience**
Stochastic Gradient Langevin Dynamics & Bayesian Dark Knowledge Example
=======================================================================

Contains examples related to *Stochastic Gradient Langevin Dynamics (SGLD)* [<cite>(Welling and Teh, 2011)</cite>](http://www.icml-2011.org/papers/398_icmlpaper.pdf)
and *Bayesian Dark Knowledge (BDK)* [<cite>(Balan, Rathod, Murphy and Welling, 2015)</cite>](http://papers.nips.cc/paper/5965-bayesian-dark-knowledge).

**sgld.ipynb** shows how to use MXNet to repeat the toy experiment in the original paper. **bdk_demo.py** contains scripts related to Bayesian Dark Knowledge. 
Use `python bdk_demo.py -d 1 -l 2 -t 50000` to run classification on MNIST. More details will be added.

See https://github.com/sxjscience/mxnet/blob/bayesian-dark-knowledge/example/bayesian-dark-knowledge/sgld.ipynb for the current notebook. However, the math formulas may not be aligned correctly (see https://github.com/jupyter/nbviewer/issues/452 for similar problems).

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the contribution! This can be very helpful for people working on MCMC.
Can you also make an notebook on bayesian dark knowledge? 

Let us also think about folder name, maybe MCMC or bayesian-method could be a better name. We could possibly add other optimizers like SGHMC and SGNHT

**Comment by sxjscience** [comment]
Fine, I'll work on a notebook for BDK. For the folder name, I think bayesian-method would be better and we can add more Bayesian modeling examples to this folder in the future.

**Comment by tqchen** [comment]
@sxjscience do we have any updates on this?

**Comment by sxjscience** [comment]
@tqchen, I've added the notebook for Bayesian Dark Knowledge. See https://github.com/sxjscience/mxnet/blob/bayesian-dark-knowledge/example/bayesian-methods/bdk.ipynb

**Comment by tqchen** [comment]
This looks great, can you squash the commits into one? I will merge it in after the squash

**Comment by sxjscience** [comment]
@tqchen Done.

**Pull request merged**
