### PR TITLE
MKL feature enhance

### PR DESCRIPTION
**Pull request by glingyan**
1. Support BM V2 API, mean & var
2. Pool Asymmetric padding filled feature

Signed-off-by: lingyan <lingyan.guo@intel.com>

### CODE REVIEW

**Comment by piiswrong** [comment]
The change in elementwise_sum is lost due to the nnvm refactor.
Please add it back in nnvm branch

**Comment by lingyanz** [comment]
diff

after checking the diff between master & nnvm branch
it seems that the operator files is missing, but MKL folder is the same

**Comment by lofrank** [comment]
@glingyan 

I get following error when try to build on windows with visual studio 2015:

> Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		identifier "dnnBatchNormalizationCreateForward_v2_F32" is undefined	mxnet	...\mxnet\src\operator\mkl\mkl_cppwrapper.h	832	

I have installed w_mkl_2017.0.109.exe, the content of mkl_version.h file is like this:

`#ifndef _MKL_VERSION_H_
#define _MKL_VERSION_H_

#define __INTEL_MKL_BUILD_DATE 20160802

#define __INTEL_MKL__ 2017
#define __INTEL_MKL_MINOR__ 0
#define __INTEL_MKL_UPDATE__ 0

#define INTEL_MKL_VERSION 20170000

#endif`


Would you  please give some comments, thanks.

**Comment by glingyan** [comment]
Hi Lofrank:
   Your mkl windows version is quite old. Need at least >= 20161122

**Comment by lofrank** [comment]
Thanks for your quick response, I will try to download new version.

Send from my iPhone

? 2016?12?28??22:50?glingyan <notifications@github.com<mailto:notifications@github.com>> ???

Hi Lofrank:
Your mkl windows version is quite old. Need at least >= 20161122

**Comment by lofrank** [comment]
@glingyan 

I have updated MKL to latest version (windows), and Intel Software Manager shows no update.
The version is 20161006.
So seems MKL version >= 20161122 is not published for windows for now?


image

image

**Comment by glingyan** [comment]
Yes, MKL is a big version, it have it is long publish flow.
So please try to use small mklml package on linux, sorry

**Comment by lofrank** [comment]
@glingyan 

Thanks for your explain.
I will wait for windows version since I do my dialy work on windows (this is why I use mxnet :))

**Pull request merged**
