### PR TITLE
mkl fast path patch update

### PR DESCRIPTION
**Pull request by glingyan**
1. enable fast path in nnvm branch
2. fix mkl v2 private format problem
3. disable mkl info

Signed-off-by: lingyan <lingyan.guo@intel.com>

### CODE REVIEW

**Comment by glingyan** [comment]
@mli @piiswrong  latest patch for nnvm branch

**Comment by glingyan** [comment]
pass tests/python/train/test_conv.py
WARNING:root:[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
--2016-12-28 11:20:50--  http://data.mxnet.io/mxnet/data/mnist.zip
Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.80
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.80|:913... connected.
Proxy request sent, awaiting response... 200 OK
Length: 11595270 (11M) [application/zip]
Saving to: ‘data/mnist.zip’

mnist.zip                                          100%[================================================================================================================>]  11.06M  10.3MB/s    in 1.1s    

2016-12-28 11:20:51 (10.3 MB/s) - ‘data/mnist.zip’ saved [11595270/11595270]

Archive:  mnist.zip
  inflating: t10k-images-idx3-ubyte  
  inflating: t10k-labels-idx1-ubyte  
  inflating: train-images-idx3-ubyte  
  inflating: train-labels-idx1-ubyte  
[11:20:53] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28)
[11:20:53] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28)
MKL Build:20161209

**Comment by glingyan** [comment]
(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet$ python tests/python/gpu/test_operator_gpu.py 
[11:22:53] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while...
MKL Build:20161209
[11:22:53] src/operator/pooling.cu:35: Sum pooling is not supported by cudnn, MxNet sum pooling is applied.
[11:22:53] src/operator/pooling.cu:35: Sum pooling is not supported by cudnn, MxNet sum pooling is applied.
[11:22:53] src/operator/pooling.cu:35: Sum pooling is not supported by cudnn, MxNet sum pooling is applied.
(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet$ python tests/python/unittest/test_operator.py
MKL Build:20161209
[11:23:46] src/operator/tensor/./matrix_op-inl.h:155: Using target_shape will be deprecated.
(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet$ cd example/image-classification/

**Comment by glingyan** [comment]
pass benchmark

(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet/example/image-classification$ python benchmark_score.py 
INFO:root:network: alexnet
INFO:root:device: cpu(0)
MKL Build:20161209
INFO:root:batch size  1, image/sec: 92.634480
INFO:root:batch size  2, image/sec: 161.885673
INFO:root:batch size  4, image/sec: 231.587160
INFO:root:batch size  8, image/sec: 419.584073
INFO:root:batch size 16, image/sec: 424.037568
INFO:root:batch size 32, image/sec: 699.141701
INFO:root:network: vgg
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 29.283698
INFO:root:batch size  2, image/sec: 43.495932
INFO:root:batch size  4, image/sec: 56.662440
INFO:root:batch size  8, image/sec: 59.977835
INFO:root:batch size 16, image/sec: 72.243211
INFO:root:batch size 32, image/sec: 75.826903
INFO:root:network: inception-bn
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 15.626930
INFO:root:batch size  2, image/sec: 20.901151
INFO:root:batch size  4, image/sec: 27.579757
INFO:root:batch size  8, image/sec: 26.375455
INFO:root:batch size 16, image/sec: 26.151229
INFO:root:batch size 32, image/sec: 29.265092
INFO:root:network: inception-v3
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 7.580702
INFO:root:batch size  2, image/sec: 9.459718
INFO:root:batch size  4, image/sec: 11.520767
INFO:root:batch size  8, image/sec: 11.841034
INFO:root:batch size 16, image/sec: 11.470438
INFO:root:batch size 32, image/sec: 10.366669
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 38.803309
INFO:root:batch size  2, image/sec: 44.550964
INFO:root:batch size  4, image/sec: 50.163285
INFO:root:batch size  8, image/sec: 53.401695
INFO:root:batch size 16, image/sec: 9.470987
INFO:root:batch size 32, image/sec: 12.635719
INFO:root:network: resnet-152
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 8.680383
INFO:root:batch size  2, image/sec: 19.338058
INFO:root:batch size  4, image/sec: 9.129889
INFO:root:batch size  8, image/sec: 5.561658
INFO:root:batch size 16, image/sec: 11.205014
INFO:root:batch size 32, image/sec: 25.518331

**Comment by glingyan** [comment]
I notice that  resnet-50 size 16 & 32 data is very strange , so  I make below test , the data is totally difference
(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet/example/image-classification$ python benchmark_s.py
INFO:root:network: resnet-50
INFO:root:device: cpu(0)
MKL Build:20161209
INFO:root:batch size 16, image/sec: 58.960396
INFO:root:batch size 32, image/sec: 57.826763

patch is 

(mxnet_env) lingyan@aocl-server:~/intel_mxnet/glingyan/mxnet/example/image-classification$ git diff benchmark_score.py
diff --git a/example/image-classification/benchmark_score.py b/example/image-classification/benchmark_score.py
index 4a21787..6c708f3 100644
--- a/example/image-classification/benchmark_score.py
+++ b/example/image-classification/benchmark_score.py
@@ -48,12 +48,12 @@ def score(network, dev, batch_size, num_batches):
     return num_batches*batch_size/(time.time() - tic)
 
 if __name__ == '__main__':
-    networks = ['alexnet', 'vgg', 'inception-bn', 'inception-v3', 'resnet-50', 'resnet-152']
-    devs = [mx.gpu(0)] if len(get_gpus()) > 0 else []
+    networks = ['resnet-50']
+    devs = [] # [mx.gpu(0)] if len(get_gpus()) > 0 else
     # Enable USE_MKL2017_EXPERIMENTAL for better CPU performance
     devs.append(mx.cpu())
 
-    batch_sizes = [1, 2, 4, 8, 16, 32]
+    batch_sizes = [ 16,32]
 
     for net in networks:
         logging.info('network: %s', net)

**Comment by piiswrong** [comment]
nnvm is merged into master now. I thought you don't need the buffer in ndarray anymore? Why add it back?

**Comment by glingyan** [comment]
Hi Eric:
   The reason that I found that only ndarray could cover all the case , for some case , it do not use graphexector to get the data.
   And ndarray do not have the problem anymore

**Comment by piiswrong** [comment]
What do you mean " it do not use graphexector to get the data."? What's the effect of that? If we can leave it out of ndarray we should.

**Comment by glingyan** [comment]
I will show you the example later, I found that do not get right filter_data and affect accuracy
Believe , merge it first , it is the best solution to make it work now

**Pull request closed without merging**
