### PR TITLE
[OP] Fix req and reserve_space in cudnn_rnn

### PR DESCRIPTION
**Pull request by sxjscience**
In CuDNN V5, the `cudnnRNNBackwardWeights` will add the calculated gradients to the existing value. We thus need to initialize `dw` to 0 when `kAddTo` is not used. @sbodenstein, could you help review this? Also, I'm not clear about the layout of `parameters` for multiple stacked LSTM layers. For a single layer, I find the layout is `[flatten(i2h_weight), flatten(h2h_weight), flatten(i2h_bias), flatten(h2h_bias)]`, but that doesn't hold for multiple LSTM layers.

### CODE REVIEW

**Comment by sxjscience** [comment]
@sbodenstein Another question I have is about the `reserveSpace`. Currently the forward and backward API calls do not share the same `reserveSpace`. https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_rnn-inl.h#L122-L125, https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_rnn-inl.h#L230-L232. However, in the CuDNN manual, it mentions that `The data in reserveSpace must have previously
been generated by cudnnRNNForwardTraining.`.
I've tried to stack two RNN symbols but the backpropagation doesn't give the correct result. I'm figuring out if it is caused by the `reserveSpace` issue.

**Comment by sxjscience** [comment]
OK, I find that the previous problem can be solved after sharing the `reserveSpace`.

**Comment by sbodenstein** [comment]
@sxjscience: Thank you for pointing out these bugs! Indeed, I didn't notice that cudnnRNNBackwardWeights accumulates, not writes to. Good catch. 

> Another question I have is about the reserveSpace. Currently the forward and backward API calls do not share the same reserveSpace.

Ah, the backward and forward temp resources are not shared (despite having the same name, kTempSpace). I see that you are solving this via `cudaMalloc`. Isn't this banned (#2944):

> Please do not use cudaMalloc & cudaFree directly anywhere in MXNet. Use Storage::Get()Alloc(size, Context::GPU()) to allocate memory to current GPU instead.

Is this possible to do with `Storage::Get()Alloc(size, Context::GPU())` instead?

> Also, I'm not clear about the layout of parameters for multiple stacked LSTM layers.

See the discussion in #3197. But tl;dr: If we decide to go with this design, I can supply a Python converter that splits the parameter NDArray into its component pieces.

**Comment by sxjscience** [comment]
You are right. Let me revise it using Storage::Get. Also, I find that we may need to support giving separate weights/bias. How about letting the users give just 4 parameters for each layer? i.e i2h_weight, h2h_weight, i2h_bias, h2h_bias. We can flatten and concatenate the parameters in the forwarding and use the splitting api in the backward.

**Comment by sbodenstein** [comment]
@sxjscience: That looks good. I want to run a few tests on my GPU machine tomorrow, and will let you know whether everything looks good. Then this should be merged.

**Comment by sbodenstein** [comment]
>  How about letting the users give just 4 parameters for each layer? i.e i2h_weight, h2h_weight, i2h_bias, h2h_bias.

Does eg. 'i2h_weight' contain the weights for all layers squashed together? And this number gets quite large for lstm etc (8 for lstm).

**Comment by sxjscience** [comment]
@sbodenstein I'm thinking to push all the input-to-gate and input-hidden weights into i2h_weight and hidden-to-gate and hidden-to-hidden weights into h2h_weight. And we can let the users give 4 parameters per layer, e.g, `[i2h_weight0, h2h_weight0, i2h_bias0, h2h_bias0, i2h_weight1, h2h_weight1, i2h_bias1, h2h_bias1]`
I've written a wrapper for RNN in the python side, which uses this type of layout. I may PR after repeating the accuracy of the NLP task.
```python
class RNN(object):
    """High level API for constructing stacked RNN layers.

    To use a recurrent neural network, we can first create an RNN object and use the step function
    during the symbol construction.

    Currently four types of RNN are supported and all parameters per layer are grouped into 4 matrices.
    The data layout and transition rules are similar to the RNN API in CuDNN (https://developer.nvidia.com/cudnn)
    1) ReLU RNN:
        h_t = ReLU(W_i x_t + R_i h_{t-1} + b_{W_i} + b_{R_i})

        Parameters:
            W_{i2h} = W_i
            b_{i2h} = b_{W_i}
            W_{h2h} = R_i
            b_{h2h} = b_{R_i}
    2) Tanh RNN:
        h_t = tanh(W_i x_t + R_i h_{t-1} + b_{W_i} + b_{R_i})

        Parameters:
            W_{i2h} = W_i
            b_{i2h} = b_{W_i}
            W_{h2h} = R_i
            b_{h2h} = b_{R_i}
    3) LSTM:
        i_t = \sigma(W_i x_t + R_i h_{t-1} + b_{W_i} + b_{R_i})
        f_t = \sigma(W_f x_t + R_f h_{t-1} + b_{W_f} + b_{R_f})
        o_t = \sigma(W_o x_t + R_o h_{t-1} + b_{W_o} + b_{R_o})
        c^\prime_t = tanh(W_c x_t + R_c h_{t-1} + b_{W_c} + b_{R_c})
        c_t = f_t \circ c_{t-1} + i_t \circ c^\prime_t
        h_t = o_t \circ tanh(c_t)

        Parameters: (input_gate, forget_gate, new_mem, output_gate)
            W_{i2h} = [W_i, W_f, W_c, W_o]
            b_{i2h} = [b_{W_i}, b_{W_f}, b_{W_c}, b_{W_o}]
            W_{h2h} = [R_i, R_f, R_c, R_o]
            b_{h2h} = [b_{R_i}, b_{R_f}, b_{R_c}, b_{R_o}]
    4) GRU:
        i_t = \sigma(W_i x_t + R_i h_{t-1} + b_{W_i} + b_{R_i})
        r_t = \sigma(W_r x_t + R_r h_{t-1} + b_{W_r} + b_{R_r})
        h^\prime_t = tanh(W_h x_t + r_t \circ (R_h h_{t-1} + b_{R_h}) + b_{W_h})
        h_t = (1 - i_t) \circ h^\prime_t + i_t \circ h_{t-1}

        Parameters: (reset_gate, update_gate, new_mem)
            W_{i2h} = [W_r, W_i, W_h]
            b_{i2h} = [b_{W_r}, b_{W_i}, b_{W_h}]
            W_{h2h} = [R_r, R_i, R_h]
            b_{h2h} = [b_{R_r}, b_{R_i}, b_{R_h}]
    """
```

**Comment by sbodenstein** [comment]
@sxjscience: this looks good to me. Lets merge it, as its fixing an obvious problem. 

We should involve others in the design of this symbol. There are pros and cons for all options.

**Comment by sxjscience** [comment]
@sbodenstein I agree. How about opening a discussing issue?

**Comment by sbodenstein** [comment]
@sxjscience: I'm just noticing now: when you allocation the GPU memory, eg 
```
dropout_states_ = Storage::Get()->Alloc(dropout_byte_, Context::GPU());
```
you don't specify which GPU device the memory should be allocated on. Is this a bug?

**Comment by piiswrong** [comment]
current device will be used if unspecified

**Comment by sbodenstein** [comment]
ah ok thanks.

**Pull request merged**
