### PR TITLE
[Scala] add AutoGrad

### PR DESCRIPTION
**Pull request by Ldpe2G**
follows: #5652

### CODE REVIEW

**Comment by piiswrong** [comment]
the api is volatile so we don't really want to add this every where yet.

**Comment by javelinjs** [comment]
@piiswrong until it is stable?

**Comment by piiswrong** [comment]
we have mxnet.contrib for python to indicate API with limited testing/backward compatibility guarantees. If you have something similar in scala you can put it there

**Comment by piiswrong** [comment]
Actually this is very experimental. The c_api can change a lot. So please don't add it to other languages yet.

**Comment by javelinjs** [comment]
So I'm going to close this pr at the moment. 

@Ldpe2G Feel free to follow the auto grad implement.
And shall we really need to make these '_' started functions public?

**Comment by Ldpe2G** [comment]
@javelinjs  @piiswrong   I see.

**Comment by Ldpe2G** [comment]
@javelinjs I think so, because the operator under src/operator/contrib are start with '_' but they should be public, for example  multibox_detection  are named to '_contrib_MultiBoxDetection' .

**Comment by javelinjs** [comment]
@Ldpe2G Could you open another PR for this change?

**Comment by Ldpe2G** [comment]
@javelinjs ok

**Pull request closed without merging**
