### PR TITLE
ADD speech_recognition example

### PR DESCRIPTION
**Pull request by Soonhwan-Kwon**
**Removed the implicit LICENSE file in example#5923 and add more details and guides for the example.**

This example based on DeepSpeech2 of Baidu helps you to build Speech-To-Text (STT) models at scale using

- CNNs, fully connected networks, (Bi-) RNNs, (Bi-) LSTMs, and (Bi-) GRUs for network layers,
- batch-normalization for training efficiency,
- and a Baidu's WarpCTC for loss calculations.

In order to make your own STT models, besides, all you need is to just edit a configuration file not actual codes.

### CODE REVIEW

**Comment by minsoo-jade-kim** [comment]
We will add performance results in weeks.

**Comment by piiswrong** [comment]
Thanks
I'll merge this first

**Comment by minsoo-jade-kim** [comment]
Many thanks.

**Comment by sbodenstein** [comment]
@Soonhwan-Kwon: MXNet now has a native ctc loss op: https://github.com/dmlc/mxnet/pull/5834

It uses the WarpCTC implementation, so it shouldn't be any slower than using the plugin. It also returns the actual CTC loss, so you don't need to calculate this with custom Python code.

**Comment by Soonhwan-Kwon** [comment]
@sbodenstein Thank you for great contribution! I started to using your merge, and I will revise the example.

**Pull request merged**
