### PR TITLE
Reorganizing high level docs structure and adding fork me on github ribbon

### PR DESCRIPTION
**Pull request by sandeep-krishnamurthy**
* Re-organized high level docs structure.
* Added new headers - Community, Deep Learning Concepts
* Renamed back "Supported Languages" to "API" because all tutorials from
this section will move out to tutorials section.

### CODE REVIEW

**Comment by pluskid** [comment]
I feel "deep learning concepts" are more about dl system / implementation concepts. I think it should be "DL System Design" or just "MXNet Internals" @tqchen @mli ?

**Comment by sandeep-krishnamurthy** [comment]
@pluskid @piiswrong @mli 
Initial idea was to move away general deep learning system design concepts from Architecture and have a separate page for it.
However, I think your suggestions are valid to keep them together. So users first read basic DL design concepts then read MXNet architecture followed by references to MXNet modules.

I am taking up re-organizing Architecture page next, I will remove "Deep Learning Concepts" header in that change. Can we merge this PR as it contains other important changes like fork me ribbon, "community" new heading and renaming supported languages to "API"?

**Comment by piiswrong** [comment]
http://mxnet.dmlc.ml/
ribbon overlapped with language selection.

**Comment by sandeep-krishnamurthy** [comment]
I observe that we need to fix CSS issue in header. Created the issue https://github.com/dmlc/mxnet/issues/3531 with details on other issues in header and possible fixes.

**Pull request merged**
