### PR TITLE
support nvidia/nccl for gpu direct communication

### PR DESCRIPTION
**Pull request by mli**
@hjk41 the implementation is done, to use it

1. install nccl
2. compile with USE_NCCL=1
3. it will take effect if `--kv-store device`, for example
```
python train_mnist.py --gpus 0,1 --kv-store device
```

however, nccl seems having bugs, or my implementation is wrong. the `ncclAllReduce` is blocked randomly, and it blocks every time when using `python train_imagnet.py --network vgg`.

for alexnet, i didn't see a big improvement for using nccl...

### CODE REVIEW

**Comment by piiswrong** [comment]
If it's buggy we probably shouldn't make it default for device?

**Comment by tqchen** [comment]
We should not consider use kvstore abstraction for the nccl case.

Instead, try to expose an allreduce interface directly is more natural to the users in this case. Consider allreduce as another alternative BSP primitive, besides kvstore

**Comment by mli** [comment]
@piiswrong it takes effect only if compiled with `USE_NCCL=1`. i think the bug is due to nccl and a future version of nccl will fix it

@tqchen i don't think have another allreduce interface is good idea, i didn't see potential speedup on performance, but we need to maintain and test two different interfaces. while adding `push_pull` on kvstore which is almost equal to `allreduce` allow us to take advantage of other allreduce implementations. 

since it goes nowhere, i will close the PR and throw away the codes

**Comment by tqchen** [comment]
One thing we should do is to enable plugin as soon as possible in an formal way, so additional primitive, operator and loader, so these things can first start as an plugin

**Comment by amithr1** [comment]
Hi All,

I see that the issue is closed. I would want to try out the nccl as it has optimizations for IBM power. Also, the current code base is well optimized for intel and only hope of scaling on power platforms is to use nccl. The numbers I get while running train_cifar10.py are: 513 samples/sec, 575 samples/sec, 664 samples/sec and 739 samples/sec for one, two, three and four gpus. As you can see, it is scaling pretty badly.

**Comment by mli** [comment]
i think you can manually merge that PR and have a try. the main problem is that nccl is quite buggy at that time i tested. also confirmed by other platform developers, nccl didn't improve things too much on most cnns

**Comment by amithr1** [comment]
So, can I just do a pull of that commit? I can pick them up from the browser but better would be to generate a patch and then try applying it. If something doesn;t apply automatically, I can manually do it.

For IBM systems, nccl has some good optimizations that may benefit. Dont know about stability..I tried just the benchmarks and they seem to run at a reasonable performance..can improve the low scaling I am seeing. Not sure on intel as I have access to only one GPU system

amithr

**Comment by vchuravy** [comment]
https://github.com/dmlc/mxnet/pull/1074.patch or you can use cherry-pick commits you want.

**Comment by amithr1** [comment]
Thanks..looks like there is a marked improvement in performance..get a factor of two improvement. still verifying

**Comment by vchuravy** [comment]
Any updates on integrating nccl to MXNet?

**Comment by antinucleon** [comment]
I remember Mu has done some work on it.
On Wed, May 18, 2016 at 04:40 Valentin Churavy <notifications@github.com>
wrote:

> Any updates on integrating nccl to MXNet?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/pull/1074#issuecomment-220001276>
>
-- 
Sent from mobile phone

**Comment by amithr1** [comment]
I was running some tests..sometime it hangs. I was wondering how the data is split across workers? Does all them get equal number of iterations? otherwise some of them can get stuck and others dont arrive

**Comment by mli** [comment]
yes, on a single machine each gpu has equal number of iterations. i also
saw hanging happens sometimes months ago, i guess its due to bug of nccl

**Comment by vchuravy** [comment]
Do you have a patch-set around that one could test?

**Comment by ajtulloch** [comment]
In our experience, one way to get NCCL deadlocks is if device synchronization occurs (e.g. a call to cudaMalloc/cudaFree) concurrently while the NCCL collective kernel launches.

**Comment by mli** [comment]
that may happen since the engine can have multiple threads. i thought
cudaMalloc/cudaFree
was thread-safe. or it's NCCL's fault to break that assumption

**Pull request closed without merging**
