### PR TITLE
fix group shape of conv and deconv

### PR DESCRIPTION
**Pull request by tornadomeet**
fix the bug https://github.com/dmlc/mxnet/issues/748, and had done some tests,now we can train the original alexnet(with num_group=2 in conv2, conv4, conv5)

### CODE REVIEW

**Comment by piiswrong** [comment]
With real grouping or ignoring grouping instead of crashing?

**Comment by tornadomeet** [comment]
This should belong to the real group(but i'm not very sure), it is the history trick which brought in by alex.  (i want to use the pretraind Hybrid-CNN network https://github.com/BVLC/caffe/wiki/Model-Zoo#places-cnn-model-from-mit, so may should use this)

**Comment by tornadomeet** [comment]
This should belong to the real group(but i'm not very sure), it is the history trick which brought in by alex.  (i want to use the pretraind Hybrid-CNN network https://github.com/BVLC/caffe/wiki/Model-Zoo#places-cnn-model-from-mit, so may should use this)

**Comment by tornadomeet** [comment]
@piiswrong @piiswrong @antinucleon  can us look this pr?

**Pull request closed without merging**
