### PR TITLE
nn fixes

### PR DESCRIPTION
**Pull request by szha**
* add CLI to autograd/resnet example
* example fixes

### CODE REVIEW

**Comment by piiswrong** [comment]
contrib.autograd will stay there for a while

**Comment by piiswrong** [comment]
Sequential is still needed because user layers are not necessarily Hybrid

**Comment by szha** [comment]
Should nn be using contrib.autograd or nn.autograd? Last pr updated the latter https://github.com/dmlc/mxnet/pull/6772/files#diff-fbbb49a23307dba3aab15c8f409d91ce, while all examples are using the former.

**Comment by piiswrong** [comment]
nn should use mx.autograd

**Pull request merged**
