### PR TITLE
Fix initialization problem

### PR DESCRIPTION
**Pull request by ZihengJiang**

### CODE REVIEW

**Comment by piiswrong** [comment]
@Ldpe2G The change worked because initializer was skipped. Looks like scala make fails whenever we try to run initializer

**Comment by ZihengJiang** [comment]
Let me try constructor attribute of GCC instead of static global variable.

**Comment by ZihengJiang** [comment]
I've tested it locally, constructor attribute doesn't work for scala too

**Comment by Ldpe2G** [comment]
@piiswrong I am still figuring out what cause this. But I have tried to comment the  following code temporarily
```bash
signal(SIGSEGV, segfault_logger);
```
and scala make successfully. Does it have another way to catch segment fault error? like try catch ?

**Comment by piiswrong** [comment]
try catch doesn't work for segfault.

**Pull request merged**
