### PR TITLE
Add snapcraft packaging

### PR DESCRIPTION
**Pull request by mhall119**
Adds snapcraft build configuration and command to run an in-snap Python 2 runtime. This allows MXNet to be used either by calling "/snap/bin/mxnet.python" or by adding the following to your environment and using your system's python:

LD_LIBRARY_PATH=/snap/mxnet/current/lib:/snap/mxnet/current/usr/lib:$LD_LIBRARY_PATH 
PYTHONPATH=/snap/mxnet/current/lib/python2.7/site-packages/:/snap/mxnet/current/usr/lib/python2.7/dist-packages/:$PYTHONPATH

The snap can be build with "snapcraft snap" on Ubuntu 16.04 or later. Use "snapcraft cleanbuild" to build it in an LXC container instead.

### CODE REVIEW

**Comment by piiswrong** [comment]
distribution is here https://github.com/dmlc/mxnet-distro
It currently publsh to pypi. You can make it publish to snap also.

The benefit of using snap is you can also install scala and R packages. Could you add that?

**Comment by piiswrong** [comment]
Also would be great if there is a gpu enabled option

**Comment by mhall119** [comment]
@piiswrong I've been looking at that mxnet-distro repo, trying to understand where and how you want the snapcraft integrated. Do you simply want the files in this PR submitted there (with modification to paths) or do you want it to be fully integrated into the Travis configuration so that it will create and publish the snap after the Travis build (a more involved process than this PR)?

**Comment by piiswrong** [comment]
Can one of the admins verify this patch?

**Comment by piiswrong** [comment]
It depends on how you want to do the releasing. We can decide that later.
First we should figure out how to support scala, R, gpu, mkl, etc. Can snap detect gpu?

**Comment by mhall119** [comment]
Scala and R can either be bundled into the same .snap as the python library, or we can split this into 3 different language-specific snaps, depending on how desirable small packages are and how common it is for a user to need support for more than one language.

My understanding is that mxnet can be built to use GPU if the build host supports it. Because the use-case for this snap will have the code being executed normally (i.e. without a sandbox) there should be nothing stopping it from detecting and using a GPU at runtime.

**Comment by mhall119** [comment]
@piiswrong what should I do to keep moving this PR along? I'm unclear from the last comments if you are waiting on me or someone else.

**Comment by piiswrong** [comment]
I can merge this right now but what we really want is binaries on the server now config file in the repo.
I'm just trying to figure out how that's going to happen

**Comment by piiswrong** [comment]
On detecting gpu, we will build separate binaries for cpu/gpu. Can snap figure out which binary to download based on whether the system has gpu?

**Comment by piiswrong** [comment]
Anyway I can merge this first if you need it merged to take the next steps.

**Comment by mhall119** [comment]
Do you mean binary snap packages? If so, you can use build.snapcraft.io to create them, triggered by commits here. It's like Travis, only made specifically for creating and publishing snaps.

The "snap install" command doesn't currently give any information about GPU. We could have two separate packages, or include both sets of binaries in the same package

**Comment by piiswrong** [comment]
I see. Then I think we should move these files to mxnet-distro which is updated when ever there is a new release.
How do we configure it to build multiple binaries?

**Comment by mhall119** [comment]
build.snapcraft.io will default to building on multiple arches (x86_64, armhf and arm64 I think). It will publish them to an "edge" channel in the store that is the equivalent of daily builds, and only seen by people who specifically ask for the bleeding edge packages. They can then be tested and promoted into "beta" and "stable" channels. By default users will only see the versions published into "stable"

**Pull request merged**
