### PR TITLE
loss layers for rpn and new operator for calc rpn bounding box in gpu side

### PR DESCRIPTION
**Pull request by starimpact**

### CODE REVIEW

**Comment by piiswrong** [comment]
Somehow the commit history is messed up. A lot of previous changes is shown in your PR.
Could you squash your commits with git rebase?

**Comment by piiswrong** [comment]
@antinucleon @precedenceguo @winstywang Could you review the rpn part in the last commit?

**Comment by starimpact** [comment]
OK, I will clean my codes.
But could you help me to check my rpn related codes ?

**Comment by precedenceguo** [comment]
Something might be useful: kCoordLabel are raw input coordinates instead of (dx, dy, dw, dh).

**Comment by starimpact** [comment]
@piiswrong I have been squashed the commits.

**Comment by starimpact** [comment]
@precedenceguo kCoordLabel is a coordinates matrix, it is convenient to do matrix calculation.

**Comment by starimpact** [comment]
seems that no people is interest in it 😞

**Comment by piiswrong** [comment]
I'm not familiar with faster rcnn and it's not clear to me what this is for. The guys that did the faster RCNN example seems to be busy at the moment.
It should help if you can integrate this into the faster rcnn exmaple or add doc and tests that explain what these ops do

**Comment by tqchen** [comment]
One comment, this PR seems still contains additional code that has nothing todo with RPN, e.g. load from bytes, which should be deleted

**Pull request closed without merging**
