### PR TITLE
Create symbol_squeezenet.py

### PR DESCRIPTION
**Pull request by qiaohaijun**
model compression techniques 
compress SqueezeNet to less than 1MB(461x smaller than AlexNet)

### CODE REVIEW

**Comment by qiaohaijun** [comment]
model compression techniques 
compress SqueezeNet to less than 1MB(461x smaller than AlexNet)

**Comment by winstywang** [comment]
Have you checked the results?

**Comment by antinucleon** [comment]
FastPoor is much faster than this net, and similarly has near Alexnet performance. The key is compression but not structure.

**Comment by tqchen** [comment]
@antinucleon What I recommend is to create a better name for fast_poor, like fit_net and have a documentation on what it is on the classification folder. We can also optionally include this in, if people want to compare

**Comment by qiaohaijun** [comment]
@tqchen Where is fast_poor

**Comment by qiaohaijun** [comment]
@winstywang  I will give a result about this net, maybe days later.

**Comment by tqchen** [comment]
let us have a update on this. I am going to merge this in if people are OK with it. but it would be great if @qiaohaijun can post the results check in first.

**Comment by futurely** [comment]
Without further applying Deep Compression [1] on the SqueezeNet network, the model size reduction compared with the AlexNet is 50x. The proposed Fire module is very similar to a mini version of GoogLeNet's Inception module. Is it possible to compress and accelerate Inception-v4 or Inception-ResNet-v2 using the SqueezeNet method?

[1] S. Han, H. Mao, and W. Dally. Deep compression: Compressing DNNs with pruning, trained quantization and huffman coding. arxiv:1510.00149v3, 2015.

**Comment by futurely** [comment]
FastPoor is [here](https://raw.githubusercontent.com/dmlc/mxnet.js/master/model/fastpoor.json).

**Comment by tmatas** [comment]
In the provided file symbol_squeezenet.py the variable `num_classes` is not used;
should it be put in  `conv10` module as `num_filter=1000`?

**Comment by tmatas** [comment]
Moreover, in this version the output size is 9000, but the classes are only 1000!
I think that the global average method
> http://arxiv.org/abs/1312.4400
should be implemented as a `mx.symbol.GlobalAveragePooling` symbol

**Comment by tmatas** [comment]
I have resolved this issue by looking at the size of each output layer with `infer_shape`, ex. 

`arg_shape, output_shape, aux_shape = conv1.infer_shape(data=(1,3,224,224))`

If you look at the size given in the paper, the lines that you need to change is 
`conv1 = mx.symbol.Convolution(data=data, kernel=(7,7), stride=(2,2), num_filter=96, pad=(2,2))`
and
`conv10 = mx.symbol.Convolution(data=dropout_fire9, kernel=(1,1), num_filter=1000)`

**Comment by tmatas** [comment]
Btw, we still need a new operator 'average pooling', otherwise the output size won't match the label size

**Comment by tmatas** [comment]
I would like to commit this file with the corrected version, how can I do that?

**Comment by qiaohaijun** [comment]
@tmatas  sorry so late, I am training the new network, using your suggestion

**Pull request closed without merging**
