### PR TITLE
Add support for eval_data as ndarray pair.

### PR DESCRIPTION
**Pull request by II-Matto**
It supports eval_data as ndarray pair, i.e. a tuple like `eval_data = (data, label)`, where `data` and `label` are both ndarray. The shape of `label` can be (n, ) or (n, 1), and the modification is tested under both cases. Hope my coding style is OK.

### CODE REVIEW

**Comment by antinucleon** [comment]
Thanks for the PR! Please fix the travis in https://travis-ci.org/dmlc/mxnet/jobs/85069662

**Comment by II-Matto** [comment]
@antinucleon Hi, is it OK now? I saw all checks passed. Sorry I didn't know there should be docstring.

**Comment by antinucleon** [comment]
Great thanks again, in general it looks good to me!

Could you fix the parameter and return docstring? Also I think we should
check whether the tuple (maybe also support list) contains Numpy NDArray,
if they are Python list, convert to numpy ndarray so that this function is
more general. The last thing is you may consider to rebase into one commit.

**Comment by II-Matto** [comment]
@antinucleon I'm so sorry that it seems I have messed up something. How should I rebase my commit now? There exist five commits instead of one. =_=||

**Comment by tqchen** [comment]
@II-Matto Seems that the init_data_iter and init_eval_iter kinda of overlaps with each other, maybe you can re-use the init_data_iter(by is_train=False) logic to do the job?

**Comment by II-Matto** [comment]
@tqchen Do you mean `_init_iter(self, X, y, is_train)`? When `is_train` is set to `false`, this function will fill `y` with zeros. So I should change `_init_iter()` as well?

BTW, is there a proper way to merge the 5 commits here? Could I reset them all and then do my modifications all over again?

**Comment by tqchen** [comment]
Yes for merge commits. You can do git rebase -i .

**Comment by tqchen** [comment]
@II-Matto Please also add your name to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md in your next commit. I will merge it in once you fixed the comments on init_iter.

Thanks

**Comment by II-Matto** [comment]
@tqchen I will try to finish it soon. Direct `rebase` operation is prevented by some conflicts and I am trying to find a way to deal with it.

**Comment by tqchen** [comment]
@II-Matto  You can fix the confliction, do a git add the fixed the file, and do ```git rebase --continue```

**Comment by II-Matto** [comment]
@tqchen I have dealt with the commit merge issue, and using `_init_iter()` in `_init_eval_iter()`. I also modified `_init_iter()`, adding extra checks. Hope my modification to the code is ok. I have tested in various cases using `fit()` and `predict()`, and the results are normal.

To make sure I didn't do anything unexpected, I will briefly list what I did to my fork and this PR:
1. Make a fork and clone a local copy.
2. Add `_init_eval_iter()` and then docstring. (2 commits)
3. Try to rebase the last 2 commits. Fail to push to Github.
4. Use `pull` to update the local copy and push again. Succeed.
5. Push the "Update branch" bottom on this PR page. (5 commits appear!)
6. Fail to rebase in various ways. Use `git reset --hard HEAD~3`.
7. Edit `model.py` as @tqchen and @antinucleon suggested.
8. Test modified code in various cases.
9. `git add -A` and `git commit -m "<Message...>"`.
10. Fail to `push` so use `git push --force`.
11. Wait for the travis to finish.

It seems that neither of `git reset --hard` and `git push --force` is suggested, and I am not sure whether or not my operation will have some unexpected effect.

If there are any problems with my code, I will try to fix it soon.

BTW, I think the right thing to do is that I wait for this PR to be done before I use `pull` or "Update branch" to keep my fork synced and don't push other commits (or I will need to start a new branch). And after the PR is done, I can merge the corresponding branch with, say, a "master" branch. Am I right?

**Comment by tqchen** [comment]
@II-Matto It is fine to git push --force to your own fork, As long as the changes are only yours. Thanks Please update the PR to add your name to  https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md and I will merge it in

**Comment by tqchen** [comment]
opps, seems there is some recent changes that makes the branch not able to auto merge. Can you rebase again? Sorry about that

**Comment by II-Matto** [comment]
This page says that "This branch has conflicts that must be resolved". What should I do? =_=

**Comment by tqchen** [comment]
Follow the rebase instruction here https://github.com/dmlc/mxnet/blob/master/doc/contribute.md#submit-a-pull-request

**Comment by II-Matto** [comment]
@tqchen Sorry for my unfamiliarity with git. Is it OK now?

**Comment by tqchen** [comment]
Thanks, this is merged!

**Comment by tqchen** [comment]
I have also updated https://github.com/dmlc/mxnet/blob/master/doc/contribute.md to include more instructions, you are welcome to contribute your experience as well :)

**Comment by II-Matto** [comment]
@tqchen Thanks! This is very considerate.

Since this is the first time I participate in an open source projects, what I really wanted to know, at the very beginning, is the right operations and steps. I had no idea what I needed to know at first, and even didn't know what to search for. After this pull request was finished, I did some googling, and found this blog post very useful: https://gun.io/blog/how-to-github-fork-branch-and-pull-request/ (Unfortunately, this seems to be outiside GFW. A Bing cached page may help in some cases.).

[This blog post](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/) lists the necessary steps (with some of my personal addition):
1. **Check out the "Network" graph** , e.g. https://github.com/dmlc/mxnet/network. It is also necessary to check out existing issues and pull requests.
2. **Open an issue for discussion**.
3. **Make a fork**. See https://help.github.com/articles/fork-a-repo/.
4. **Clone the fork** to get a local working copy.
5. **Add upstream** to get synced with the original repository.
6. **Setup a development branch**. I guess it is a good idea to use a new branch for each new feature or fix, since "you can only have one Pull Request per branch".
7. **Do the development**. Maybe you will commit crazily to the development branch. Also, don't forget to discuss with others.
8 **Squash commits**, i.e. merge small and unnecessary commit pieces into larger and meaningful commits.
9. **Submit a Pull Request (PR)**, discuss, fix problems, etc. Work with other contributors to finally make a good patch.
10. Wait for the owner to merge or reject the PR.
11. Done!
12. Maybe merge the development branch to the forked master branch, and start new branch for new features.

I am not sure whether new commits will keep appearing in a pull request after it is merged, or merging the development branch with the forked master branch will ever effect the corresponding pull request.

**Comment by tqchen** [comment]
If you like to share your experience and contribute to the  https://github.com/dmlc/mxnet/blob/master/doc/contribute.md  to make others to get started more easily

It is more than welcomed :) Thanks for the contribution

**Comment by II-Matto** [comment]
@tqchen I will do that after I perform some experiments to confirm the right thing to do. Thanks the team for making such a good open source project!

**Pull request merged**
