### PR TITLE
Add R installation tutorial

### PR DESCRIPTION
**Pull request by tengpeng**
Add R installation tutorial step by step with trouble shooting. Hope would make installation easier for R users.

### CODE REVIEW

**Comment by thirdwing** [comment]
Thank you for the contribution.

But I am afraid we have the installation instructions at https://github.com/dmlc/mxnet/blob/master/doc/build.md#r-package-installation

**Comment by tengpeng** [comment]
@thirdwing I have read and followed the tutorial you mentioned. 

Many caffe users shared some difficulties during the installation. I do not think R user are much better than caffe users. That's the motivation of my writing.

Maybe combine the pre-installation and troubleshooting parts, and merge to troubleshooting parts?

**Comment by tqchen** [comment]
If these instruction helps to improve the instructions. Can you consider make the PR and enhance the tutorial  here https://github.com/dmlc/mxnet/blob/master/doc/build.md#r-package-installation

**Comment by thirdwing** [comment]
I agree with @tqchen . I can add more instructions but not a new file.

**Comment by tengpeng** [comment]
Great! It is supposed to be a supplement to make the guide more complete.

**Comment by tqchen** [comment]
I think @tengpeng is more than welcomed to modify this PR to improve the build.md instead :)

**Comment by tqchen** [comment]
closing this for now, @tengpeng you are more than welcomed to open a new PR that directly improves the original build doc

**Pull request closed without merging**
