### PR TITLE
enable setting return type for operators in registry

### PR DESCRIPTION
**Pull request by hjk41**
Most operators returns one Symbol, but some like slice_channel returns array of Symbols. This patch enables setting return type to "Symbol" or "Symbol[]" in the registry, so that we can get the return type in MXSymbolGetAtomicSymbolInfo()

### CODE REVIEW

**Comment by piiswrong** [comment]
Can this be accomplished by exposing num visible outputs?

**Comment by hjk41** [comment]
@piiswrong nope. The number of outputs for slice_channel is not fixed. It depends on the parameters.

**Comment by piiswrong** [comment]
Is the return type of Slice still an array if there is only one output?

**Comment by hjk41** [comment]
```c++
virtual void Forward(const OpContext &ctx,
                       const std::vector<TBlob> &in_data,
                       const std::vector<OpReqType> &req,
                       const std::vector<TBlob> &out_data,
                       const std::vector<TBlob> &aux_args)
```

The output of our operators are always array of tblobs. But for most of the operators, we just have one element in the output.
This patch does not affect any existing code, it just enables us to set the information when we register the op properties. And the op properties are just static information of the op. I am currently relying on this information to generate the CPP wrappers for the operators. I think it is also used to generated python doc. Fixing this will allow me to get the return type of the SliceChannel operator right, and it should also fix the python doc.

**Comment by piiswrong** [comment]
I see.

**Pull request merged**
