### PR TITLE
Example ssd, major update 

### PR DESCRIPTION
**Pull request by zhreshold**
*  New image detection iterator in src/io/iter_image_det_recordio.cc similar to iter_image_recordio.cc
*  This iterator coupled with image_det_aug_default can handle various augmentation options for image detection. 
*  As a result, training is significantly faster
*  Better performance on mAP, basically 5% mAP improvement
*  Can monitor validation mAP during training(at the end of each epoch)
*  Caffe converter for SSD models is available

### CODE REVIEW

**Comment by piiswrong** [comment]
Is this faster than using mx.image?

**Comment by zhreshold** [comment]
This one is faster when multiple GPUs are available. 
I got like 15fps/37fps/43fps with the old cv2, mx.image(3 threads) and det_iter.cc(3 threads) on a single GPU, respectively. 
The gap is even larger on multi-gpu and more threads, obviously. 
Basically I found the colorJitter in mx.image was still quite slow a month ago.

**Comment by piiswrong** [comment]
Is this mergable? What's going on with the notebook pr?

**Comment by zhreshold** [comment]
@ikvision
Mergable from my side.

**Comment by lovedl** [comment]
@zhreshold Hi, may I ask you a question? When you say "you got like 15fps/37fps/43fps with the old cv2, mx.image(3 threads) and det_iter.cc(3 threads)". I am curious how you use mx.image for complex data augmentation, like sample cropbox, crop, resize and so on. Do you call the functions in mx.image for a batch of images? For me, each image in a batch could have different parameters in terms of data-augmentation, how do we do as a whole? Thanks in advance.

**Comment by zhreshold** [comment]
@lovedl These functions will be released soon.

**Pull request merged**
