### PR TITLE
l2 norm op && default value of NumOutputs

### PR DESCRIPTION
**Pull request by winstywang**

### CODE REVIEW

**Comment by piiswrong** [comment]
There is a L2Norm under unary function. Maybe you can add backward to that function instead?

**Comment by winstywang** [comment]
We need to broadcast over samples @piiswrong

**Comment by piiswrong** [comment]
ndarray functions now accept keyword parameters, so you can do norm(p=2, axis=1)

**Comment by winstywang** [comment]
https://github.com/dmlc/mxnet/blob/master/src/ndarray/unary_function-inl.h#L206 seems no backward defined for it?

**Comment by winstywang** [comment]
Another question: Could we get the output of forward if implementing it as a unary function? If not, it will introduce extra cost, we have to calculate the norm again.

**Comment by piiswrong** [comment]
I think you can. I'm not 100% sure.

**Comment by winstywang** [comment]
You mean set_gradient? It seems not, or do I miss something? https://github.com/dmlc/mxnet/blob/db1a5b503b12be0d05ab7cc3cc3979819720d3ba/src/common/tblob_op_registry.h#L88

**Comment by winstywang** [comment]
oh... I get it, let me check it then

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/blob/db1a5b503b12be0d05ab7cc3cc3979819720d3ba/src/common/tblob_op_registry.h#L53 this should be the output value you want.

**Comment by winstywang** [comment]
I see. Maybe I am not clear about the use of the op. This op does not output the l2 norm of the ndarray, instead it normalizes each row by its l2 norm. I think we cannot merge these two functions together.

**Comment by tqchen** [comment]
closing for less active on this. feel free to open later

**Comment by winstywang** [comment]
reopen for review? @piiswrong it is different from the ndarray function.

**Pull request merged**
