### PR TITLE
Fixed: MXNET R Reference manual broken link

### PR DESCRIPTION
**Pull request by chetkhatri**
What were proposed in this Pull Request ?
* Broken link fixed for R Package Reference manual.

### CODE REVIEW

**Comment by chetkhatri** [comment]
@mli Relevant 2 issues are open due to above broken link issue, once this will get merge. will ask issuer to close issue.

**Comment by mli** [comment]
we should remove the R reference manual link. it is not maintained anymore. we are consisdering to generate html pages instead of a pdf file

**Comment by chetkhatri** [comment]
@mli For time being let's user go ahead with the pdf, even though generate html for 99 pages pdf will take time. I think for now you can merge it and will keep issue open named generate html for reference manual. would that sounds good.

**Comment by piiswrong** [comment]
Merged since this is at least better than broken link.

**Pull request merged**
