### PR TITLE
Model Parallel LSTM Example

### PR DESCRIPTION
**Pull request by tqchen**
cc @antinucleon @pluskid @mli

### CODE REVIEW

**Comment by tqchen** [comment]
I used the old executor API. tested a bit on Mu's CI mahine, adding GPU can indeed get some speedup for large workload

**Comment by tqchen** [comment]
see https://github.com/dmlc/mxnet/pull/1781/commits/68513c07c903a7fb77f30c1f053a5ee42dc47a77 for changes I made. 

Change this line https://github.com/tqchen/mxnet/commit/5d1da317494bad4d2a5793dc0c3a7e5dcfb288b9#diff-535d0615f09506053f7e903437a4cf36R71

for device placement

**Comment by mli** [comment]
can you please give a rough speedup? we may include them on the slides

**Comment by eric-haibin-lin** [comment]
Is this example not using the bucketing API intentionally? I and @harouwu talked to @mli, and we are doing some benchmarking on the PTB example this week to checkout the bucketing performance on multi-GPU nodes and if any improvement can be made

**Comment by tqchen** [comment]
I just pick the simper version for demonstration. I think the same philosophy applies to bucketing case.

**Pull request merged**
