### PR TITLE
jenkins test

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by piiswrong** [comment]
@javelinjs Please move scala linux test to jenkins.
@sandeep-krishnamurthy we now support running gpu ci

**Comment by pluskid** [comment]
How does the jenkins environment work? Do we have a AWS with everything (julia, scala) installed or do we use a script to download and install those language interpreters every time like Travis CI?

**Comment by sandeep-krishnamurthy** [comment]
@piiswrong This is great. 
* As first step of CI, we should target to run IPython notebook examples from terminal/code.
* We should carefully select or create new notebooks that covers functionality from various components of the system. This ensures our CI test suite is easy to create and maintains high quality.

**Comment by piiswrong** [comment]
You cannot sudo in scripts.
It's an ec2 instance. If you send me your public key I can give you access

**Comment by javelinjs** [comment]
will update soon

**Pull request merged**
