### PR TITLE
0.9 release note

### PR DESCRIPTION
**Pull request by piiswrong**
@tqchen @mli @javelinjs @Ldpe2G @pluskid @thirdwing See if you have any thing to add

### CODE REVIEW

**Comment by mli** [comment]
1. updated image classification example: resnet-family, pre-trained models, distributed performance and convergence results
2. ssd for object detection
3. tools/bandwidth for debugging multi-GPU/machine performance

**Comment by piiswrong** [comment]
These are already in master right? They should be included in 0.8 release notes

**Comment by mli** [comment]
ah, got it.

**Comment by javelinjs** [comment]
lgtm

**Pull request merged**
