### PR TITLE
[WIP/RFC ]Volumetric operators 

### PR DESCRIPTION
**Pull request by korneil**
Currently it's an experimental branch to implement the cudnn/cuda part of volumetric operators. 
The PR is for getting feedback, once I have the code properly running I will recommit the code with the right code formatting.

### CODE REVIEW

**Comment by korneil** [comment]
I am getting an error at the VolumetricConcat operator during compilation, however it's the same as the Concat operator adopted to 5D. 

It has error with this line:

      std::vector <Tensor<xpu, 5>> data(size_);

This is the error:

		src/operator/./volumetric_concat-inl.h(57): error: identifier "data" is undefined
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(57): error: function call is not allowed in a constant expression
		src/operator/./volumetric_concat-inl.h(57): error: expression must have a constant value
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(57): error: expected a ">"
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(57): error: expected a declaration
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(74): error: no instance of function template "mxnet::op::Concatenate" matches the argument list
		            argument types are: (<error-type>, mshadow::Tensor<mxnet::gpu, 5, mshadow::default_real_t> *)
		          detected during:
		            instantiation of "void mxnet::op::VolumetricConcatOp<xpu>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]"
		(44): here
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(89): error: identifier "grad_in" is undefined
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(89): error: function call is not allowed in a constant expression
		src/operator/./volumetric_concat-inl.h(89): error: expression must have a constant value
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(89): error: expected a ">"
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(89): error: expected a declaration
		          detected during:
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

		src/operator/./volumetric_concat-inl.h(108): error: no instance of function template "mxnet::op::Split" matches the argument list
		            argument types are: (mshadow::Tensor<mxnet::gpu, 5, mshadow::default_real_t>, <error-type>)
		          detected during:
		            instantiation of "void mxnet::op::VolumetricConcatOp<xpu>::Backward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]"
		(44): here
		            implicit generation of "mxnet::op::VolumetricConcatOp<xpu>::~VolumetricConcatOp() [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of class "mxnet::op::VolumetricConcatOp<xpu> [with xpu=mxnet::gpu]"
		(44): here
		            instantiation of "mxnet::op::VolumetricConcatOp<xpu>::VolumetricConcatOp(mxnet::op::VolumetricConcatParam) [with xpu=mxnet::gpu]"
		src/operator/volumetric_concat.cu(14): here

Maybe it's something obvious that I miss.
Any idea?

**Comment by piiswrong** [comment]
try 
std::vector <Tensor<xpu, 5> > data(size_);
You need a space there

**Comment by korneil** [comment]
Oh, great thanks, works!

**Comment by piiswrong** [comment]
Your welcome.
BTW, I think it's better to merge activation, concat and pooling into the old ops. These should be shape agnostic. Especially activation.

Thanks,

**Comment by tqchen** [comment]
+1 for moving concat and activations into old generic operators. The support for activation should already been generic and accept 5D tensors, so no re-implementation is needed

**Comment by korneil** [comment]
I will, thanks!

Is there an easy way to dump an output of a symbolic variable in python, or get it as a numpy array? I wonder if I can easily double check e.g. the pooling if it works well.

**Comment by piiswrong** [comment]
x = mx.sym.XXX
X = mx.nd.ndarray()
exe = x.bind(args{'x': X})
exe.forward()
X.asnumpy()

**Comment by korneil** [comment]
Thanks!

**Comment by korneil** [comment]
Do you have any idea what's wrong with this code?

    sym = mx.symbol.Flatten(data=data, name="x")
    D = mx.nd.ones([1, 1, 5, 5, 5])
    X = mx.nd.zeros([1, 25])
    exe = sym.bind(dev, {'x_output': X, 'data': D})
    exe.forward()
    print X.asnumpy()
    print sym.list_outputs()
    print sym.list_arguments()

Output:

	[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
	   0.  0.  0.  0.  0.  0.  0.]]
	['x_output']
	['data']

**Comment by korneil** [comment]
I got this error when trying to access a buffer from python that supposedly has data copied from gpu:

    dev = mx.gpu()
    
    sym = mx.symbol.Flatten(data=data, name="x")
    data = mx.nd.ones([1, 1, 5, 5, 5])
    exe = sym.bind(dev, {'data': data})
    exe.forward()
    
    for v in exe.outputs:
        d = mx.nd.empty(v.shape, ctx=mx.cpu())
        v.copyto(d)
        print d.asnumpy()

The code fails at print d.asnumpy(). Output:

	[03:02:23] ./dmlc-core/include/dmlc/logging.h:208: [03:02:23] ./mshadow/mshadow/./tensor_blob.h:476: Check failed: Device::kDevMask == dev_mask_ && DataType<DType>::kFlag == type_flag_ TBlob.get: device type do not match specified type
	[03:02:23] ./dmlc-core/include/dmlc/logging.h:208: [03:02:23] src/engine/./threaded_engine.h:295: [03:02:23] ./mshadow/mshadow/./tensor_blob.h:476: Check failed: Device::kDevMask == dev_mask_ && DataType<DType>::kFlag == type_flag_ TBlob.get: device type do not match specified type
	terminate called after throwing an instance of 'dmlc::Error'
	  what():  [03:02:23] src/engine/./threaded_engine.h:295: [03:02:23] ./mshadow/mshadow/./tensor_blob.h:476: Check failed: Device::kDevMask == dev_mask_ && DataType<DType>::kFlag == type_flag_ TBlob.get: device type do not match specified type

**Comment by piiswrong** [comment]
This looks like you allocated a gpu/cpu array and used it for cpu/gpu

**Comment by piiswrong** [comment]
@korneil Hi, any updates?

**Comment by kayhan-batmanghelich** [comment]
Hello @korneil and @piiswrong , I was wondering if there is any update on this. When I try to compile the  current code from this repository I get this error:

```
fig --cflags opencv` -DMSHADOW_USE_CUDNN=1  -c src/operator/volumetric_concat.cc -o build/operator/volumetric_concat.o
In file included from src/operator/volumetric_concat.cc:8:
src/operator/./volumetric_concat-inl.h:74:17: error: no matching function for call to 'Concatenate'
                Concatenate(data, &out);
                ^~~~~~~~~~~
src/operator/./volumetric_concat-inl.h:44:22: note: in instantiation of member function 'mxnet::op::VolumetricConcatOp<mshadow::cpu>::Forward'
      requested here
            explicit VolumetricConcatOp(VolumetricConcatParam param) : size_(param.num_args) { }
                     ^
src/operator/volumetric_concat.cc:14:14: note: in instantiation of member function
      'mxnet::op::VolumetricConcatOp<mshadow::cpu>::VolumetricConcatOp' requested here
  return new VolumetricConcatOp<cpu>(param);
             ^
src/operator/./channel_op_common.h:18:13: note: candidate function template not viable: requires 3 arguments, but 2 were provided
inline void Concatenate(const std::vector<mshadow::Tensor<xpu, dim> > &input,
            ^
In file included from src/operator/volumetric_concat.cc:8:
src/operator/./volumetric_concat-inl.h:108:17: error: no matching function for call to 'Split'
                Split(grad, &grad_in);
                ^~~~~
src/operator/./volumetric_concat-inl.h:44:22: note: in instantiation of member function
      'mxnet::op::VolumetricConcatOp<mshadow::cpu>::Backward' requested here
            explicit VolumetricConcatOp(VolumetricConcatParam param) : size_(param.num_args) { }
                     ^
src/operator/volumetric_concat.cc:14:14: note: in instantiation of member function
      'mxnet::op::VolumetricConcatOp<mshadow::cpu>::VolumetricConcatOp' requested here
  return new VolumetricConcatOp<cpu>(param);
             ^
src/operator/./channel_op_common.h:65:6: note: candidate function template not viable: requires 3 arguments, but 2 were provided
void Split(const mshadow::Tensor<xpu, dim> &input,
     ^
2 errors generated.
make: *** [build/operator/volumetric_concat.o] Error 1

```

**Comment by tqchen** [comment]
@korneil  We hope we can push some progress on this. One thing we can do is to split this PR into multiple ones, and merge one operator at a time.

Here are some comments on ops:
- Activation and Concat should be readily handled by the original operators.
- [ ] CUDNN3DColvolution 
- [ ] 3DPooling

**Comment by winstywang** [comment]
Close for now. Please feel free to reopen it if having any update

**Pull request closed without merging**
