### PR TITLE
Change mkl fully connected operator to stateless.

### PR DESCRIPTION
**Pull request by jermainewang**
* Move LayerSetUp to constructor.
* Remove unused codes.
* Put resource members to local variables.

This allows Forward and Backward to be called standalone. So it is not necessary to call Forward before Backward.

### CODE REVIEW

**Comment by jermainewang** [comment]
@zhenlinluo @glingyan

**Comment by glingyan** [comment]
@jermainewang thanks, yes, FC could be stateless

**Comment by jermainewang** [comment]
We may need to rewrite other operators as well. It will be great if you guys could help us. BTW, @glingyan do you know which MKL operator definitely *cannot* be rewritten as stateless?

**Comment by glingyan** [comment]
@jermainewang, mkl2017  is a lot more complicated, some details is unsure without test
but MKL-DNN is stateless from design

**Comment by jermainewang** [comment]
@mli Should I ignore the perl-test?

**Comment by jermainewang** [comment]
GPU build failed with cuFFT link error. The PR didn't touch any GPU codes.

**Comment by jermainewang** [comment]
```
[ERROR] libdc1394 error: Failed to initialize libdc1394
[ERROR] error: java.lang.UnsatisfiedLinkError: /workspace/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: /workspace/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: undefined symbol: _ZN5mxnet2io22ImageDetNormalizeParam11__MANAGER__Ev
```
```
[ERROR] Caused by: java.lang.UnsatisfiedLinkError: /workspace/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: /workspace/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so: undefined symbol: _ZN5mxnet2io22ImageDetNormalizeParam11__MANAGER__Ev\
```

**Comment by jermainewang** [comment]
`ImageDet` ?

**Comment by cjolivier01** [comment]
Thank you!

**Pull request merged**
