### PR TITLE
python operator

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by tqchen** [comment]
Wait until @piiswrong updated the naming to NumpyOp and NativeOp on C++. Allow registeration

**Comment by tqchen** [comment]
@pluskid of potential  interest. This PR enables define operators using numpy.

**Comment by pluskid** [comment]
Great!

**Comment by jrabary** [comment]
Do we have the equivalent of `theano.tensor.grad` here, or do we always have to implement the backward function.

**Comment by tqchen** [comment]
It depends on the level of customization. The NumpyOp so far provides the ```atomic``` operators, in a sense that it can be used to compose together with other operators. So we will need a way to know its gradient. 

However, if you define operators such as exp, and relu. And you compose them together using
```
out = relu(exp(in))
```
You do not need to define the backward function of this composition.

**Pull request merged**
