### PR TITLE
[scala-package] generate source jars correctly and a large cleanup of pom files

### PR DESCRIPTION
**Pull request by CodingCat**
fix for https://github.com/dmlc/mxnet/issues/4893

@javelinjs  it seems that there are a lot of conflicts among the plugins....

This patch is ready for the review. There are four major changes here:

1. Move the dependency and plugin definition in the root pom.xml: I found that the submodules have a lot of shared dependencies/plugins, so it is not necessary to define in <dependencyManagement>/<pluginManagement> in root pom and reference them in submodules. A more efficient structure would be define them directly in root

2. Fix the source-jar generated issue...It seems that the latest version of maven-scala-plugin is the cause, and I usually use scala-maven-plugin in my other projects...so I replace maven-scala-plugin with scala-maven-plugin and everything becomes fine

3. fix some misconfigurations: some projects (spark/example) are configured with <packaging>pom</packaging> which is incorrect....

4. remove some unused/duplicate plugins

I published jars to my local repo

refer the dependency as

image

and try to check source in IntelliJ:

image

### CODE REVIEW

**Comment by javelinjs** [comment]
I agree with you, example and spark should not copy all the dependencies.

**Comment by CodingCat** [comment]
thanks, then I will move forward by changing that

**Comment by CodingCat** [comment]
Hi, @javelinjs @terrytangyuan  this patch is ready for the review, please help to check in your convenient time

**Comment by javelinjs** [comment]
Great, will check soon.

**Comment by javelinjs** [comment]
LGTM.

And shall we change this https://github.com/dmlc/mxnet/blob/master/scala-package/assembly/linux-x86_64-cpu/src/main/assembly/assembly.xml#L10 to `<include>ml.dmlc.mxnet:*:jar</include>` ? Currently Scala libraries are packed, which makes the assembly jars large.

**Comment by CodingCat** [comment]
I am not sure if that's a good idea, that's essentially excluding scala.* from classpath (if the user does not specify that in another place), did you try that?

**Comment by javelinjs** [comment]
When deploying to our internal maven repo, we remove scala. It makes jar light and reduces the risk of  dependency conflicts. The only shortcoming is that, users must specify the scala classpath.

**Comment by CodingCat** [comment]
@javelinjs my opinion is that, since they want to use assembly/fat jar...it means that they want to live with the large jar file size but not the trouble to put jar (not only of scala jars but also other depended libs) in some places and setup in the whole cluster....

If large jar size is not something to be accepted, the ***_core might be the option, I guess? your idea?

**Comment by javelinjs** [comment]
Sure, please update the branch then we can merge.

**Comment by CodingCat** [comment]
thanks, synced with master

**Comment by CodingCat** [comment]
@javelinjs mind merging this? I don't think the failed tests are related to the modifications here

**Comment by CodingCat** [comment]
thanks

**Pull request merged**
