### PR TITLE
NDSB1 example. Stratified sampling and generation of training curve graph

### PR DESCRIPTION
**Pull request by Gelu74**
sorry, this is a continuation of https://github.com/dmlc/mxnet/pull/1345, I messed up my fork branch and didn't manage to recover so I make this new PR. (I am new to git/github).

Following @piiswrong recommendation I removed pandas dependencies and made stratified sampling optional, I have also made a better arg parser.

Minor change to the NDSB1 example, adding stratified sampling instead of the "sed" command to split into train and validation.
Also added an example of how to generate the training curves from the log script based on #1302

### CODE REVIEW

**Comment by winstywang** [comment]
Could you fix some indentation issues in the PR? Indentations are not consistent in this PR.

**Comment by Gelu74** [comment]
I've corrected the indentation mistakes

**Comment by winstywang** [comment]
Update the codebase, then I can merge

**Comment by Gelu74** [comment]
done

**Pull request merged**
