### PR TITLE
Add BatchNorm support in lstm bucketing example

### PR DESCRIPTION
**Pull request by dianyancao**
I make some breaking changes in mxnet/python and c++ module:
1.Add BatchNorm to lstm.
2.Add layer normalization to BatchNorm.
3.Expose parameter names and auxiliary state names to python.
And some other changes for supporting BatchNorm in lstm.
Is it good for allowing duplicate argument names and auxiliary state names in a model?(Any variables with same names will share ndarrays?)
Pull request need your help.

### CODE REVIEW

**Comment by piiswrong** [comment]
The part that handles batchnorm aux names is fine.
But please rebase your code with latest master

**Comment by dianyancao** [comment]
I use the python keyword arguments to specify the moving_mean,moving_var names in BatchNorm and discard layer name prefix at auxiliary state names.This seems to be bad.
How to specify auxiliary state variables with same names in c++ side directly?

**Comment by dianyancao** [comment]
@piiswrong ,I follow the instruction in your link,rebase the code,but seems to be no effect.
Shoud I do rebase again?

**Comment by piiswrong** [comment]
you need to squash your commits.http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by dianyancao** [comment]
@piiswrong,I think that use aux names but not symbol variable in BatchNorm keyword parameters is not good.Waiting for your next round refactor.I will close the pull request.Thanks

**Pull request closed without merging**
