### PR TITLE
fix visualization bug

### PR DESCRIPTION
**Pull request by pluskid**
the heads (outputs nodes) is a list like `[[1, 0], [25, 0], [100, 0]]`. I don't know what the second 0 is, but the original code is buggy when visualizing RNN with multiple outputs. Julia side is already fixed. I'm not sure about R side.

### CODE REVIEW

**Comment by antinucleon** [comment]
The 0 is for rushing only output case. I guess multi-in is still not fixed and I will refactor it and fix it.

**Comment by pluskid** [comment]
@antinucleon What is the issue with multi-in? I think input nodes (data, label, weights, etc) are not drawn in the figure.

**Comment by antinucleon** [comment]
Yes that is my fault. I will refactor it, probably today.

**Comment by pluskid** [comment]
@antinucleon My feeling is that it is OK to draw without the parameters (weights, bias) because otherwise the figure will be too messy. But it might be helpful to draw the input nodes (data and labels). Though it might be difficult to decide which one is data and which is label as now we stop relying on the naming postfix. One option might be only draw them when the user supplied input shapes for doing input inference.

BTW: I also think it is super helpful to also include `node["name"]` in the label, even if `op != "null"`, as that will be super helpful for debugging -- I have the say, the GraphViz visualized graph is not always super easy to interpret, esp. for unrolled RNNs.

**Comment by tqchen** [comment]
@antinucleon please merge this in if you think is approperiate

**Comment by antinucleon** [comment]
I agree we don't need to weight in the graph, Iet's merge first

**Pull request merged**
