### PR TITLE
Keep references to the callback functions

### PR DESCRIPTION
**Pull request by vchuravy**
@piiswrong I only saw your comment after I was already done and I used a slightly different approach.

ref: #587  #554

### CODE REVIEW

**Comment by vchuravy** [comment]
@starimpact Could you test if either my PR or @piiswrong PR solves your problem?

**Comment by starimpact** [comment]
ok, let me have a try.

**Comment by starimpact** [comment]
I am sorry, but where can I get your commit?

**Comment by vchuravy** [comment]
````
cd to/your/local/mxnet/version
git remote add vchuravy https://github.com/vchuravy/mxnet.git
git fetch vchuravy
git checkout vc/py_gc

# make sure that your version of  the python bindings is up to date.
cd python 
python setup.py install
````

**Comment by starimpact** [comment]
ok , :smile:

**Comment by starimpact** [comment]
do not need to do ```make``` ?

**Comment by vchuravy** [comment]
Sine there are only changes to the python side of things no. But you should make sure that you then have the correct version installed

**Comment by starimpact** [comment]
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/home/mzhang/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/operator.py", line 167, in backward_entry
    self.backward(in_data=tensors[0], out_data=tensors[1],
SystemError: Objects/cellobject.c:24: bad argument to internal function
```

**Comment by starimpact** [comment]
maybe I should use C++ to implement the perators.

**Comment by starimpact** [comment]
I must use C++ now, since I must finish my project firstly.
Thank you very much. :smiley:

**Comment by starimpact** [comment]
We can do more try after my project.

**Comment by tqchen** [comment]
@piiswrong I guess this PR can be closed due to #587? Or is there anything that can be incorporated?

**Comment by vchuravy** [comment]
If @starimpact problem has been solved with #587 than we can indeed close this.

**Comment by starimpact** [comment]
I am sorry. I just right have completed the CPP version , it can work well .
the python version, I will take a time to do a test, but not now.
Really busy.
Really sorry.

**Comment by starimpact** [comment]
I am sorry. I just now have completed the CPP version , it can work well .
the python version, I will take a time to do a test, but not now.
Really busy.
Really sorry.

**Comment by vchuravy** [comment]
Closing for now

**Pull request closed without merging**
