### PR TITLE
[R] AWS S3 to host all pre-built binary packages.

### PR DESCRIPTION
**Pull request by thirdwing**
Please don't merge. I need opinions from R users.

I am considering using S3 to host all the pre-built pkgs for Windows/OSX users, because they are too large to host on github. The GPU-enabled pkg for Windows is more than 180 MB.

For CPU-only pkg:

```r
  cran <- getOption("repos")
  cran["dmlc"] <- "https://s3.amazonaws.com/mxnet-r/"
  options(repos = cran)
  install.packages("mxnet")
```

For GPU-enabled pkg:

```r
  cran <- getOption("repos")
  cran["dmlc"] <- "https://s3.amazonaws.com/mxnet-r/GPU"
  options(repos = cran)
  install.packages("mxnet")
```

### CODE REVIEW

**Comment by mli** [comment]
that's a good idea. we can put r packages with others into `https://s3.amazonaws.com/apache-mxnet/`

**Comment by thirdwing** [comment]
`apache-mxnet` should be a better name.

**Comment by szha** [comment]
@mli @thirdwing having a prefix specific for R can help organizing the repo. Some repo (e.g apt) requires a specific file structure which doesn't apply to other repos (pip), though I'm not familiar with how CRAN is set up. Having a namespace can help avoiding mixing those repos, so I'd suggest having a key prefix such as `/R/`for your use for CRAN repo (e.g. https://s3.amazonaws.com/apache-mxnet/R/...).

**Comment by thirdwing** [comment]
No idea about pip. You can find cran folder structure from https://github.com/dmlc/drat

**Comment by thirdwing** [comment]
I have uploaded the R pkg to `s3://apache-mxnet/R/` and it is working. @mli @szha 

```
> cran <- getOption("repos")
> cran["dmlc"] <- "https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/macosx/el-capitan/contrib/3.4/mxnet_0.10.1.tgz'
Content type 'application/x-tar' length 4995215 bytes (4.8 MB)
==================================================
downloaded 4.8 MB


The downloaded binary packages are in
	/var/folders/gd/hm095sqs6nlgqjhgc81jx1kxxp2h14/T//RtmpcBPKA3/downloaded_packages
```

**Pull request merged**
