### PR TITLE
regression_output Nx1 shaped label fix

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by winstywang** [comment]
Could you please try to test MNIST iter using this example? I find that the data layout of different iterator is different. We should try to consider all of them when implementing some general models.

**Comment by piiswrong** [comment]
I haven't used MNIST iter. How are they different? We probably should modify the iter to make them consistent?

**Comment by winstywang** [comment]
For example, you used the provide_data and provide_label which are specific to NDArrayIter in solver.py. I think we should not use them.

**Comment by pluskid** [comment]
I think provide_label and provide_data should be part of the data iter API now. For mx data iter they are already implemented.

**Comment by winstywang** [comment]
@pluskid I have tried MNIST iter. At least, it does not work.

**Comment by pluskid** [comment]
Which script Are you referring to? I was referring to mnist/mlp.py for example, the default model.py now also uses provide_label and data.

**Comment by winstywang** [comment]
hmm... I will try to investigate it tomorrow.

**Pull request merged**
