### PR TITLE
Add GRU in R

### PR DESCRIPTION
**Pull request by ziyeqinghan**
I add GRU model and some reusable APIs which are similar to the APIs for LSTM in [#2329].
- `mx.gru` Training GRU Unrolled Model
- `mx.gru.inference` Create a GRU Inference Model
- `mx.gru.forward` Forward function for GRU inference model

### CODE REVIEW

**Comment by thirdwing** [comment]
LGTM.

BTW, don't forget the mid-term evaluation.

**Comment by ziyeqinghan** [comment]
Thank you for you reminder. I have completed the mid-term evaluation right now. :)

**Comment by thirdwing** [comment]
@ziyeqinghan Please rebase against the master. I will merge it.

**Comment by ziyeqinghan** [comment]
I have rebased it.

**Pull request merged**
