### PR TITLE
[R] added API info for R functions

### PR DESCRIPTION
**Pull request by miguelgfierro**
Updated man in R package and rcppexport

### CODE REVIEW

**Comment by piiswrong** [comment]
We have changed the way we handle things under man/
please rebase your change on the NNVM branch and submit there.

**Comment by miguelgfierro** [comment]
I see no  man folder in that branch. Also the makefile is different and there is no command to compile only the roxygen. I don't know what to do with this PR. Can somebody explain to me the steps to follow?

**Comment by thirdwing** [comment]
Please see here: https://github.com/dmlc/mxnet/blob/nnvm/Makefile#L287

In NNVM branch, all man files will be generated when building. No need to `make rcppexport` any more.

**Comment by miguelgfierro** [comment]
Hi, I did a PR to nnvm brach, here it is #3949. I close this one.

**Pull request closed without merging**
