### PR TITLE
compute embed layer for all time index jointly

### PR DESCRIPTION
**Pull request by pluskid**
One potential factor that our char-lstm is slow **might** be because we compute the embedding for each time index separately. This PR is trying to modify the example to allow the embedding to be computed jointly. Not sure if we could get speed up here, but at least the data iter `provide_data` could be more compact.

- [x] modify `SliceChannel`
- [x] modify `Embedding`
- [x] modify `lstm_unroll`
- [x] modify bucketing io
- [x] modify bucketing executor for better memory sharing

Now we have some small speed up. In my local test, original was 500~600 samples/sec, with joint embedding, now we are around 600~700 samples/sec.

### CODE REVIEW

**Comment by pluskid** [comment]
There is still a slightly ugly `SplitChannel` + `Concat` + `Reshape` massage. Could be fixed if we have a `Transpose` operator. Left for future work.

**Comment by piiswrong** [comment]
Why do we need transpose fr this?

**Comment by pluskid** [comment]
becaue of the way we handle data path. it will depends on reshaping labels with col order or row order.

**Comment by piiswrong** [comment]
Don't quite get it but I think we have a swap axis.

**Comment by pluskid** [comment]
oh great. i will look into that tomorrow.

**Comment by pluskid** [comment]
Sorry it seems I tried squash too many times and the history is intertwined...

**Pull request merged**
