### PR TITLE
[Operator] add nearest neighboor up sampling

### PR DESCRIPTION
**Pull request by antinucleon**

### CODE REVIEW

**Comment by antinucleon** [comment]
@winstywang @piiswrong

**Comment by piiswrong** [comment]
Looks good to me.
BTW, I also need multi input upsampling (basically upsampling + concat) that takes n*c_1*w_1*h_1 ... n*c_k*w_k*h_k and output n*(c_1+...+c_k)*w*h. This is useful for multi resolution feature (i.e. hypercolumn) and saves one memory allocation.

**Comment by antinucleon** [comment]
I am out side and I will probably add bilinear upsampling in upsampling symbol. For multi input upsampling, can we use two symbol to do that? I

**Comment by piiswrong** [comment]
Using to symbols will result in doubling the memory used.

**Comment by antinucleon** [comment]
K, I only use this for GAN and double memoir doesn't hurt me seems. Also for bilinear seems we need to do similar thing.  I will use symbol first to make GAN work.

**Comment by winstywang** [comment]
seems good to me.
@piiswrong For hypercolumn, it is better to implement bilinear upsamping or use the deconv directly.

**Comment by vchuravy** [comment]
We could also implement bilinear upsampling with the deconvolution layer, but we would need a way to prevent changes to the weights. See https://github.com/dmlc/MXNet.jl/pull/34 for a first implementation on the Julia side.

**Pull request merged**
