### PR TITLE
add code to make mxnet do conv as caffe

### LINKED ISSUE #2997: Under CPU model, convert Caffe model to MXNET using convert tool failed
I have a lot of caffe model file which I trained before.  When I convert it into MXNET format with the model convert tools. googlnet trained from caffe show similar problem under CPU mode. 
It report following error
I0811 13:42:19.532551 20173 net.cpp:228] conv1 does not need backward computation.
I0811 13:42:19.532557 20173 net.cpp:228] input does not need backward computation.
I0811 13:42:19.532563 20173 net.cpp:270] This network produces output prob
I0811 13:42:19.532578 20173 net.cpp:283] Network initialization done.
I0811 13:42:19.540653 20173 net.cpp:761] Ignoring source layer data
I0811 13:42:19.543014 20173 net.cpp:761] Ignoring source layer loss
Swapping BGR of caffe into RGB in mxnet
converting layer conv1, wmat shape = (32, 3, 7, 7), bias shape = (32,)
converting layer conv2, wmat shape = (64, 32, 5, 5), bias shape = (64,)
converting layer conv3, wmat shape = (128, 64, 3, 3), bias shape = (128,)
converting layer fc6, wmat shape = (512, 6272), bias shape = (512,)
Traceback (most recent call last):
  File "../convert_model.py", line 108, in <module>
    main()
  File "../convert_model.py", line 90, in main
    wmat = wmat.reshape(arg_shape_dic[weight_name])
ValueError: total size of new array must be unchanged

It looks to me that the CPU mode code process the CONV and POOLING in a way different from Caffe.

### PR DESCRIPTION
**Pull request by ChenFengAndy**
This is to fix #2997 : Under CPU model, convert Caffe model to MXNET using convert tool failed 
added code to processing the calculating the boundary in same way as caffe
This feature is turn off by default in config.mk and cmake file. 
To make mxnet do conv is the same way as caffe:
change 
CAFFE_CONV_COMPATIABLE = 0 
to 
CAFFE_CONV_COMPATIABLE = 1

If will fix the error reported during model convert and make the converted caffe model run correctly under mxnet.

### CODE REVIEW

**Comment by winstywang** [comment]
@antinucleon Is it just the legacy codes of padding? I remember that caffe fixed this issue long long ago. In the latest caffe, they use the same infershape as ours. Please help me confirm this since it is related to the core codes.

BTW, the name CAFFE_CONV_COMPATIABLE is not acceptable since it also changes the way of pooling.

**Comment by ChenFengAndy** [comment]
@winstywang  you are right. I checked the latest caffe and their code is same as mxnet. 
I will re-train the model in mxnet.

**Comment by zhangqianhui** [comment]
@ChenFengAndy  meet the same problem , Have you dealed this problem?

**Comment by Darwin2011** [comment]
@ChenFengAndy @winstywang 
I also encounter this legacy issue in pooling layer which causes model convertor failded in Caffe Googlenet then compare the output size of pooling layer.

for caffe,
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L90
for mxnet, 
https://github.com/dmlc/mxnet/blob/master/src/operator/pooling-inl.h#L202

Any suggestion for this error? Thanks.

**Pull request closed without merging**
