### PR TITLE
Broadcast op + Update Submodules

### PR DESCRIPTION
**Pull request by sxjscience**
Based on https://github.com/dmlc/mxnet/pull/2039 . 

Two questions:
1. I'm not sure whether to add inplace-opt flag because  the validation of inplace-opt depends on the shape of lhs and rhs. E.g, (2,2) + (2, 1) can be optimized while (2,1) + (1,2) cannot.
2. Can we directly use the `broadcast_with_axis` operation in MShadow to simplify the implementation?

### CODE REVIEW

**Comment by piiswrong** [comment]
any idea what's causing this?
    return np.sum(x, keepdims=1, axis=tuple(axis))
TypeError: sum() got an unexpected keyword argument 'keepdims'

Some people seems to have this issue as well. Is it due to numpy version?

**Comment by sxjscience** [comment]
Have no idea about the problem... Let me test again.

**Comment by piiswrong** [comment]
https://github.com/numpy/numpy/issues/4537
looks like a numpy bug that's recently fixed. Has to do with masked arrays. Maybe try to copy them into normal arrays

**Comment by mli** [comment]
@sxjscience thanks for the followup. i was sick last week... we'd better remove the inplace flag. when the shape matched, inplace is fine. but it is problematic if the engine is not smart on that.

another thing i didn't do is writing test code for `mul`

@piiswrong that error is due to low version of numpy. i think we can remove `keepdims`

**Comment by mli** [comment]
i used broadcast rather than broadcast_with_axis because i guess the former has less index operators and may have better performance,

**Comment by sxjscience** [comment]
@mli I've removed the keepdims and inplace flags. Also I've tested broadcast_mul and the code is correct.

**Comment by piiswrong** [comment]
LGTM. @mli Could you have a look and lets merge

**Comment by mli** [comment]
lgtm

**Comment by piiswrong** [comment]
let's rebase and merge @sxjscience

**Comment by sxjscience** [comment]
I've rebased @piiswrong

**Comment by mli** [comment]
many thanks

**Pull request merged**
