### PR TITLE
Improve Caffe Importer

### PR DESCRIPTION
**Pull request by sbodenstein**
- added support for dilation param to Convolution layer
- added Deconvolution layer support
- factored out convolution parameter string calculation: used by both deconv and conv
- updated caffe.proto to latest from Caffe master (needed for dilation)
- input size now inferred from protobuf rather than always using (1,3,224,224)
- made naming more robust: caffe models with layer names containing '-' now work
- weight shapes: now support new Caffe shape format along with old format

### CODE REVIEW

**Comment by tmatas** [comment]
Cool!
When this PR will be merged I'm going to include the support for the global pooling layer

**Comment by tqchen** [comment]
@piiswrong @winstywang can you help review this PR?

**Comment by piiswrong** [comment]
looks good. I'm not very familiar with this part of code though

**Comment by mli** [comment]
@dongguosheng

**Comment by tmatas** [comment]
@sbodenstein, if you run `run.sh` with `vgg16` it does not work anymore

**Comment by sbodenstein** [comment]
@tmatas: Thats strange, I don't reproduce that. Can you try:
```
make clean
make
```
then try again?

**Comment by tmatas** [comment]
I reinstalled MxNet and I put this `caffe_pb2.py` file, but I got the same error as before
[caffe_pb2.py.zip](https://github.com/dmlc/mxnet/files/325487/caffe_pb2.py.zip)

**Comment by yangj1e** [comment]
I got the following error when I ran `./run.sh vgg16`, which worked well before this PR.

```
Traceback (most recent call last):
  File "/home/mxnet/tools/caffe_converter/convert_model.py", line 105, in <module>
    main()
  File "/home/mxnet/tools/caffe_converter/convert_model.py", line 66, in main
    if len(layer_blobs[0].shape.dim) > 0:
AttributeError: 'IntVec' object has no attribute 'dim'
```

**Comment by goodtogood** [comment]
got same error !

`I0623 09:49:53.505887 31472 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.

W0623 09:49:53.505887 31472 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.

Traceback (most recent call last):
  File "convert_model.py", line 106, in <module>
    main()
  File "convert_model.py", line 67, in main
    if len(layer_blobs[0].shape.dim) > 0:
AttributeError: 'IntVec' object has no attribute 'dim'`

**Pull request merged**
