### PR TITLE
[Op] global pool option

### PR DESCRIPTION
**Pull request by antinucleon**
For different input shape without generating new symbol.

### CODE REVIEW

**Comment by tmatas** [comment]
That sounds like cool stuff!
I would like to implement the operator "Global Average Pooling", as the last layer proposed in [SqueezeNet](http://arxiv.org/abs/1602.07360); does this operator solve the matter?

**Comment by antinucleon** [comment]
@tmatas Thank you! BTW, a small fix, "global average pooling" is proposed by Min Lin in his paper "Network in Network". Also for "squeeze network structure", we have used it for more than one year: https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_inception-bn-28-small.py

**Comment by iluvatar593** [comment]
Just a small question.
I noticed that trying to use this new option in a training I still have to specify the kernel size, even if in your implementation this field should be ignored if `global_pool` is set to `True`.

For example, training having a layer like this:
`mygpool = mx.symbol.Pooling(data=relu_conv10, stride=(1,1), pool_type="avg",global_pool="True")`
produces the error
`mxnet.base.MXNetError: Required parameter kernel of Shape(tuple) is not presented`

I'm quite sure that just adding the field `kernel(1,1)` to the layer makes everything correct but I'm wondering if it is better to allow to left the kernel field completely unspecified.
Also, specifying the kernel with size zero is still not allowed because of the `enforce_nonzero()`.

P.S. Where is the error message generated? I found the one related to the zero-size kernels in the `Check` method of the `FieldEntry` class at `mxnet/include/mxnet/base.h` but I cannot find the one related to the kernel field missing.

**Comment by antinucleon** [comment]
@iluvatar593 The kernel shape is required and defined in https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/parameter.h

If we allow empty shape, we need to do check logic in infer shape, which is acceptable, but I am a little bit lazy to do that, and I think it is fine to provide dummy kernel. 

If it is really annoying, I will fix it.

**Comment by tmatas** [comment]
For me the dummy kernel is ok. 
With the new operator I'm able to expand the `caffe_converter` with the following commit in `convert_symbol.py`

```
if param.global_pooling == True:
         param_string = "pad=(%d,%d), kernel=(1,1), stride=(1,1), global_pool='True'" %\
                    (param.pad, param.pad)
else
         #as before

```
and I am able to finish a conversion, but I'm not sure about the correctness.

I also noticed that if I add a `flatten` layer in the converted `symbol.json` the conversion is correct.

This means that I should add a `flatten` layer after a `global_pool` layer in the converter?

**Comment by antinucleon** [comment]
@tmatas Not necessary, because FullyConnected is able to handle 4D input to make it to 2D. So I will merge it first.

**Comment by tmatas** [comment]
@antinucleon thank you very much, it's clear now!

**Pull request merged**
