### PR TITLE
[CALL FOR TESTING] Single script to build and install mxnet for Windows with Python

### PR DESCRIPTION
**Pull request by howard0su**
This script is only one script to build and install mxnet with minimal dependency:
1. Visual Studio 2015 Community Edition
https://go.microsoft.com/fwlink/?LinkId=691978
2. Conda with Python 3.5
http://conda.pydata.org/miniconda.html

All the other dependencies are pulled via conda, like openblas, opencv. The script doesn't require modifying the files in Visual studio installation.

The script is largely copied from torch distro and modified for mxnet. It supports OpenBlas, MKL and CUDA. The script is tested only on a Windows 10 x64 version box with one single NVidia Cuda card. So far I don't have plan to support 32bit OS.

- [x] Support cudnn
- [x] Test MKL build
- [x] Test on various configuration
- [x] Code Cleanup
- [ ] Document update for Windows installation

### CODE REVIEW

**Comment by howard0su** [comment]
This pull request is *not* ready for merge

**Comment by howard0su** [comment]
I need more people to test this. I already done several rounds testing locally.

**Comment by piiswrong** [comment]
@hjk41 @miguelgfierro @thirdwing

**Comment by piiswrong** [comment]
since this won't break any existing functionalities we can merge it first and see if it works for everyone

**Pull request merged**
