### PR TITLE
Simplify ApplyPass interface

### PR DESCRIPTION
**Pull request by jermainewang**
Redo the PR.

### CODE REVIEW

**Comment by jermainewang** [comment]
@tqchen Hmm... I don't know what happened to these checks. The commits have been cleaned up.

**Comment by jermainewang** [comment]
That's wierd. I've updated the NNVM.

**Comment by jermainewang** [comment]
@tqchen @piiswrong need help.

**Comment by tqchen** [comment]
there is a bug in gradient node checking that is fixed by https://github.com/dmlc/mxnet/pull/3278, let us wait and see if that can be merged in, close this for now

**Comment by tqchen** [comment]
merged via https://github.com/dmlc/mxnet/pull/3290

**Pull request closed without merging**
