### PR TITLE
fix rmsprop optimizer

### PR DESCRIPTION
**Pull request by loofahcus**
Add the missing brackets in RMSProp optimizer.

### CODE REVIEW

**Comment by sxjscience** [comment]
@loofahcus Thanks very much for pointing this out! I find that the current test cases of the optimizer (https://github.com/dmlc/mxnet/blob/master/tests/python/unittest/test_optimizer.py) have not included the test for `wd`. Could you also add the test case for `wd`? Also, the test has not found the bug so there must be something wrong with the current test cases.

**Comment by loofahcus** [comment]
@sxjscience I have added the ```wd``` in test_optimizer.py. 
This bug would be found earlier with ```wd``` in the test cases.

**Comment by sxjscience** [comment]
@sbodenstein @piiswrong How about renaming the RMSProp to RMSPropAlex and adding the non-centered version of RMSProp (Original version in Hinton's slides) to the optimizer?

**Comment by sbodenstein** [comment]
@sxjscience: thats a great idea. The "Alex" version of RMSProp also has an extra state, taking more memory. So it would be similar to SGD and SGDMom updaters.

**Comment by piiswrong** [comment]
why was the test passing?

**Comment by sbodenstein** [comment]
@piiswrong: for the simple reason that there was no test for this particular case (using l2 reg).

**Comment by sxjscience** [comment]
@leezu Leo will do the refactoring.

**Pull request merged**
