### PR TITLE
Add nce loss example for word2vec and lstm

### PR DESCRIPTION
**Pull request by xlvector**
add readme

nce

add lstm example

### CODE REVIEW

**Comment by xlvector** [comment]
https://github.com/dmlc/mxnet/issues/2704

**Comment by sxjscience** [comment]
@xlvector Do you have time to add the latest version? We can rebase and merge this example.

**Comment by xlvector** [comment]
I will add it this weekend. Thanks!

**Comment by xlvector** [comment]
@sxjscience Seems last test is random failed because I only change README in last commit.

**Comment by sxjscience** [comment]
@xlvector Fine. Let's rebate and I'll merge it.

**Comment by xlvector** [comment]
@sxjscience I have tested it under CPU. Since I only use python, I think GPU will also works.

**Pull request merged**
