### PR TITLE
add states to modules

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by piiswrong** [comment]
@pluskid

**Comment by pluskid** [comment]
LGTM!

**Comment by piiswrong** [comment]
@pluskid I couldn't decide how to handle layout for states so I disabled merge_multi_context for now. Any suggestions?

**Comment by pluskid** [comment]
How is the layout information currently decided for the module outputs? Couldn't it be handled similarly?

**Comment by piiswrong** [comment]
yeah I guess that works.
Overall do you think it's a good idea to have states separate from inputs?

**Comment by pluskid** [comment]
Yes, I think the goal is to make an interface in which that the users do not need to explicitly deal with the states at least for the common use cases such as RNN/LSTMs. Also when separated, we might potentially be able to provide some utilities such as automatically forwarding some states to consecutive evaluation of the modules in the RNN case. It does make things a bit complicated as we have quite a few concepts: data, label, states, parameters. But I do not have a better solution in mind.

**Pull request merged**
