### PR TITLE
Topk and arange

### PR DESCRIPTION
**Pull request by sxjscience**
Continue after the rebase of NNVM.

### CODE REVIEW

**Comment by piiswrong** [comment]
@thirdwing A lot of R lint errors poped up after merging in master. Did you change anything in master?

**Comment by thirdwing** [comment]
I don't think so. I will check that tomorrow.

**Comment by sxjscience** [comment]
@piiswrong Seems the following code will not trigger error now:
```python
import mxnet as mx
a = mx.nd.ones((10,10))
b = mx.nd.sum(a, axxxxis=1)
```

**Comment by piiswrong** [comment]
>>> a = mx.nd.ones((10,10))
>>> b = mx.nd.sum(a, axxxxis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/mxnet/python/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/scratch/mxnet/python/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Cannot find argument 'axxxxis', Possible Arguments:
----------------
axis : Shape(tuple), optional, default=()
    Empty or unsigned or tuple. The axes to perform the reduction.If left empty, a global reduction will be performed.
keepdims : boolean, optional, default=False
    If true, the axis which is reduced is left in the result as dimension with size one.

**Comment by sxjscience** [comment]
@piiswrong OK, I find that I'm using Cython. ctypes works correctly.

**Comment by piiswrong** [comment]
Weird. Seems there is a bug with cython interface. @tqchen

**Comment by piiswrong** [comment]
what happened to R lint?

**Comment by sxjscience** [comment]
@piiswrong I find the python test fails because when I use `a = mx.nd.ones(shape=(10,10), ctx=mx.cpu(1))` , the context of a will still be `mx.cpu(0)`.

**Comment by piiswrong** [comment]
The r lint problem also popped up on my machine. It wasn't failing before. Does anyone know why suddenly we have errors like this:
R-package/src/symbol.h:6:  #ifndef header guard has wrong style, please use: R_PACKAGE_SRC_SYMBOL_H_  [build/header_guard] [5]

**Comment by piiswrong** [comment]
I found the issue. Was due to this change in dmlc-core: https://github.com/dmlc/dmlc-core/commit/a3b2fbeb360a15cfbfd5762dd62c1b81309f5c6a#diff-460cb56a7855c776ca8943d6f4f2c6c4
Will pr to dmlc-core to fix it. Please update dmlc-core afterwards

**Comment by piiswrong** [comment]
Please manually update dmlc-core to current master

**Comment by piiswrong** [comment]
looks ok now. Please fix lint

**Pull request closed without merging**
