### PR TITLE
update docs/

### PR DESCRIPTION
**Pull request by mli**
available at http://mxnet.dmlc.ml

compile with `cd docs; make html`

@tqchen got a bunch of errors for the python documents

```bash
/home/muli/work/mxnet/docs/packages/python/io.md:: WARNING: Pygments lexer name u'eval_rst' is not known
```

and no cpp and scala documents yet.

### CODE REVIEW

**Comment by mli** [comment]
@pluskid do you think it's possible to provide a script such as

```bash
git clone mxnet.jl
cp mxnet.jl/doc/*.md docs/packages/julia/
make html
```

so the julia documents can be also viewed at

http://mxnet.dmlc.ml/packages/julia/index.html

**Comment by tqchen** [comment]
You will need recommonmark parser on my private fork as markdown parser。
refer to the old doc configuration script

**Comment by mli** [comment]
already included https://github.com/dmlc/mxnet/blob/master/docs/conf.py#L26

**Comment by tqchen** [comment]
Also need to add Autostructify as transformer. See last lines of the
original conf

**Comment by mli** [comment]
fixed, see http://mxnet.dmlc.ml/packages/python/symbol.html

**Comment by tqchen** [comment]
seems to be good

**Comment by tqchen** [comment]
please retrigger the build after the lint on cu is merged

**Pull request merged**
