### PR TITLE
Update viz.graph for R

### PR DESCRIPTION
**Pull request by jeremiedb**
Fix the bugs associated with DiagrammeR by using visNetwork. 
Add the data shapes, similar to python visualization. 
MLP, Conv and RNN architectures tested.

### CODE REVIEW

**Comment by thirdwing** [comment]
@hetong007

**Comment by jeremiedb** [comment]
The build fail is due to the vignette: fiveMinutesNeuralNetwork.R

graph.viz now takes symbol as parameter so need to change line 28 to `graph.viz(model$symbol)` instead of `graph.viz(model$symbol$as.json())`. 
Other vignettes such as MNIST and RNNchar could now display the network if desired. 

DESCRIPTION file should as well be updated to import visNetwork(>= 1.0.3). 

Should I submit a new pull with the above updates?

**Comment by piiswrong** [comment]
can this be merged? @thirdwing

**Comment by thirdwing** [comment]
This visualization part is not by me. It will be better to have @hetong007 or @pommedeterresautee to look at it.

**Comment by hetong007** [comment]
Sorry for delayed reply. Just tested it and I think it can be merged.

**Pull request merged**
