### PR TITLE
[WIP] Fix amalgamation

### PR DESCRIPTION
**Pull request by antinucleon**
- [x] Compile
- [x] Add support for MKLDNN
- [x] Add support for NNPACK
- [ ] Test with pretrained model
- [ ] Add test to jekins

### CODE REVIEW

**Comment by mli** [comment]
we also need to test mkldnn for amalgamation

@arank

**Comment by antinucleon** [comment]
Updated task

**Comment by futurely** [comment]
MKLdnn Integration Patch to improve issue #2986(call for cpu performance)
https://github.com/dmlc/mxnet/pull/3438

**Comment by antinucleon** [comment]
NNPACK pc support is done, but not test on mobile yet

**Comment by tqchen** [comment]
@antinucleon can we add a testcase to ensure amga always compile?

**Comment by piiswrong** [comment]
updates?

**Pull request closed without merging**
