### PR TITLE
Add test with MKL option

### PR DESCRIPTION
**Pull request by lxn2**
Allows us to add a job on CPU that tests with MKL.

### CODE REVIEW

**Comment by lxn2** [comment]
@szha @piiswrong I added the MKL job (disabled it after it finished) and Python tests passed.

**Comment by piiswrong** [comment]
@javelinjs @CodingCat @Ldpe2G Any idea what's going on with the scala test fails with stod throwing invalid_argument?

**Comment by javelinjs** [comment]
Does it train with python? Since I didn't see training test cases for python on jenkins log outputs.

**Comment by Ldpe2G** [comment]
@piiswrong @javelinjs  I think the problem may be caused by this commit #5151, 
I have tried git reset to  #5216 and the scalatest passed.
Then I reset back to #5151 and the scalatest failed.

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/pull/5151/files#diff-4ae864e473b6f349d054aad47522e2e0R78
you need to do this change for scala too.

**Comment by javelinjs** [comment]
thank @Ldpe2G  https://github.com/dmlc/mxnet/pull/5248

**Comment by lxn2** [comment]
@javelinjs Can you search for "BUILD python_test" and "BUILD python3_test" in the Jenkins log and verify that's what you're looking for? Do I have to do "sudo python setup.py install" or is just adding pythonpath okay?

**Comment by javelinjs** [comment]
@lxn2 Depeng has fixed the issue, please update the branch, the scalatest should be passed now.

**Comment by lxn2** [comment]
run tests

**Comment by lxn2** [comment]
@javelinjs the scalatest passed for the regular cpu run, but not for cpu w/ MKL?

**Comment by javelinjs** [comment]
With MKL, the MNIST training accuracy with one epoch falls to 0.098, while it is 0.92 for cpu. Have you tested this with python?

**Comment by szha** [comment]
@glingyan @zhenlinluo

**Comment by glingyan** [comment]
I tested before upstream , will double check with latest

**Comment by glingyan** [comment]
INFO:root:Start training with [cpu(0)]
Start training with [cpu(0)]
**MKL Build:20170209**
INFO:root:Epoch[0] Resetting Data Iterator
Epoch[0] Resetting Data Iterator
INFO:root:Epoch[0] Time cost=3.871
Epoch[0] Time cost=3.871
INFO:root:Epoch[0] Validation-accuracy=0.961000
Epoch[0] Validation-accuracy=0.961000
INFO:root:Finish fit...
Finish fit...
INFO:root:Finish predict...
Finish predict...
INFO:root:final accuracy = 0.960900
final accuracy = 0.960900

**Comment by glingyan** [comment]
just do a latest clean checkout , no problem found

**Comment by javelinjs** [comment]
I'll find a linux server to see if I can reproduce the test results.

**Comment by szha** [comment]
@javelinjs @lxn2 MKL python unit tests have been fixed in #5085 #5144, just FYI

**Comment by szha** [comment]
@glingyan @javelinjs  ```ScalaTest-main-running-ConvSuite``` seems to be still failing on mnist training.

**Comment by piiswrong** [comment]
Can one of the admins verify this patch?

**Comment by glingyan** [comment]
please also provide crash log
setup scala env is painful for network issue

**Comment by glingyan** [comment]
running on latest source code
[16:47:00] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28)
[16:47:00] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28)
2017-03-08 16:47:00,501 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.FeedForward] [DEBUG] - Start training on multi-device
2017-03-08 16:47:00,504 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.DataParallelExecutorManager] [INFO] - Start training with [cpu(0)]
2017-03-08 16:47:03,198 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.Model] [INFO] - Epoch[0] Train-accuracy=0.9338
2017-03-08 16:47:03,199 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.Model] [INFO] - Epoch[0] Time cost=2675
2017-03-08 16:47:03,295 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.Model] [INFO] - Epoch[0] Validation-accuracy=0.9508
2017-03-08 16:47:03,303 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.train.ConvSuite] [INFO] - Finish fit ...
2017-03-08 16:47:03,405 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.train.ConvSuite] [INFO] - Finish predict ...
2017-03-08 16:47:03,430 [ScalaTest-main-running-ConvSuite] [ml.dmlc.mxnet.train.ConvSuite] [INFO] - Final accuracy = 0.9508

**Comment by glingyan** [comment]
no problem at all

**Comment by javelinjs** [comment]
That's wired, @piiswrong can we manually run the jenkins test again?

**Comment by mli** [comment]
closing this pr now. will open a new one for mkl ci testing

**Pull request closed without merging**
