### PR TITLE
fix plot_network bottom data drawing

### PR DESCRIPTION
**Pull request by taoari**
Fix `mx.viz.plot_network()` function that does not plot the bottom data blob.

### CODE REVIEW

**Comment by piiswrong** [comment]
mxnet doesn't differentiate between input and weight. Is this going to plot all weights?

**Comment by taoari** [comment]
@piiswrong It will only additionally plot the bottom data, for example:

```
def get_mlp():
    """
    multi-layer perceptron
    """
    data = mx.symbol.Variable('data')
    fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=128)
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
    fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 64)
    act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
    fc3  = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=10)
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
    return mlp
```

should plot like:

(data) -> (FullyConnected) -> (Activation) -> (FullyConnected) -> (Activation) -> (FullyConnected) -> (SoftmaxOutput) 

However, the original version plot like:

 (FullyConnected) -> (Activation) -> (FullyConnected) -> (Activation) -> (FullyConnected) -> (SoftmaxOutput) 

It lacks plotting "(data) -> "

BTW, how can I directly insert a picture in the comment?
￼

**Comment by winstywang** [comment]
@taoari This PR is good to merge. Please update to the latest master to merge.

**Comment by winstywang** [comment]
You may need to update again...

**Pull request merged**
