### PR TITLE
fix UnicodeDecodeError

### PR DESCRIPTION
**Pull request by kice**
Remove unexpected character

### CODE REVIEW

**Comment by kice** [comment]
Issue: https://github.com/dmlc/mxnet/issues/5848

fix another file beside https://github.com/dmlc/mxnet/pull/5908

**Comment by piiswrong** [comment]
@mli @zackchase Can we enforce some kind of unicode check in lint?

**Comment by kice** [comment]
Maybe we can look every byte to check if it is Printable characters (and maybe include TAB character)?

https://en.wikipedia.org/wiki/ASCII#Printable_characters

**Comment by yajiedesign** [comment]
good.I changed this file but forgot to submit it in https://github.com/dmlc/mxnet/pull/5908

**Pull request merged**
