### PR TITLE
ENH python metrics added, fixed

### PR DESCRIPTION
**Pull request by jmschrei**
Python evaluation metrics have been updated. In addition to mean squared error and F1 being added, array size checks have been fixed for MAE and RMSE. All metrics can now be called using strings. More useful error messages have been added, and assertions have been replaced with a reused function. This solves issues #1163 and #1107.

### CODE REVIEW

**Comment by tqchen** [comment]
can you fix the test case here? https://travis-ci.org/dmlc/mxnet/jobs/100461695

**Comment by jmschrei** [comment]
The nosetests run on my computer, so I don't really know how to fix it. Do you have any insight?

**Comment by jmschrei** [comment]
Looks like the lint check is still failing, but the python tests are passing now.

**Comment by tqchen** [comment]
You can reproduce lint check locally via ```make lint```

**Comment by jmschrei** [comment]
32 python files fail the lint test locally. Is this expected?

**Comment by tqchen** [comment]
Hmm, could due to pylint version so it behave differently. I guess we only need to fix the error reported by travis for now

**Comment by jmschrei** [comment]
Looks like everything is finally massing @tqchen

**Pull request merged**
