### PR TITLE
Separate load and save model prefixes

### PR DESCRIPTION
**Pull request by futurely**

### CODE REVIEW

**Comment by winstywang** [comment]
Update and ready to merge

**Comment by winstywang** [comment]
Sorry need to update again

**Comment by winstywang** [comment]
Still cannot merge. Could you check your branch is updated with the latest one?

**Comment by tqchen** [comment]
I is recommended to use the rebase approach to update with master and to combine the less meaningful commits, as mentioned in http://mxnet.readthedocs.org/en/latest/contribute.html#git-workflow-howtos

**Pull request merged**
