### PR TITLE
Syncing up perl-package to current state of the Python interface

### PR DESCRIPTION
**Pull request by sergeykolychev**
@piiswrong 
Notable additions:
a) high level RNN API
b) initializers reworked to include InitDesc
c) new attribute for variables __init__, holds jsonified initializer constructor parameters
d) miscellaneous improvements

### CODE REVIEW

**Comment by sergeykolychev** [comment]
@piiswrong Thanks for cancelling the travis checks on intermediate commits, wish there was some option to to trigger new build on every commit to the pull request. In any case now the pull in the state that I consider mergeable and I'll not be updating it.

**Comment by sergeykolychev** [comment]
@piiswrong the perl build failed because of connectivity error on travis part when uploading cache data after all tests successfully passed, I'm merging master in once more.

**Comment by sergeykolychev** [comment]
@piiswrong Is there a particular reason why this is not merged yet ? the tests are happy.

**Comment by sergeykolychev** [comment]
@mli Can you please see if this mergeable ? With this pull I'm getting perl current and would like to start on writing docs, tests, examples, html in order to have perl interface visible on mxnet.io

**Comment by piiswrong** [comment]
Just waiting for test to finish. Merged

**Pull request merged**
