### PR TITLE
refactor cachedop

### PR DESCRIPTION
**Pull request by piiswrong**
@sergeykolychev I refactored CachedOp and revered changes in perl.

### CODE REVIEW

**Comment by sergeykolychev** [comment]
@piiswrong are you ok with me just redoing the cachedop for Perl to make it compatible with your changes without​ yanking whole pull away ?

**Comment by sergeykolychev** [comment]
On other hand the errors in the Perl tests are superficial , no tests failed just the number of tests run need adjustment , I will create a pull against this pull with the tests fix and will worry about the cachedop later. Do you plan to redo it or you consider it's stable this time ? I'll wait with porting of your changes if it's still in flux. Thanks

**Comment by sergeykolychev** [comment]
@piiswrong https://github.com/piiswrong/mxnet/pull/4 this fixes the perl tests on this branch.

**Comment by piiswrong** [comment]
I only removed the cachedop for perl.

Its probably better to wait for a couple weeks before reintroducing it to perl.

Thanks

**Comment by sergeykolychev** [comment]
Ok, sure, I'll wait.

**Comment by sergeykolychev** [comment]
@piiswrong looks like my test number fix got somehow removed from your branch, you'll need to reapply.

**Pull request merged**
