### PR TITLE
Update CMake so it finds OpenBLAS correctly on Windows

### PR DESCRIPTION
**Pull request by hjk41**

### CODE REVIEW

**Comment by piiswrong** [comment]
is long long guaranteed to be int64 on across platforms?

**Comment by hjk41** [comment]
it is guaranteed to be at least 64 bit in C99 and C++

On Tue, Mar 1, 2016 at 3:41 PM, Eric Junyuan Xie <notifications@github.com>
wrote:

> is long long guaranteed to be int64 on across platforms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/pull/1548#issuecomment-190598015>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
please use // NOLINT(*) comment to surpress the warning

**Comment by tqchen** [comment]
@hjk41 can you update the status on this?

**Pull request merged**
