### PR TITLE
module api formatting fixes

### PR DESCRIPTION
**Pull request by Roshrini**
Minor typos and formatting fixes for Module API. 
@madjam @piiswrong @mli Please review and merge.

### CODE REVIEW

**Comment by piiswrong** [comment]
Are you sure this would render better?

**Comment by Roshrini** [comment]
I built it locally and checked. Looks good. 
screen shot 2017-05-23 at 12 10 05 pm

**Comment by piiswrong** [comment]
ok. Could you put a space after every `#`

**Comment by Roshrini** [comment]
@piiswrong Done.

**Pull request merged**
