### PR TITLE
Move all the unittest_tools to the main package

### PR DESCRIPTION
**Pull request by sxjscience**
Move all the unittest_tools to the main package.

Enable outputing a dictionary for executors.

Remove old check_utils

Enable AddTo and gradient w.r.t ROI

### CODE REVIEW

**Comment by sxjscience** [comment]
@precedenceguo Could you review the change of ROI-Pooling for me? I've changed Backward to BackwardAcc and also gives zero-gradient for ROI.

**Comment by sxjscience** [comment]
@piiswrong @tqchen @antinucleon I've moved the testing functions to the main package so the user can directly call these functions to check their own operator.

**Comment by piiswrong** [comment]
I think this is a legit change.
Although test_utils may be a better name

**Comment by precedenceguo** [comment]
@sxjscience Yes there is no clear way to give gradient for ROI. I think there is no problem with the roipooling change. I tested on a trained model and a training code to verify this.

**Comment by sxjscience** [comment]
@precedenceguo Thanks! I'll merge this in.

**Pull request merged**
