### PR TITLE
Add several optimizer in R

### PR DESCRIPTION
**Pull request by ziyeqinghan**
Add `Adam`, `AdaGrad`, `AdaDelta` optimizer in R and test them in [mnist classification](https://github.com/dmlc/mxnet/tree/master/example/image-classification). Part of the test results are below.

- `Adam` optimizer with parameters `learning.rate=0.001`, `optimizer="adam"`
```
Batch [50] Train-accuracy=0.414375
Batch [100] Train-accuracy=0.571875
...
Batch [400] Train-accuracy=0.77541015625
Batch [450] Train-accuracy=0.788229166666667
[1] Train-accuracy=0.791672243040685
[1] Validation-accuracy=0.900841346153846
Batch [50] Train-accuracy=0.9034375
...
[5] Train-accuracy=0.965745192307692
[5] Validation-accuracy=0.96474358974359
Batch [50] Train-accuracy=0.971875
...
Batch [450] Train-accuracy=0.986423611111111
[10] Train-accuracy=0.986378205128205
[10] Validation-accuracy=0.972956730769231
```

- `AdaGrad` optimizer with parameters `learning.rate=0.05`, `optimizer="adagrad"`
```
Batch [50] Train-accuracy=0.576875
Batch [100] Train-accuracy=0.716484375
...
Batch [450] Train-accuracy=0.877534722222222
[1] Train-accuracy=0.879901632762313
[1] Validation-accuracy=0.947015224358974
Batch [50] Train-accuracy=0.94875
...
Batch [450] Train-accuracy=0.974982638888889
[5] Train-accuracy=0.975060096153846
[5] Validation-accuracy=0.969350961538462
Batch [50] Train-accuracy=0.9771875
...
Batch [450] Train-accuracy=0.984826388888889
[10] Train-accuracy=0.984909188034188
[10] Validation-accuracy=0.973056891025641
```

- `AdaDelta` optimizer with parameters `optimizer="adam"`
```
Batch [50] Train-accuracy=0.116875
Batch [100] Train-accuracy=0.24375
Batch [150] Train-accuracy=0.395208333333333
...
Batch [400] Train-accuracy=0.708984375
Batch [450] Train-accuracy=0.733871527777778
[1] Train-accuracy=0.741652168094218
[1] Validation-accuracy=0.950120192307692
Batch [50] Train-accuracy=0.9453125
...
[5] Train-accuracy=0.984124599358974
[5] Validation-accuracy=0.973657852564103
Batch [50] Train-accuracy=0.989375
...
Batch [450] Train-accuracy=0.994201388888889
[10] Train-accuracy=0.994190705128205
[10] Validation-accuracy=0.975460737179487
```

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Looks great! Please resolve conflicts and we'll merge.

**Comment by ziyeqinghan** [comment]
The branch is rebased.

**Comment by terrytangyuan** [comment]
I cannot merge it if it doesn't pass tests :-(

**Comment by ziyeqinghan** [comment]
I don't know why `cpp_test` failed because I didn't change the c/c++ code. Could you gave me some suggestions? thank you so much!

**Comment by terrytangyuan** [comment]
@tqchen Could you take a look? I don't have permission to merge this and cannot rerun Travis for some reason

**Comment by terrytangyuan** [comment]
I rerun the tests but then it's outdated again...

**Comment by ziyeqinghan** [comment]
The branch is rebased again.

**Comment by terrytangyuan** [comment]
Thanks!

**Pull request merged**
