### PR TITLE
[R] ImageNet training with ResNet-v2, Inception-resnet and others for R

### PR DESCRIPTION
**Pull request by miguelgfierro**
Several things to notice, I didn't put all CNN architectures, only the ones that are wroking for me. The default network is ResNet-18, with it I got a top-5 accuracy of 93% using Azure VMs with 4 GPUs.

### CODE REVIEW

**Comment by piiswrong** [comment]
@thirdwing Is this good for merging?
@miguelgfierro Please rebase and fix conflict

**Comment by thirdwing** [comment]
It is OK and I tried to merge.

**Comment by tornadomeet** [comment]
cool, ResNet-18 is 2% absolute higher than i trained!

**Comment by miguelgfierro** [comment]
@tornadomeet I'm tryining also ResNet152 to see if I'm able to get to more than 95%, which is the human level performance. I'll tell you if I get it

**Comment by miguelgfierro** [comment]
The test failed in python:

```python
ld: warning: directory not found for option '-L/Users/travis/usr/local/cuda-7.5/lib64'

ld: warning: directory not found for option '-L/Users/travis/usr/lib/x86_64-linux-gnu'

/usr/local/opt/python/bin/python2.7: No module named nose
```

I think it doesn't have to do with the R code

**Pull request merged**
