### PR TITLE
concat supports dimension 0-3

### PR DESCRIPTION
**Pull request by yang1fan2**
@tqchen  Sorry for pulling request again. I met several problems on rebasing and may not be able to fix it. So I created another branch.

Thanks;

### CODE REVIEW

**Comment by piiswrong** [comment]
Does this support any dimension or just dimension 1-4? 
I think  you can handle concating at dim i by reshaping it into a 3d tensor like (ndim[0]*...*ndim[i-1], ndim[i], ndim[i+1]*...*ndim[N])

**Comment by yang1fan2** [comment]
It supports dimension 0-3

**Comment by tqchen** [comment]
Thanks! Merging. In future, let us think about how to support general cases without switch, take a look at how swapaxis is implemented, we should get some idea

**Comment by tqchen** [comment]
@yang1fan2 let us know if you would like to improve it a bit further:)

**Comment by tqchen** [comment]
Have added you to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md please feel free to update more details about yourself, and contribute more to mxnet!

**Pull request merged**
