### PR TITLE
add zero propagation

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by piiswrong** [comment]
@tqchen

**Comment by piiswrong** [comment]
@Ldpe2G @javelinjs Any idea why scala is segfaulting? Looks like its make that threw segfault

**Comment by Ldpe2G** [comment]
@piiswrong can not figure out where cause this, seems this problem exist for quiet a long time. 
may be you can comment signal(SIGSEGV, segfault_logger); temporarily
@javelinjs Any idea?

**Comment by Ldpe2G** [comment]
@piiswrong 
in initialize.cc, I try the following modification and it works:
change 
```bash
static LibraryInitializer __library_init;
```
to
```bash
static LibraryInitializer& getInstance()
{
    static LibraryInitializer __library_init;
    return __library_init;
}
```

**Pull request closed without merging**
