### PR TITLE
start work on the docs

### PR DESCRIPTION
**Pull request by yuweiw823**
Changes made on front-end, especially navigation bar, index page banner, and language selector.

### CODE REVIEW

**Comment by piiswrong** [comment]
@mli @tqchen

**Comment by mli** [comment]
any preview?

**Comment by piiswrong** [comment]
no server. try pull it and build?

**Comment by mli** [comment]
you can add a new website at readthedocs.org for https://github.com/yuweiw823/mxnet e.g. https://readthedocs.org/projects/mxnet-mli/

**Comment by yuweiw823** [comment]
build error using readthedocs.org :(, have no idea where does the **recommonmark** come from? any suggestions?

File "/home/docs/checkouts/readthedocs.org/user_builds/mxnet-docs/checkouts/enhance-css/**recommonmark/recommonmark/states.py**", line 117, in run_role
    rawtext=str(content),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

**Comment by tqchen** [comment]
the recommonmark was clone from my repo https://github.com/tqchen/recommonmark

**Comment by piiswrong** [comment]
@tqchen PR proposed

**Comment by tqchen** [comment]
@piiswrong anyway to get a preview?

**Comment by piiswrong** [comment]
there seems to be encoding problems with the chinese docs.
Are you sure current master can build?

**Comment by tqchen** [comment]
no, current master breaks.

**Comment by piiswrong** [comment]
http://mxnet.dmlc.ml/en/latest//zh/index.html
We should have 5 chinese doc pages but there are only 2 on web.
So the doc site haven't been building for a long time. Could you look into it?

**Comment by tqchen** [comment]
seems was due to utf-8 encoding problem and improper handling in recommonmark,

**Comment by tqchen** [comment]
@piiswrong I fixed my repo and the doc should now build with the lastest pull

**Comment by piiswrong** [comment]
@tqchen Are you sure it can build on readthedocs?

**Comment by tqchen** [comment]
Yes, the last build passed

**Comment by piiswrong** [comment]
@tqchen  https://mxnet.readthedocs.io/en/latest//zh/index.html
still doesn't show the new chinese docs

**Comment by tqchen** [comment]
@piiswrong this was because the index was not automatically generated see https://github.com/dmlc/mxnet/blob/master/docs/zh/index.md

However, check http://mxnet.readthedocs.io/en/latest//zh/system/index.html

**Comment by tqchen** [comment]
@piiswrong Please rebase and see if we can merge it in first

**Comment by mli** [comment]
is the preview site available now?

**Comment by mli** [comment]
all recent builds are failed

https://readthedocs.org/projects/mxnet/builds/

**Comment by tqchen** [comment]
I fixed the build

**Comment by yuweiw823** [comment]
Thanks a lot 👍  :)

**Comment by tqchen** [comment]
Here is the new doc. Everything looks to be good. The only bad thing was this python page

http://mxnet.readthedocs.io/en/latest/packages/python/index.html

**Comment by yuweiw823** [comment]
The customized css file mxnet.css sometimes has loading problem for the online version. I'm looking into it.

**Pull request merged**
