### PR TITLE
Update deconvolution-inl.h. Change the condition control statement in InferPad. Merge differences between v0.8 and v0.9.

### PR DESCRIPTION
**Pull request by lordofgod**
There seems to be a bug at the condition control statement in InferPad. Original version(v0.9) only use target_shape.ndim to decide the calculation of pad. But we find even the target_shape.ndim is not zero, values of target_shape can be zero. When we load v0.8 model with v0.9, this may cause error calculation of pad.

### CODE REVIEW

**Comment by piiswrong** [comment]
please fix lint

**Comment by piiswrong** [comment]
Done processing src/operator/swapaxis.cc
Done processing src/operator/l2_normalization.cc
src/operator/deconvolution-inl.h:91:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/operator/deconvolution-inl.h:91:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
src/operator/deconvolution-inl.h:93:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/operator/deconvolution-inl.h:96:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/operator/deconvolution-inl.h:98:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/operator/deconvolution-inl.h:100:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/operator/deconvolution-inl.h:105:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/operator/deconvolution-inl.h:105:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Done processing src/operator/deconvolution-inl.h

**Comment by mli** [comment]
I'm going to close the PR since there is no activity for more than 2 months. But please feel free to re-open it and update with the master.

**Comment by piiswrong** [comment]
@mli This needs to be fixed. If the original author doesn't respond can we have someone to take it over.

**Pull request merged**
