### PR TITLE
Add simple equal operator

### PR DESCRIPTION
**Pull request by jermainewang**
@sxjscience Please have a look at this simple implementation.

### CODE REVIEW

**Comment by piiswrong** [comment]
This should be unary.

**Comment by jermainewang** [comment]
It is binary. The output is a 0-1 array.

**Comment by piiswrong** [comment]
ok. I see. LGTM

**Comment by piiswrong** [comment]
also add .__eq__ for python side?

**Comment by jermainewang** [comment]
Done.

**Comment by sxjscience** [comment]
Looks good to me.

**Pull request merged**
