### PR TITLE
Module tutorial prerequisite section modified

### PR DESCRIPTION
**Pull request by Roshrini**
@piiswrong Can you merge this? Seems like build failure is not due to this PR.

### CODE REVIEW

**Comment by piiswrong** [comment]
as I mentioned in another PR. Put common prerequisite in tutorial index page

**Comment by nswamy** [comment]
@piiswrong Please see my comment here https://github.com/dmlc/mxnet/pull/6580#issuecomment-307477023.
Can you please wait for a discussion(at least an answer) before you decide to the close PR?

**Comment by piiswrong** [comment]
There are too many PRs doing the same work.

It's flooding the test server and making discussions fragmented. Please
condense them into one per person per topic


Naveen Swamy <notifications@github.com>于2017年6月9日 周五下午12:46写道：

**Comment by nswamy** [comment]
@piiswrong we should improve the process of PRs being tested, it's been discussed in the past and we can have another discussion later.  There are multiple people working to make sure the tutorials work seamlessly on the platforms that MXNet supports, so you see multiple PRs. let's move these opinion based discussions to slack channel in the future.

**Pull request closed without merging**
