### PR TITLE
update im2rec.cc for random short edge

### PR DESCRIPTION
**Pull request by tornadomeet**
This is the scale augmentation used in the original paper VGG, Resnet-v1, Resnet-v2, when training with imagenet

### CODE REVIEW

**Comment by piiswrong** [comment]
This is done by ImageRecordIter

**Comment by tornadomeet** [comment]
@piiswrong  Do you mean ```min_random_scale ``` and ```max_random_scale``` in ImageRecordIter? i had used it to train resnet-v2 on imagent, i think there is a little difference with using ```min_size``` and ```max_size``` done in the ```im2rec``` side, say that  we want to random resize the short edge to [256, 480], which is the default scale augment done in VGG, Resnet-v1, Resnet-v2.  
*  if set```resize=256``` in ```im2rec```, then the short edge is resized to 256, and this will bring in information losing( when the short edge is larger than 256 ). so if we set ```min_random_scale=1.0``` and ```max_random_scale=480/256```, it is sure that the short edge is random with [256, 480], but it need resize again from the information losing roi.  
* if set ```unchanged=1``` in ```im2rec```, then the information is perfect retained, but the vale of ```min_random_scale``` and ```max_random_scale``` is dynamic changed. another, this will make the size .rec file too large.

**Comment by piiswrong** [comment]
Still doesn't make much sense to randomize here. You can resize to max_size instead

**Comment by tornadomeet** [comment]
the .rec file is too big if resize to max_size.

**Pull request closed without merging**
