### PR TITLE
Enable DTypes in deconvolution

### PR DESCRIPTION
**Pull request by vchuravy**
Ref #2302

### CODE REVIEW

**Comment by piiswrong** [comment]
could you add a type consistency check in tests/python/gpu/test_operator_gpu.py?

**Comment by piiswrong** [comment]
otherwise lgtm

**Comment by vchuravy** [comment]
done.

**Comment by vchuravy** [comment]
rebased and ready to merge.

**Comment by piiswrong** [comment]
Need to rebase again...
Linear merging is indeed becoming a problem

**Comment by vchuravy** [comment]
Yes it indeed is. It especially slows you down if you are in a different timezone, than the majority of people with merge rights.

**Comment by vchuravy** [comment]
@piiswrong rebased

**Comment by piiswrong** [comment]
@tqchen good for merging after test finishes

**Pull request merged**
