### PR TITLE
Sum with axis full support

### PR DESCRIPTION
**Pull request by sxjscience**
Directly support multiple axes + keepdims in C++. `sum_axis`, `max_axis` and `min_axis` can be depreciated. Refer to https://github.com/dmlc/mxnet/issues/2197 .

Also, the `mx.nd.sum(a)` will now return a NDArray with shape `(1,)`. The previous sum operator implemented using Python will cast it to a float (See https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L875-L878). I'm not sure whether this change will affect other packages like Minpy.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @jermainewang

**Comment by tqchen** [comment]
Let us remove the deprecated ops after one week it get merged. In the future, let us always make the op naming convention be as compatible as possible as numpy

**Comment by piiswrong** [comment]
Why ndarray instead of float?

**Comment by tqchen** [comment]
ndarray is async, so it won't force a sync point unless asscalar is called

**Comment by tqchen** [comment]
thanks this is great! Can we do similar renaming for broadcast_axis, maybe numpy.broadcast_to?

**Comment by sxjscience** [comment]
@tqchen `broadcast_axis` is useful when we want to broadcast along a single axis, e.g, `b = broadcast_axis(a, axis=1, size=100)`. I can add another `broadcast_to` operator that is similar to `numpy.broadcast_to`. We can also allow zeros in the shape argument, which means to keep the original dimension (like http://mxnet.readthedocs.io/en/latest/packages/python/symbol.html#mxnet.symbol.Reshape).

**Pull request merged**
