### PR TITLE
add mutliprocessing

### PR DESCRIPTION
**Pull request by junranhe**
1)modify to use multiprocessing
2)add some except handle for image broken

### CODE REVIEW

**Comment by piiswrong** [comment]
Looks good. Thanks for your contribution.
One suggestion: could you add serialization in write_worker and preserve the order in image list?

**Comment by junranhe** [comment]
@piiswrong I add it to preserve the order  now

**Comment by piiswrong** [comment]
Thanks, this does make the output .lst consistent with the rec file, but the input .lst file is still different from the output .lst file.
We can merge this now or if you are interested, you can make sink a dictionary, and wait for the next item before writing, and don't forget to delete written items.

**Comment by junranhe** [comment]
@piiswrong sometime my image is broken, and I drop it out, so output.lst  is different from input.lst in fact

**Comment by piiswrong** [comment]
Ok. Please merge in master and we can merge this.

**Comment by junranhe** [comment]
@piiswrong I have merge in master:)

**Pull request merged**
