### PR TITLE
[RFC] Operator priority based on pushed order

### PR DESCRIPTION
**Pull request by jermainewang**
***DO NOT MERGE***

@piiswrong @tqchen @mli 

This branch is for engine refactor. Here is the change needed to fix the memory consumption problem mentioned in #4294 . This is the current solution (though not ideal). More details and thinkings on this problem are in the document I sent to you.

Basic idea:
* Assign a decreasing priority to operators based on their pushed order.
* In such way, if pushed operators could be paralleled, their execution order will be close to the sequential order as much as possible.

For following example:
```python
x = mx.nd.zeros((128, 4096), ctx=mx.gpu(0))
dy = mx.nd.zeros((128, 4096), ctx=mx.gpu(0))
dw = mx.nd.zeros((4096, 4096), ctx=mx.gpu(0))

for i in range(10000):
   dw += mx.nd.dot(x.T, dy)

dw.wait_to_read()
```

Previous engine will raise OOM error. This change will use <500 MB memory.

I want to let MinPy use this version of MXNet in the future to make everything more stable. Please have a look.

Thanks.

### CODE REVIEW

**Comment by piiswrong** [comment]
@howard0su

**Comment by howard0su** [comment]
This change will impact all the current code and cause the parallel execution/dispatching doesn't happen since most of the current code will have 0 as priority.

I suggest to thinking about other direction to consider GPU memory as a resource. Maybe fun to look at how nnvm pass can help this.

**Comment by jermainewang** [comment]
@howard0su , it won't affect the parallelism. It will only affect the dispatch order of parallel operators. If two operators could be run in parallel, they will still be run in parallel.

NNVM pass could help the symbolic part since we have the whole graph, but for imperative way like minpy, we only have segments and graph may change during running. I haven't come up with a good idea of how to utilize NNVM pass for these scenarios. It will definitely be one of the future direction of minpy. Maybe you have more thoughts on this?

**Comment by tqchen** [comment]
Can we implement this with FIFO queue? since the operation on priority queue could be slower than a fifo queue.

**Comment by howard0su** [comment]
I reread the code in engine and dmlc ConcurrentBlockingQueue.

The root cause is that ConcurrentQueue is using std::push_heap to insert op into the list. unfortunately, heap sort is not a stable sort algorithm. So it is not strict FIFO when priority is same (zero in most cases.)

Personally, I don't suggest to merge this fix. instead, we should reimplement ConcurrentBlockingQueue with a stable implementation of PriorityQueue.

Also, when I investigate why threaded engine is slow on CPU. ConcurrentBlockingQueue also introduces contention during worker threads. I am also looking at do some change in this class. @piiswrong

**Comment by jermainewang** [comment]
The so called "FIFO" order is meaningless in the execution since the queue is for operators that all their dependencies have been resolved. Strictly speaking, their execution order is *undefined*, leaving chances for parallelism. FIFO is just our current way of selecting the order, but there is also other orders (like the order based on pushed order) that *may* better than it. Ideally, we should have a global analysis of the whole dag using dynamic programming to find the priority that best saves memory as Eric once suggested. 

@howard0su about the stability, since FIFO is just one alternative, strict FIFO is not required for execution. I think the more critical problem is whether priority queue is fast enough for tiny operators. I tested rnn (written in purely ndarray) with 64 batch size and 512 hidden layer size with 50 unrolling steps, the change does not affect the execution speed. For symbolic execution, it should be better since each operator is more costly and there are fewer of them. However, this requires further investigation.

The PR is not meant for merge. Instead, the branch is for future changes that @piiswrong is also looking at.

**Comment by jermainewang** [comment]
About the order, I always mean the dispatch order. If we only have one worker thread (we have two right now), dispatch order is equal to execution order. Otherwise, the execution order cannot be guaranteed.

**Comment by howard0su** [comment]
I had some offline discussion with @piiswrong 

You are right. my previous comments are not correct.

The concern for the current solution is we overload priority parameter. One possible solution can be:
1. maintain a order count. and assign this count to the newly pushed operation. and order + priority >> 16 as a priority. (need a smart way to handle order overflow)
2. Always prioritize DeleteVariable op so that we can free memory.

**Comment by jermainewang** [comment]
@howard0su that's a good idea. I could help change this on this branch. I don't have a good idea to handle overflow as well. This is another drawback of the priority approach. It will be good that we could come up with some data structure that will simulate this priority. We could do some brainstorm in the engine refactoring document.

If we all agree this. I will keep this branch for future engine change. And I will close this PR.

**Pull request closed without merging**
