### PR TITLE
Enable Bulk Execution of a Subgraph For Faster GPU Serving

### PR DESCRIPTION
**Pull request by tqchen**
This PR enables to push a subgraph as a group, removing sync between all the operations in the subgraph. It contains two commits

- Enable TempSpace resource to persist across several calls, so allocated space in GPU operator will have the same address valid as it executes
- Enable a CreateCachedOpr function to create an operator that executes over the subgraph.
   - The execution mode won't be selected when there is async or operations cross the devices.

Preliminary experiment show that it can improve the prediction speed of small batches on GPU.

see #2462

## Possible Improvement
A smarter scheduler to split the graph into several segments, with each one corresponds to a cached operatpr.

### CODE REVIEW

**Comment by tqchen** [comment]
@winstywang @piiswrong

**Comment by lofrank** [comment]
@tqchen 
This is really useful for small batches.
But it breaks the build, would you please fix it?
https://travis-ci.org/dmlc/mxnet/builds/139618293

**Comment by tqchen** [comment]
this is already merged and functioning in master

**Comment by lofrank** [comment]
@tqchen 
I see you have added a new variable named 'old_handles' in this commit.
https://github.com/tqchen/mxnet/blob/a699d1cd2c8551a669725a6acc3dadadd01ce948/src/resource.cc

But this variable doesn't exist in master branch.
https://github.com/dmlc/mxnet/blob/master/src/resource.cc

So I assume the commit is not merged to master successfully.

**Comment by tqchen** [comment]
That changes get overriden by new commits, but the bulk execution is functioning correctly

**Comment by lofrank** [comment]
@tqchen 
Got it. 
Thanks for your quick response.
I will test it and confirm whether it improves the prediction speed of small batches on GPU.
For my case, the batch size is 1 for most time.

**Comment by lofrank** [comment]
For me (or my model), this commit does not speed up prediction when batch size is one.

**Pull request merged**
