### PR TITLE
Improve Navbar style

### PR DESCRIPTION
**Pull request by kevinthesun**
Adjust navigation bar style to show larger size navigation items.

### CODE REVIEW

**Comment by mli** [comment]
screen shot 2016-12-15 at 1 25 18 pm

logo is too left, we should vertically align it with text below. also search bar is not horizontally aligned.

**Comment by kevinthesun** [comment]
For the search box, I changed it to different line to make room for navigation items. If we want all stuffs in the same line, I can continue adjusting the layout.

**Comment by mli** [comment]
1) change english into Eng, 2) make the box smaller, 3) remove the go button, and change "Search" into "Search, press <Enter> to go"

**Comment by mli** [comment]
we can also remove "get started" in the navbar

**Comment by kevinthesun** [comment]
Sounds good.

**Pull request merged**
