### PR TITLE
Stochastic Depth Training

### PR DESCRIPTION
**Pull request by pluskid**
Simple implementation of Stochastic Depth Training with the Module API. I did not use fancy tricks like constant graph and re-pointing weights, because the prediction needs to use all the layers anyway. The speed on a single GPU seem to be similar to [the torch implementation](https://github.com/yueatsprograms/Stochastic_Depth) (they report 60 seconds, while we are ~50 seconds, but my GPU might be better).

I did not observe good speedup by running multi-GPU, though. Maybe because of overhead of data copying between modules -- note each block is an independent module, so e.g. the 110-layer Resnet has 50+ modules.

I did not try to use the exact hyper parameters as the torch implementation. Both the residual block and the skip connections are also slightly different. Will add final number to the comments after finish running. The progress up to now seems reasonable:

```
INFO:root:Epoch[127] Batch [100]        Speed: 1056.31 samples/sec      Train-accuracy=0.961094
INFO:root:Epoch[127] Batch [150]        Speed: 1041.82 samples/sec      Train-accuracy=0.958438
INFO:root:Epoch[127] Batch [200]        Speed: 1044.29 samples/sec      Train-accuracy=0.949688
INFO:root:Epoch[127] Batch [250]        Speed: 1057.96 samples/sec      Train-accuracy=0.953906
INFO:root:Epoch[127] Batch [300]        Speed: 1054.22 samples/sec      Train-accuracy=0.955781
INFO:root:Epoch[127] Batch [350]        Speed: 1053.62 samples/sec      Train-accuracy=0.952031
INFO:root:Epoch[127] Train-accuracy=0.949920
INFO:root:Epoch[127] Time cost=47.548
INFO:root:Saved checkpoint to "sd-110-0128.params"
INFO:root:Epoch[127] Validation-accuracy=0.894131
```

### CODE REVIEW

**Comment by zlmzju** [comment]
I also tried to implement the drop path method with a simple `CustomOp` layer, which accepts two input and randomly outputs the identity or the summed one. 

But I did not achieve good results with this layer, a little worse than the original resnet.

I observe that your implementation is quite different. Does my idea OK?

**Comment by pluskid** [comment]
@zlmzju I'm not sure exactly how you did it. The implementation above is also slightly worse than the reported number. Roughly 9% error vs 5% error IIRC. But the ResNet architecture are slightly different.

**Comment by zlmzju** [comment]
@pluskid , I can show a simple demo code:
```python
class Drop(mx.operator.CustomOp):
    def __init__(self, probs=[0.5,0.5]):
        self.probs=probs    #can be different for each layer
    def forward(self, is_train, req, in_data, out_data, aux):
        if is_train:        #testing is ignored for demo
            options=[0,1]   #0: only identity, 1: summed result
            self.choice=np.random.choice(options,1,p=self.probs)
        if self.choice==0:
            out=in_data[0]
        elif self.choice==1:
            out=in_data[0]+in_data[1]
        self.assign(out_data[0], req[0], out)
    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        if self.choice==0:
            out_grad0=out_grad[0]
            out_grad1=0
        elif self.choice==1:
            out_grad0=out_grad[0]
            out_grad1=out_grad[0]            
        self.assign(in_grad[0], req[0], out_grad0)
        self.assign(in_grad[1], req[1], out_grad1)

#usage
output=mx.symbol.Custom(data1=identity, data2=residual, op_type='drop')
```

I find that some works achieve very good results with such drop path technique, such as FractalNet, [resnet of resnet](https://arxiv.org/abs/1608.02908) and another similar method [Swapout](https://arxiv.org/abs/1605.06465).

So I think it will help a lot for mxnet users if we can reproduce their results.

**Comment by pluskid** [comment]
@zlmzju I see. I think stochastic depth might have two main effects: one is regularization, and the other is saving computation. The reason that I use imperative scheduling is to avoid extra computation when a branch is skipped. The `CustomOp` way you used might not be able to save the computation. Yes, I agree. It will be very useful for the community if we are able to reproduce those results and have complete examples.

**Comment by zlmzju** [comment]
@pluskid yes, you are right, your implementation is better. I can help test some examples based on my resnet implementation (resnet-110 5%~6% error with so many epochs).

**Pull request merged**
