### PR TITLE
Update static_graph.cc

### PR DESCRIPTION
**Pull request by linkerlin**
set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number

### CODE REVIEW

**Comment by piiswrong** [comment]
Why is this good?

**Comment by tqchen** [comment]
This is used for memory optimization, and usually small number is good

**Comment by linkerlin** [comment]
python lstm_bucketing.py 
Summary of dataset ==================
bucket of len  10 : 19479 samples
bucket of len  20 : 19336 samples
bucket of len  30 : 12208 samples
bucket of len  40 : 3962 samples
bucket of len  50 : 845 samples
bucket of len  60 : 160 samples
Summary of dataset ==================
bucket of len  10 : 1531 samples
bucket of len  20 : 1518 samples
bucket of len  30 : 980 samples
bucket of len  40 : 322 samples
bucket of len  50 : 65 samples
bucket of len  60 : 10 samples
2016-04-09 11:37:06,438 Start training with [gpu(0)]
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[11:37:06] /home/linker/mxnet/src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number

**Comment by tqchen** [comment]
This was an warning to enable the efficient aggregation and save memory. The message was a hint for this experimental feature. It is likely you can benefit from switching it on

**Pull request closed without merging**
