### PR TITLE
add ps-lite in cmake with ps-lite in dev branch

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Comment by hjk41** [comment]
Is it tested on windows?

**Comment by yajiedesign** [comment]
yes,but,must merage https://github.com/dmlc/ps-lite/pull/22 first in ps-lite

**Comment by mli** [comment]
the ps-lite PR is merged, thanks.

could you please try the test at https://github.com/dmlc/mxnet/tree/master/tests/python/multi-node ?

at least for dist_sync_mlp.py and dist_sync_kvstore.py by
```
../../../ps-lite/tracker/dmlc_local.py -n 2 -s 2 ./dist_sync_mlp.py
```

**Comment by yajiedesign** [comment]
@mli ok i run test and fix some promblem

**Pull request merged**
