### PR TITLE
[Scala] Code generation for Symbol

### PR DESCRIPTION
**Pull request by javelinjs**
https://github.com/dmlc/mxnet/issues/3084

Using Scala Macros, we support code generation for `Symbol` functions. The `Symbol` is now automatically up-to-date.
While I changed the APIs slightly to unify the positional arguments and keyword arguments. @xlvector @Ldpe2G Could you help to review this change of APIs?

### CODE REVIEW

**Comment by piiswrong** [comment]
Consider PR this to dmlc:nnvm?

**Comment by javelinjs** [comment]
@piiswrong Do you mean adding it as a frontend for nnvm and make mxnet-scala depend on this 'nnvm-scala' lib?

**Comment by piiswrong** [comment]
No, I mean rebase this on the nnvm branch and send it there.

**Comment by tqchen** [comment]
I think it is fine to bring this to master. I will periodically pull the master into nnvm branch

**Comment by tqchen** [comment]
let us merge this in once the checks are passed

**Comment by javelinjs** [comment]
@tqchen Got it

**Pull request merged**
