### PR TITLE
fix #601

### LINKED ISSUE #601: python doc error in KVstore example
in the KVstore example:
```python
>>> def update(key, input, stored):
>>>     print "update on key: %d" % key
>>>     stored += input * 2
>>> kv.set_updater(update)
```
where `kv.set_updater` should be
`kv._set_updater(update)`

### PR DESCRIPTION
**Pull request by wangg12**

### CODE REVIEW

**Comment by winstywang** [comment]
please rebase this pr before we can merge.

**Comment by wangg12** [comment]
I don't know how to rebase. I haven't done this before.

**Comment by tqchen** [comment]
http://mxnet.readthedocs.org/en/latest/contribute.html#git-workflow-howtos

**Comment by wangg12** [comment]
@winstywang  I am not sure if I've correctly rebased.

**Comment by tqchen** [comment]
Thanks for the PR, have added you to https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md Please feel free to contribute more to mxnet!

**Comment by wangg12** [comment]
@tqchen Thanks!

**Pull request merged**
