### PR TITLE
Create note_memory_zh.md

### PR DESCRIPTION
**Pull request by wac81**

### CODE REVIEW

**Comment by piiswrong** [comment]
@tqchen Should we create a separate folder for chinese docs?

**Comment by tqchen** [comment]
yes, let us put it under doc/zh

**Comment by wac81** [comment]
why does this pull is not succeed？

Some checks were not successful
1 errored and 1 successful checks
Details Required  continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error

**Comment by wac81** [comment]
and i don't see anything in mxnet/master, i should create a folder like /zh?

**Comment by tqchen** [comment]
yes, create mxnet/doc/zh

**Pull request closed without merging**
