### PR TITLE
convert to long int for direct comparison

### PR DESCRIPTION
**Pull request by liangfu**
```self._data_shapes[0].shape``` is ```int``` based shape, and ```data_batch.data``` is ```long int``` base shape result.
The change converts both shape variables into ```long int``` for direct comparison.

### CODE REVIEW

**Comment by piiswrong** [comment]
>>> 1 == 1L
True

**Comment by liangfu** [comment]
>>> (i for i in range(2))==(i for i in range(2))
False

**Comment by piiswrong** [comment]
This is due to (...) returns a generator.
I think the right fix is to change to tuple(...)
```
>>> tuple(i for i in range(2)) == tuple(i for i in range(2))
True
```

**Comment by liangfu** [comment]
Agree, ideally solved the problem.

**Pull request merged**
